// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: azd/extensions/v1beta/account.proto

package v1beta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrincipalType int32

const (
	PrincipalType_PRINCIPAL_TYPE_UNSPECIFIED       PrincipalType = 0
	PrincipalType_PRINCIPAL_TYPE_USER              PrincipalType = 1
	PrincipalType_PRINCIPAL_TYPE_SERVICE_PRINCIPAL PrincipalType = 2
)

// Enum value maps for PrincipalType.
var (
	PrincipalType_name = map[int32]string{
		0: "PRINCIPAL_TYPE_UNSPECIFIED",
		1: "PRINCIPAL_TYPE_USER",
		2: "PRINCIPAL_TYPE_SERVICE_PRINCIPAL",
	}
	PrincipalType_value = map[string]int32{
		"PRINCIPAL_TYPE_UNSPECIFIED":       0,
		"PRINCIPAL_TYPE_USER":              1,
		"PRINCIPAL_TYPE_SERVICE_PRINCIPAL": 2,
	}
)

func (x PrincipalType) Enum() *PrincipalType {
	p := new(PrincipalType)
	*p = x
	return p
}

func (x PrincipalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrincipalType) Descriptor() protoreflect.EnumDescriptor {
	return file_azd_extensions_v1beta_account_proto_enumTypes[0].Descriptor()
}

func (PrincipalType) Type() protoreflect.EnumType {
	return &file_azd_extensions_v1beta_account_proto_enumTypes[0]
}

func (x PrincipalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrincipalType.Descriptor instead.
func (PrincipalType) EnumDescriptor() ([]byte, []int) {
	return file_azd_extensions_v1beta_account_proto_rawDescGZIP(), []int{0}
}

type ListSubscriptionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter subscriptions by tenant ID.
	TenantId      *string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsRequest) Reset() {
	*x = ListSubscriptionsRequest{}
	mi := &file_azd_extensions_v1beta_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsRequest) ProtoMessage() {}

func (x *ListSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_azd_extensions_v1beta_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_azd_extensions_v1beta_account_proto_rawDescGZIP(), []int{0}
}

func (x *ListSubscriptionsRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

type ListSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsResponse) Reset() {
	*x = ListSubscriptionsResponse{}
	mi := &file_azd_extensions_v1beta_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsResponse) ProtoMessage() {}

func (x *ListSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_azd_extensions_v1beta_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_azd_extensions_v1beta_account_proto_rawDescGZIP(), []int{1}
}

func (x *ListSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type LookupTenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The subscription ID to lookup the tenant for.
	SubscriptionId string `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LookupTenantRequest) Reset() {
	*x = LookupTenantRequest{}
	mi := &file_azd_extensions_v1beta_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupTenantRequest) ProtoMessage() {}

func (x *LookupTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_azd_extensions_v1beta_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupTenantRequest.ProtoReflect.Descriptor instead.
func (*LookupTenantRequest) Descriptor() ([]byte, []int) {
	return file_azd_extensions_v1beta_account_proto_rawDescGZIP(), []int{2}
}

func (x *LookupTenantRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type LookupTenantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tenant ID required to access the subscription.
	TenantId      string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupTenantResponse) Reset() {
	*x = LookupTenantResponse{}
	mi := &file_azd_extensions_v1beta_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupTenantResponse) ProtoMessage() {}

func (x *LookupTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_azd_extensions_v1beta_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupTenantResponse.ProtoReflect.Descriptor instead.
func (*LookupTenantResponse) Descriptor() ([]byte, []int) {
	return file_azd_extensions_v1beta_account_proto_rawDescGZIP(), []int{3}
}

func (x *LookupTenantResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetCurrentPrincipalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required subscription ID. The active environment is not used as a default.
	SubscriptionId string `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCurrentPrincipalRequest) Reset() {
	*x = GetCurrentPrincipalRequest{}
	mi := &file_azd_extensions_v1beta_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPrincipalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPrincipalRequest) ProtoMessage() {}

func (x *GetCurrentPrincipalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_azd_extensions_v1beta_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPrincipalRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentPrincipalRequest) Descriptor() ([]byte, []int) {
	return file_azd_extensions_v1beta_account_proto_rawDescGZIP(), []int{4}
}

func (x *GetCurrentPrincipalRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type GetCurrentPrincipalResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Object ID in the subscription's resource tenant, not the user's home tenant or an application client ID.
	ObjectId string `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// Principal type determined from the host's login details.
	PrincipalType PrincipalType `protobuf:"varint,2,opt,name=principal_type,json=principalType,proto3,enum=azd.extensions.v1beta.PrincipalType" json:"principal_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentPrincipalResponse) Reset() {
	*x = GetCurrentPrincipalResponse{}
	mi := &file_azd_extensions_v1beta_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPrincipalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPrincipalResponse) ProtoMessage() {}

func (x *GetCurrentPrincipalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_azd_extensions_v1beta_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPrincipalResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentPrincipalResponse) Descriptor() ([]byte, []int) {
	return file_azd_extensions_v1beta_account_proto_rawDescGZIP(), []int{5}
}

func (x *GetCurrentPrincipalResponse) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetCurrentPrincipalResponse) GetPrincipalType() PrincipalType {
	if x != nil {
		return x.PrincipalType
	}
	return PrincipalType_PRINCIPAL_TYPE_UNSPECIFIED
}

var File_azd_extensions_v1beta_account_proto protoreflect.FileDescriptor

const file_azd_extensions_v1beta_account_proto_rawDesc = "" +
	"\n" +
	"#azd/extensions/v1beta/account.proto\x12\x15azd.extensions.v1beta\x1a\"azd/extensions/v1beta/models.proto\"J\n" +
	"\x18ListSubscriptionsRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\tH\x00R\btenantId\x88\x01\x01B\f\n" +
	"\n" +
	"_tenant_id\"f\n" +
	"\x19ListSubscriptionsResponse\x12I\n" +
	"\rsubscriptions\x18\x01 \x03(\v2#.azd.extensions.v1beta.SubscriptionR\rsubscriptions\">\n" +
	"\x13LookupTenantRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"3\n" +
	"\x14LookupTenantResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"E\n" +
	"\x1aGetCurrentPrincipalRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"\x87\x01\n" +
	"\x1bGetCurrentPrincipalResponse\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12K\n" +
	"\x0eprincipal_type\x18\x02 \x01(\x0e2$.azd.extensions.v1beta.PrincipalTypeR\rprincipalType*n\n" +
	"\rPrincipalType\x12\x1e\n" +
	"\x1aPRINCIPAL_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PRINCIPAL_TYPE_USER\x10\x01\x12$\n" +
	" PRINCIPAL_TYPE_SERVICE_PRINCIPAL\x10\x022\xef\x02\n" +
	"\x0eAccountService\x12v\n" +
	"\x11ListSubscriptions\x12/.azd.extensions.v1beta.ListSubscriptionsRequest\x1a0.azd.extensions.v1beta.ListSubscriptionsResponse\x12g\n" +
	"\fLookupTenant\x12*.azd.extensions.v1beta.LookupTenantRequest\x1a+.azd.extensions.v1beta.LookupTenantResponse\x12|\n" +
	"\x13GetCurrentPrincipal\x121.azd.extensions.v1beta.GetCurrentPrincipalRequest\x1a2.azd.extensions.v1beta.GetCurrentPrincipalResponseBGZEgithub.com/azure/azure-dev/cli/azd/pkg/azdext/contracts/v1beta;v1betab\x06proto3"

var (
	file_azd_extensions_v1beta_account_proto_rawDescOnce sync.Once
	file_azd_extensions_v1beta_account_proto_rawDescData []byte
)

func file_azd_extensions_v1beta_account_proto_rawDescGZIP() []byte {
	file_azd_extensions_v1beta_account_proto_rawDescOnce.Do(func() {
		file_azd_extensions_v1beta_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_azd_extensions_v1beta_account_proto_rawDesc), len(file_azd_extensions_v1beta_account_proto_rawDesc)))
	})
	return file_azd_extensions_v1beta_account_proto_rawDescData
}

var file_azd_extensions_v1beta_account_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_azd_extensions_v1beta_account_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_azd_extensions_v1beta_account_proto_goTypes = []any{
	(PrincipalType)(0),                  // 0: azd.extensions.v1beta.PrincipalType
	(*ListSubscriptionsRequest)(nil),    // 1: azd.extensions.v1beta.ListSubscriptionsRequest
	(*ListSubscriptionsResponse)(nil),   // 2: azd.extensions.v1beta.ListSubscriptionsResponse
	(*LookupTenantRequest)(nil),         // 3: azd.extensions.v1beta.LookupTenantRequest
	(*LookupTenantResponse)(nil),        // 4: azd.extensions.v1beta.LookupTenantResponse
	(*GetCurrentPrincipalRequest)(nil),  // 5: azd.extensions.v1beta.GetCurrentPrincipalRequest
	(*GetCurrentPrincipalResponse)(nil), // 6: azd.extensions.v1beta.GetCurrentPrincipalResponse
	(*Subscription)(nil),                // 7: azd.extensions.v1beta.Subscription
}
var file_azd_extensions_v1beta_account_proto_depIdxs = []int32{
	7, // 0: azd.extensions.v1beta.ListSubscriptionsResponse.subscriptions:type_name -> azd.extensions.v1beta.Subscription
	0, // 1: azd.extensions.v1beta.GetCurrentPrincipalResponse.principal_type:type_name -> azd.extensions.v1beta.PrincipalType
	1, // 2: azd.extensions.v1beta.AccountService.ListSubscriptions:input_type -> azd.extensions.v1beta.ListSubscriptionsRequest
	3, // 3: azd.extensions.v1beta.AccountService.LookupTenant:input_type -> azd.extensions.v1beta.LookupTenantRequest
	5, // 4: azd.extensions.v1beta.AccountService.GetCurrentPrincipal:input_type -> azd.extensions.v1beta.GetCurrentPrincipalRequest
	2, // 5: azd.extensions.v1beta.AccountService.ListSubscriptions:output_type -> azd.extensions.v1beta.ListSubscriptionsResponse
	4, // 6: azd.extensions.v1beta.AccountService.LookupTenant:output_type -> azd.extensions.v1beta.LookupTenantResponse
	6, // 7: azd.extensions.v1beta.AccountService.GetCurrentPrincipal:output_type -> azd.extensions.v1beta.GetCurrentPrincipalResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_azd_extensions_v1beta_account_proto_init() }
func file_azd_extensions_v1beta_account_proto_init() {
	if File_azd_extensions_v1beta_account_proto != nil {
		return
	}
	file_azd_extensions_v1beta_models_proto_init()
	file_azd_extensions_v1beta_account_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_azd_extensions_v1beta_account_proto_rawDesc), len(file_azd_extensions_v1beta_account_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_azd_extensions_v1beta_account_proto_goTypes,
		DependencyIndexes: file_azd_extensions_v1beta_account_proto_depIdxs,
		EnumInfos:         file_azd_extensions_v1beta_account_proto_enumTypes,
		MessageInfos:      file_azd_extensions_v1beta_account_proto_msgTypes,
	}.Build()
	File_azd_extensions_v1beta_account_proto = out.File
	file_azd_extensions_v1beta_account_proto_goTypes = nil
	file_azd_extensions_v1beta_account_proto_depIdxs = nil
}
