// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: azd/extensions/v1beta/follow_up.proto

package v1beta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetFollowUpRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier supplied with the project handler invocation.
	InvocationId string `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	// Empty text explicitly clears the contribution.
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFollowUpRequest) Reset() {
	*x = SetFollowUpRequest{}
	mi := &file_azd_extensions_v1beta_follow_up_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFollowUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFollowUpRequest) ProtoMessage() {}

func (x *SetFollowUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_azd_extensions_v1beta_follow_up_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFollowUpRequest.ProtoReflect.Descriptor instead.
func (*SetFollowUpRequest) Descriptor() ([]byte, []int) {
	return file_azd_extensions_v1beta_follow_up_proto_rawDescGZIP(), []int{0}
}

func (x *SetFollowUpRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *SetFollowUpRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SetFollowUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFollowUpResponse) Reset() {
	*x = SetFollowUpResponse{}
	mi := &file_azd_extensions_v1beta_follow_up_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFollowUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFollowUpResponse) ProtoMessage() {}

func (x *SetFollowUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_azd_extensions_v1beta_follow_up_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFollowUpResponse.ProtoReflect.Descriptor instead.
func (*SetFollowUpResponse) Descriptor() ([]byte, []int) {
	return file_azd_extensions_v1beta_follow_up_proto_rawDescGZIP(), []int{1}
}

var File_azd_extensions_v1beta_follow_up_proto protoreflect.FileDescriptor

const file_azd_extensions_v1beta_follow_up_proto_rawDesc = "" +
	"\n" +
	"%azd/extensions/v1beta/follow_up.proto\x12\x15azd.extensions.v1beta\"M\n" +
	"\x12SetFollowUpRequest\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x15\n" +
	"\x13SetFollowUpResponse2w\n" +
	"\x0fFollowUpService\x12d\n" +
	"\vSetFollowUp\x12).azd.extensions.v1beta.SetFollowUpRequest\x1a*.azd.extensions.v1beta.SetFollowUpResponseBGZEgithub.com/azure/azure-dev/cli/azd/pkg/azdext/contracts/v1beta;v1betab\x06proto3"

var (
	file_azd_extensions_v1beta_follow_up_proto_rawDescOnce sync.Once
	file_azd_extensions_v1beta_follow_up_proto_rawDescData []byte
)

func file_azd_extensions_v1beta_follow_up_proto_rawDescGZIP() []byte {
	file_azd_extensions_v1beta_follow_up_proto_rawDescOnce.Do(func() {
		file_azd_extensions_v1beta_follow_up_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_azd_extensions_v1beta_follow_up_proto_rawDesc), len(file_azd_extensions_v1beta_follow_up_proto_rawDesc)))
	})
	return file_azd_extensions_v1beta_follow_up_proto_rawDescData
}

var file_azd_extensions_v1beta_follow_up_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_azd_extensions_v1beta_follow_up_proto_goTypes = []any{
	(*SetFollowUpRequest)(nil),  // 0: azd.extensions.v1beta.SetFollowUpRequest
	(*SetFollowUpResponse)(nil), // 1: azd.extensions.v1beta.SetFollowUpResponse
}
var file_azd_extensions_v1beta_follow_up_proto_depIdxs = []int32{
	0, // 0: azd.extensions.v1beta.FollowUpService.SetFollowUp:input_type -> azd.extensions.v1beta.SetFollowUpRequest
	1, // 1: azd.extensions.v1beta.FollowUpService.SetFollowUp:output_type -> azd.extensions.v1beta.SetFollowUpResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_azd_extensions_v1beta_follow_up_proto_init() }
func file_azd_extensions_v1beta_follow_up_proto_init() {
	if File_azd_extensions_v1beta_follow_up_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_azd_extensions_v1beta_follow_up_proto_rawDesc), len(file_azd_extensions_v1beta_follow_up_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_azd_extensions_v1beta_follow_up_proto_goTypes,
		DependencyIndexes: file_azd_extensions_v1beta_follow_up_proto_depIdxs,
		MessageInfos:      file_azd_extensions_v1beta_follow_up_proto_msgTypes,
	}.Build()
	File_azd_extensions_v1beta_follow_up_proto = out.File
	file_azd_extensions_v1beta_follow_up_proto_goTypes = nil
	file_azd_extensions_v1beta_follow_up_proto_depIdxs = nil
}
