apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-api-config
data:
  AZURE_AKS_IDENTITY_CLIENT_ID: {{.Env.AZURE_AKS_IDENTITY_CLIENT_ID}}
  AZURE_KEY_VAULT_ENDPOINT: {{.Env.AZURE_KEY_VAULT_ENDPOINT}}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{.Env.APPLICATIONINSIGHTS_CONNECTION_STRING}}