// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by grpc/generatefacade. DO NOT EDIT.

package azdext

import (
	v1 "github.com/azure/azure-dev/cli/azd/pkg/azdext/contracts/v1"
	"google.golang.org/grpc"
)

const (
	AccountService_ListSubscriptions_FullMethodName                        = v1.AccountService_ListSubscriptions_FullMethodName
	AccountService_LookupTenant_FullMethodName                             = v1.AccountService_LookupTenant_FullMethodName
	AiModelService_ListLocationsWithQuota_FullMethodName                   = v1.AiModelService_ListLocationsWithQuota_FullMethodName
	AiModelService_ListModelLocationsWithQuota_FullMethodName              = v1.AiModelService_ListModelLocationsWithQuota_FullMethodName
	AiModelService_ListModels_FullMethodName                               = v1.AiModelService_ListModels_FullMethodName
	AiModelService_ListUsages_FullMethodName                               = v1.AiModelService_ListUsages_FullMethodName
	AiModelService_ResolveModelDeployments_FullMethodName                  = v1.AiModelService_ResolveModelDeployments_FullMethodName
	ArtifactKind_ARTIFACT_KIND_ARCHIVE                                     = v1.ArtifactKind_ARTIFACT_KIND_ARCHIVE
	ArtifactKind_ARTIFACT_KIND_CONFIG                                      = v1.ArtifactKind_ARTIFACT_KIND_CONFIG
	ArtifactKind_ARTIFACT_KIND_CONTAINER                                   = v1.ArtifactKind_ARTIFACT_KIND_CONTAINER
	ArtifactKind_ARTIFACT_KIND_DEPLOYMENT                                  = v1.ArtifactKind_ARTIFACT_KIND_DEPLOYMENT
	ArtifactKind_ARTIFACT_KIND_DIRECTORY                                   = v1.ArtifactKind_ARTIFACT_KIND_DIRECTORY
	ArtifactKind_ARTIFACT_KIND_ENDPOINT                                    = v1.ArtifactKind_ARTIFACT_KIND_ENDPOINT
	ArtifactKind_ARTIFACT_KIND_RESOURCE                                    = v1.ArtifactKind_ARTIFACT_KIND_RESOURCE
	ArtifactKind_ARTIFACT_KIND_UNSPECIFIED                                 = v1.ArtifactKind_ARTIFACT_KIND_UNSPECIFIED
	ComposeService_AddResource_FullMethodName                              = v1.ComposeService_AddResource_FullMethodName
	ComposeService_GetResourceType_FullMethodName                          = v1.ComposeService_GetResourceType_FullMethodName
	ComposeService_GetResource_FullMethodName                              = v1.ComposeService_GetResource_FullMethodName
	ComposeService_ListResourceTypes_FullMethodName                        = v1.ComposeService_ListResourceTypes_FullMethodName
	ComposeService_ListResources_FullMethodName                            = v1.ComposeService_ListResources_FullMethodName
	ContainerService_Build_FullMethodName                                  = v1.ContainerService_Build_FullMethodName
	ContainerService_Package_FullMethodName                                = v1.ContainerService_Package_FullMethodName
	ContainerService_Publish_FullMethodName                                = v1.ContainerService_Publish_FullMethodName
	CopilotFileChangeType_COPILOT_FILE_CHANGE_TYPE_CREATED                 = v1.CopilotFileChangeType_COPILOT_FILE_CHANGE_TYPE_CREATED
	CopilotFileChangeType_COPILOT_FILE_CHANGE_TYPE_DELETED                 = v1.CopilotFileChangeType_COPILOT_FILE_CHANGE_TYPE_DELETED
	CopilotFileChangeType_COPILOT_FILE_CHANGE_TYPE_MODIFIED                = v1.CopilotFileChangeType_COPILOT_FILE_CHANGE_TYPE_MODIFIED
	CopilotFileChangeType_COPILOT_FILE_CHANGE_TYPE_UNSPECIFIED             = v1.CopilotFileChangeType_COPILOT_FILE_CHANGE_TYPE_UNSPECIFIED
	CopilotService_GetFileChanges_FullMethodName                           = v1.CopilotService_GetFileChanges_FullMethodName
	CopilotService_GetMessages_FullMethodName                              = v1.CopilotService_GetMessages_FullMethodName
	CopilotService_GetUsageMetrics_FullMethodName                          = v1.CopilotService_GetUsageMetrics_FullMethodName
	CopilotService_Initialize_FullMethodName                               = v1.CopilotService_Initialize_FullMethodName
	CopilotService_ListSessions_FullMethodName                             = v1.CopilotService_ListSessions_FullMethodName
	CopilotService_SendMessage_FullMethodName                              = v1.CopilotService_SendMessage_FullMethodName
	CopilotService_StopSession_FullMethodName                              = v1.CopilotService_StopSession_FullMethodName
	DeploymentService_GetDeploymentContext_FullMethodName                  = v1.DeploymentService_GetDeploymentContext_FullMethodName
	DeploymentService_GetDeployment_FullMethodName                         = v1.DeploymentService_GetDeployment_FullMethodName
	EnvironmentService_GetConfigSection_FullMethodName                     = v1.EnvironmentService_GetConfigSection_FullMethodName
	EnvironmentService_GetConfigString_FullMethodName                      = v1.EnvironmentService_GetConfigString_FullMethodName
	EnvironmentService_GetConfig_FullMethodName                            = v1.EnvironmentService_GetConfig_FullMethodName
	EnvironmentService_GetCurrent_FullMethodName                           = v1.EnvironmentService_GetCurrent_FullMethodName
	EnvironmentService_GetValue_FullMethodName                             = v1.EnvironmentService_GetValue_FullMethodName
	EnvironmentService_GetValues_FullMethodName                            = v1.EnvironmentService_GetValues_FullMethodName
	EnvironmentService_Get_FullMethodName                                  = v1.EnvironmentService_Get_FullMethodName
	EnvironmentService_List_FullMethodName                                 = v1.EnvironmentService_List_FullMethodName
	EnvironmentService_Select_FullMethodName                               = v1.EnvironmentService_Select_FullMethodName
	EnvironmentService_SetConfig_FullMethodName                            = v1.EnvironmentService_SetConfig_FullMethodName
	EnvironmentService_SetValue_FullMethodName                             = v1.EnvironmentService_SetValue_FullMethodName
	EnvironmentService_UnsetConfig_FullMethodName                          = v1.EnvironmentService_UnsetConfig_FullMethodName
	ErrorOrigin_ERROR_ORIGIN_LOCAL                                         = v1.ErrorOrigin_ERROR_ORIGIN_LOCAL
	ErrorOrigin_ERROR_ORIGIN_SERVICE                                       = v1.ErrorOrigin_ERROR_ORIGIN_SERVICE
	ErrorOrigin_ERROR_ORIGIN_TOOL                                          = v1.ErrorOrigin_ERROR_ORIGIN_TOOL
	ErrorOrigin_ERROR_ORIGIN_UNSPECIFIED                                   = v1.ErrorOrigin_ERROR_ORIGIN_UNSPECIFIED
	EventService_EventStream_FullMethodName                                = v1.EventService_EventStream_FullMethodName
	ExtensionService_Ready_FullMethodName                                  = v1.ExtensionService_Ready_FullMethodName
	ExtensionService_ReportError_FullMethodName                            = v1.ExtensionService_ReportError_FullMethodName
	FrameworkService_Stream_FullMethodName                                 = v1.FrameworkService_Stream_FullMethodName
	LocationKind_LOCATION_KIND_LOCAL                                       = v1.LocationKind_LOCATION_KIND_LOCAL
	LocationKind_LOCATION_KIND_REMOTE                                      = v1.LocationKind_LOCATION_KIND_REMOTE
	LocationKind_LOCATION_KIND_UNSPECIFIED                                 = v1.LocationKind_LOCATION_KIND_UNSPECIFIED
	ProjectService_AddService_FullMethodName                               = v1.ProjectService_AddService_FullMethodName
	ProjectService_GetConfigSection_FullMethodName                         = v1.ProjectService_GetConfigSection_FullMethodName
	ProjectService_GetConfigValue_FullMethodName                           = v1.ProjectService_GetConfigValue_FullMethodName
	ProjectService_GetResolvedServices_FullMethodName                      = v1.ProjectService_GetResolvedServices_FullMethodName
	ProjectService_GetServiceConfigSection_FullMethodName                  = v1.ProjectService_GetServiceConfigSection_FullMethodName
	ProjectService_GetServiceConfigValue_FullMethodName                    = v1.ProjectService_GetServiceConfigValue_FullMethodName
	ProjectService_GetServiceTargetResource_FullMethodName                 = v1.ProjectService_GetServiceTargetResource_FullMethodName
	ProjectService_Get_FullMethodName                                      = v1.ProjectService_Get_FullMethodName
	ProjectService_ParseGitHubUrl_FullMethodName                           = v1.ProjectService_ParseGitHubUrl_FullMethodName
	ProjectService_SetConfigSection_FullMethodName                         = v1.ProjectService_SetConfigSection_FullMethodName
	ProjectService_SetConfigValue_FullMethodName                           = v1.ProjectService_SetConfigValue_FullMethodName
	ProjectService_SetServiceConfigSection_FullMethodName                  = v1.ProjectService_SetServiceConfigSection_FullMethodName
	ProjectService_SetServiceConfigValue_FullMethodName                    = v1.ProjectService_SetServiceConfigValue_FullMethodName
	ProjectService_UnsetConfig_FullMethodName                              = v1.ProjectService_UnsetConfig_FullMethodName
	ProjectService_UnsetServiceConfig_FullMethodName                       = v1.ProjectService_UnsetServiceConfig_FullMethodName
	PromptService_Confirm_FullMethodName                                   = v1.PromptService_Confirm_FullMethodName
	PromptService_MultiSelect_FullMethodName                               = v1.PromptService_MultiSelect_FullMethodName
	PromptService_PromptAiDeployment_FullMethodName                        = v1.PromptService_PromptAiDeployment_FullMethodName
	PromptService_PromptAiLocationWithQuota_FullMethodName                 = v1.PromptService_PromptAiLocationWithQuota_FullMethodName
	PromptService_PromptAiModelLocationWithQuota_FullMethodName            = v1.PromptService_PromptAiModelLocationWithQuota_FullMethodName
	PromptService_PromptAiModel_FullMethodName                             = v1.PromptService_PromptAiModel_FullMethodName
	PromptService_PromptLocation_FullMethodName                            = v1.PromptService_PromptLocation_FullMethodName
	PromptService_PromptResourceGroupResource_FullMethodName               = v1.PromptService_PromptResourceGroupResource_FullMethodName
	PromptService_PromptResourceGroup_FullMethodName                       = v1.PromptService_PromptResourceGroup_FullMethodName
	PromptService_PromptSubscriptionResource_FullMethodName                = v1.PromptService_PromptSubscriptionResource_FullMethodName
	PromptService_PromptSubscription_FullMethodName                        = v1.PromptService_PromptSubscription_FullMethodName
	PromptService_Prompt_FullMethodName                                    = v1.PromptService_Prompt_FullMethodName
	PromptService_Select_FullMethodName                                    = v1.PromptService_Select_FullMethodName
	ProvisioningService_Stream_FullMethodName                              = v1.ProvisioningService_Stream_FullMethodName
	ProvisioningSkippedReason_PROVISIONING_SKIPPED_REASON_DEPLOYMENT_STATE = v1.ProvisioningSkippedReason_PROVISIONING_SKIPPED_REASON_DEPLOYMENT_STATE
	ProvisioningSkippedReason_PROVISIONING_SKIPPED_REASON_UNSPECIFIED      = v1.ProvisioningSkippedReason_PROVISIONING_SKIPPED_REASON_UNSPECIFIED
	ServiceTargetService_Stream_FullMethodName                             = v1.ServiceTargetService_Stream_FullMethodName
	TelemetryService_ReportUsage_FullMethodName                            = v1.TelemetryService_ReportUsage_FullMethodName
	UserConfigService_GetSection_FullMethodName                            = v1.UserConfigService_GetSection_FullMethodName
	UserConfigService_GetString_FullMethodName                             = v1.UserConfigService_GetString_FullMethodName
	UserConfigService_Get_FullMethodName                                   = v1.UserConfigService_Get_FullMethodName
	UserConfigService_Set_FullMethodName                                   = v1.UserConfigService_Set_FullMethodName
	UserConfigService_Unset_FullMethodName                                 = v1.UserConfigService_Unset_FullMethodName
	ValidationCheckSeverity_VALIDATION_CHECK_SEVERITY_ERROR                = v1.ValidationCheckSeverity_VALIDATION_CHECK_SEVERITY_ERROR
	ValidationCheckSeverity_VALIDATION_CHECK_SEVERITY_WARNING              = v1.ValidationCheckSeverity_VALIDATION_CHECK_SEVERITY_WARNING
	ValidationService_Stream_FullMethodName                                = v1.ValidationService_Stream_FullMethodName
	WorkflowService_Run_FullMethodName                                     = v1.WorkflowService_Run_FullMethodName
)

type (
	AccountServiceClient                                     = v1.AccountServiceClient
	AccountServiceServer                                     = v1.AccountServiceServer
	ActionableErrorDetail                                    = v1.ActionableErrorDetail
	AddResourceRequest                                       = v1.AddResourceRequest
	AddResourceResponse                                      = v1.AddResourceResponse
	AddServiceRequest                                        = v1.AddServiceRequest
	AiModel                                                  = v1.AiModel
	AiModelDeployment                                        = v1.AiModelDeployment
	AiModelDeploymentOptions                                 = v1.AiModelDeploymentOptions
	AiModelFilterOptions                                     = v1.AiModelFilterOptions
	AiModelServiceClient                                     = v1.AiModelServiceClient
	AiModelServiceServer                                     = v1.AiModelServiceServer
	AiModelSku                                               = v1.AiModelSku
	AiModelUsage                                             = v1.AiModelUsage
	AiModelVersion                                           = v1.AiModelVersion
	Artifact                                                 = v1.Artifact
	ArtifactKind                                             = v1.ArtifactKind
	ArtifactList                                             = v1.ArtifactList
	AzureContext                                             = v1.AzureContext
	AzureScope                                               = v1.AzureScope
	ComposeServiceClient                                     = v1.ComposeServiceClient
	ComposeServiceServer                                     = v1.ComposeServiceServer
	ComposedResource                                         = v1.ComposedResource
	ComposedResourceType                                     = v1.ComposedResourceType
	ConfirmOptions                                           = v1.ConfirmOptions
	ConfirmRequest                                           = v1.ConfirmRequest
	ConfirmResponse                                          = v1.ConfirmResponse
	ContainerBuildRequest                                    = v1.ContainerBuildRequest
	ContainerBuildResponse                                   = v1.ContainerBuildResponse
	ContainerPackageRequest                                  = v1.ContainerPackageRequest
	ContainerPackageResponse                                 = v1.ContainerPackageResponse
	ContainerPublishRequest                                  = v1.ContainerPublishRequest
	ContainerPublishResponse                                 = v1.ContainerPublishResponse
	ContainerServiceClient                                   = v1.ContainerServiceClient
	ContainerServiceServer                                   = v1.ContainerServiceServer
	CopilotFileChange                                        = v1.CopilotFileChange
	CopilotFileChangeType                                    = v1.CopilotFileChangeType
	CopilotServiceClient                                     = v1.CopilotServiceClient
	CopilotServiceServer                                     = v1.CopilotServiceServer
	CopilotSessionEvent                                      = v1.CopilotSessionEvent
	CopilotSessionMetadata                                   = v1.CopilotSessionMetadata
	CopilotUsageMetrics                                      = v1.CopilotUsageMetrics
	Deployment                                               = v1.Deployment
	DeploymentServiceClient                                  = v1.DeploymentServiceClient
	DeploymentServiceServer                                  = v1.DeploymentServiceServer
	DockerProjectOptions                                     = v1.DockerProjectOptions
	EmptyRequest                                             = v1.EmptyRequest
	EmptyResponse                                            = v1.EmptyResponse
	Environment                                              = v1.Environment
	EnvironmentDescription                                   = v1.EnvironmentDescription
	EnvironmentListResponse                                  = v1.EnvironmentListResponse
	EnvironmentResponse                                      = v1.EnvironmentResponse
	EnvironmentServiceClient                                 = v1.EnvironmentServiceClient
	EnvironmentServiceServer                                 = v1.EnvironmentServiceServer
	ErrorLink                                                = v1.ErrorLink
	ErrorOrigin                                              = v1.ErrorOrigin
	EventMessage                                             = v1.EventMessage
	EventMessage_InvokeProjectHandler                        = v1.EventMessage_InvokeProjectHandler
	EventMessage_InvokeServiceHandler                        = v1.EventMessage_InvokeServiceHandler
	EventMessage_ProjectHandlerStatus                        = v1.EventMessage_ProjectHandlerStatus
	EventMessage_ServiceHandlerStatus                        = v1.EventMessage_ServiceHandlerStatus
	EventMessage_SubscribeProjectEvent                       = v1.EventMessage_SubscribeProjectEvent
	EventMessage_SubscribeServiceEvent                       = v1.EventMessage_SubscribeServiceEvent
	EventServiceClient                                       = v1.EventServiceClient
	EventServiceServer                                       = v1.EventServiceServer
	EventService_EventStreamClient                           = v1.EventService_EventStreamClient
	EventService_EventStreamServer                           = v1.EventService_EventStreamServer
	ExtensionError                                           = v1.ExtensionError
	ExtensionError_LocalError                                = v1.ExtensionError_LocalError
	ExtensionError_ServiceError                              = v1.ExtensionError_ServiceError
	ExtensionServiceClient                                   = v1.ExtensionServiceClient
	ExtensionServiceServer                                   = v1.ExtensionServiceServer
	ExternalTool                                             = v1.ExternalTool
	FrameworkPackageRequirements                             = v1.FrameworkPackageRequirements
	FrameworkRequirements                                    = v1.FrameworkRequirements
	FrameworkServiceBuildRequest                             = v1.FrameworkServiceBuildRequest
	FrameworkServiceBuildResponse                            = v1.FrameworkServiceBuildResponse
	FrameworkServiceClient                                   = v1.FrameworkServiceClient
	FrameworkServiceInitializeRequest                        = v1.FrameworkServiceInitializeRequest
	FrameworkServiceInitializeResponse                       = v1.FrameworkServiceInitializeResponse
	FrameworkServiceMessage                                  = v1.FrameworkServiceMessage
	FrameworkServiceMessage_BuildRequest                     = v1.FrameworkServiceMessage_BuildRequest
	FrameworkServiceMessage_BuildResponse                    = v1.FrameworkServiceMessage_BuildResponse
	FrameworkServiceMessage_InitializeRequest                = v1.FrameworkServiceMessage_InitializeRequest
	FrameworkServiceMessage_InitializeResponse               = v1.FrameworkServiceMessage_InitializeResponse
	FrameworkServiceMessage_PackageRequest                   = v1.FrameworkServiceMessage_PackageRequest
	FrameworkServiceMessage_PackageResponse                  = v1.FrameworkServiceMessage_PackageResponse
	FrameworkServiceMessage_ProgressMessage                  = v1.FrameworkServiceMessage_ProgressMessage
	FrameworkServiceMessage_RegisterFrameworkServiceRequest  = v1.FrameworkServiceMessage_RegisterFrameworkServiceRequest
	FrameworkServiceMessage_RegisterFrameworkServiceResponse = v1.FrameworkServiceMessage_RegisterFrameworkServiceResponse
	FrameworkServiceMessage_RequiredExternalToolsRequest     = v1.FrameworkServiceMessage_RequiredExternalToolsRequest
	FrameworkServiceMessage_RequiredExternalToolsResponse    = v1.FrameworkServiceMessage_RequiredExternalToolsResponse
	FrameworkServiceMessage_RequirementsRequest              = v1.FrameworkServiceMessage_RequirementsRequest
	FrameworkServiceMessage_RequirementsResponse             = v1.FrameworkServiceMessage_RequirementsResponse
	FrameworkServiceMessage_RestoreRequest                   = v1.FrameworkServiceMessage_RestoreRequest
	FrameworkServiceMessage_RestoreResponse                  = v1.FrameworkServiceMessage_RestoreResponse
	FrameworkServicePackageRequest                           = v1.FrameworkServicePackageRequest
	FrameworkServicePackageResponse                          = v1.FrameworkServicePackageResponse
	FrameworkServiceProgressMessage                          = v1.FrameworkServiceProgressMessage
	FrameworkServiceRequiredExternalToolsRequest             = v1.FrameworkServiceRequiredExternalToolsRequest
	FrameworkServiceRequiredExternalToolsResponse            = v1.FrameworkServiceRequiredExternalToolsResponse
	FrameworkServiceRequirementsRequest                      = v1.FrameworkServiceRequirementsRequest
	FrameworkServiceRequirementsResponse                     = v1.FrameworkServiceRequirementsResponse
	FrameworkServiceRestoreRequest                           = v1.FrameworkServiceRestoreRequest
	FrameworkServiceRestoreResponse                          = v1.FrameworkServiceRestoreResponse
	FrameworkServiceServer                                   = v1.FrameworkServiceServer
	FrameworkService_StreamClient                            = v1.FrameworkService_StreamClient
	FrameworkService_StreamServer                            = v1.FrameworkService_StreamServer
	GetConfigRequest                                         = v1.GetConfigRequest
	GetConfigResponse                                        = v1.GetConfigResponse
	GetConfigSectionRequest                                  = v1.GetConfigSectionRequest
	GetConfigSectionResponse                                 = v1.GetConfigSectionResponse
	GetConfigStringRequest                                   = v1.GetConfigStringRequest
	GetConfigStringResponse                                  = v1.GetConfigStringResponse
	GetCopilotFileChangesRequest                             = v1.GetCopilotFileChangesRequest
	GetCopilotFileChangesResponse                            = v1.GetCopilotFileChangesResponse
	GetCopilotMessagesRequest                                = v1.GetCopilotMessagesRequest
	GetCopilotMessagesResponse                               = v1.GetCopilotMessagesResponse
	GetCopilotUsageMetricsRequest                            = v1.GetCopilotUsageMetricsRequest
	GetCopilotUsageMetricsResponse                           = v1.GetCopilotUsageMetricsResponse
	GetDeploymentContextResponse                             = v1.GetDeploymentContextResponse
	GetDeploymentResponse                                    = v1.GetDeploymentResponse
	GetEnvRequest                                            = v1.GetEnvRequest
	GetEnvironmentRequest                                    = v1.GetEnvironmentRequest
	GetProjectConfigSectionRequest                           = v1.GetProjectConfigSectionRequest
	GetProjectConfigSectionResponse                          = v1.GetProjectConfigSectionResponse
	GetProjectConfigValueRequest                             = v1.GetProjectConfigValueRequest
	GetProjectConfigValueResponse                            = v1.GetProjectConfigValueResponse
	GetProjectResponse                                       = v1.GetProjectResponse
	GetResolvedServicesResponse                              = v1.GetResolvedServicesResponse
	GetResourceRequest                                       = v1.GetResourceRequest
	GetResourceResponse                                      = v1.GetResourceResponse
	GetResourceTypeRequest                                   = v1.GetResourceTypeRequest
	GetResourceTypeResponse                                  = v1.GetResourceTypeResponse
	GetServiceConfigSectionRequest                           = v1.GetServiceConfigSectionRequest
	GetServiceConfigSectionResponse                          = v1.GetServiceConfigSectionResponse
	GetServiceConfigValueRequest                             = v1.GetServiceConfigValueRequest
	GetServiceConfigValueResponse                            = v1.GetServiceConfigValueResponse
	GetServiceTargetResourceRequest                          = v1.GetServiceTargetResourceRequest
	GetServiceTargetResourceResponse                         = v1.GetServiceTargetResourceResponse
	GetTargetResourceRequest                                 = v1.GetTargetResourceRequest
	GetTargetResourceResponse                                = v1.GetTargetResourceResponse
	GetUserConfigRequest                                     = v1.GetUserConfigRequest
	GetUserConfigResponse                                    = v1.GetUserConfigResponse
	GetUserConfigSectionRequest                              = v1.GetUserConfigSectionRequest
	GetUserConfigSectionResponse                             = v1.GetUserConfigSectionResponse
	GetUserConfigStringRequest                               = v1.GetUserConfigStringRequest
	GetUserConfigStringResponse                              = v1.GetUserConfigStringResponse
	InfraOptions                                             = v1.InfraOptions
	InitializeCopilotRequest                                 = v1.InitializeCopilotRequest
	InitializeCopilotResponse                                = v1.InitializeCopilotResponse
	InvokeProjectHandler                                     = v1.InvokeProjectHandler
	InvokeServiceHandler                                     = v1.InvokeServiceHandler
	KeyValue                                                 = v1.KeyValue
	KeyValueListResponse                                     = v1.KeyValueListResponse
	KeyValueResponse                                         = v1.KeyValueResponse
	ListCopilotSessionsRequest                               = v1.ListCopilotSessionsRequest
	ListCopilotSessionsResponse                              = v1.ListCopilotSessionsResponse
	ListLocationsWithQuotaRequest                            = v1.ListLocationsWithQuotaRequest
	ListLocationsWithQuotaResponse                           = v1.ListLocationsWithQuotaResponse
	ListModelLocationsWithQuotaRequest                       = v1.ListModelLocationsWithQuotaRequest
	ListModelLocationsWithQuotaResponse                      = v1.ListModelLocationsWithQuotaResponse
	ListModelsRequest                                        = v1.ListModelsRequest
	ListModelsResponse                                       = v1.ListModelsResponse
	ListResourceTypesResponse                                = v1.ListResourceTypesResponse
	ListResourcesResponse                                    = v1.ListResourcesResponse
	ListSubscriptionsRequest                                 = v1.ListSubscriptionsRequest
	ListSubscriptionsResponse                                = v1.ListSubscriptionsResponse
	ListUsagesRequest                                        = v1.ListUsagesRequest
	ListUsagesResponse                                       = v1.ListUsagesResponse
	LocalErrorDetail                                         = v1.LocalErrorDetail
	Location                                                 = v1.Location
	LocationKind                                             = v1.LocationKind
	LookupTenantRequest                                      = v1.LookupTenantRequest
	LookupTenantResponse                                     = v1.LookupTenantResponse
	ModelLocationQuota                                       = v1.ModelLocationQuota
	MultiSelectChoice                                        = v1.MultiSelectChoice
	MultiSelectOptions                                       = v1.MultiSelectOptions
	MultiSelectRequest                                       = v1.MultiSelectRequest
	MultiSelectResponse                                      = v1.MultiSelectResponse
	ParseGitHubUrlRequest                                    = v1.ParseGitHubUrlRequest
	ParseGitHubUrlResponse                                   = v1.ParseGitHubUrlResponse
	PrepareValidationContextChunk                            = v1.PrepareValidationContextChunk
	PrepareValidationContextResponse                         = v1.PrepareValidationContextResponse
	ProjectConfig                                            = v1.ProjectConfig
	ProjectHandlerStatus                                     = v1.ProjectHandlerStatus
	ProjectMetadata                                          = v1.ProjectMetadata
	ProjectServiceClient                                     = v1.ProjectServiceClient
	ProjectServiceServer                                     = v1.ProjectServiceServer
	PromptAiDeploymentRequest                                = v1.PromptAiDeploymentRequest
	PromptAiDeploymentResponse                               = v1.PromptAiDeploymentResponse
	PromptAiLocationWithQuotaRequest                         = v1.PromptAiLocationWithQuotaRequest
	PromptAiLocationWithQuotaResponse                        = v1.PromptAiLocationWithQuotaResponse
	PromptAiModelLocationWithQuotaRequest                    = v1.PromptAiModelLocationWithQuotaRequest
	PromptAiModelLocationWithQuotaResponse                   = v1.PromptAiModelLocationWithQuotaResponse
	PromptAiModelRequest                                     = v1.PromptAiModelRequest
	PromptAiModelResponse                                    = v1.PromptAiModelResponse
	PromptLocationRequest                                    = v1.PromptLocationRequest
	PromptLocationResponse                                   = v1.PromptLocationResponse
	PromptOptions                                            = v1.PromptOptions
	PromptRequest                                            = v1.PromptRequest
	PromptResourceGroupOptions                               = v1.PromptResourceGroupOptions
	PromptResourceGroupRequest                               = v1.PromptResourceGroupRequest
	PromptResourceGroupResourceRequest                       = v1.PromptResourceGroupResourceRequest
	PromptResourceGroupResourceResponse                      = v1.PromptResourceGroupResourceResponse
	PromptResourceGroupResponse                              = v1.PromptResourceGroupResponse
	PromptResourceOptions                                    = v1.PromptResourceOptions
	PromptResourceSelectOptions                              = v1.PromptResourceSelectOptions
	PromptResponse                                           = v1.PromptResponse
	PromptServiceClient                                      = v1.PromptServiceClient
	PromptServiceServer                                      = v1.PromptServiceServer
	PromptSubscriptionRequest                                = v1.PromptSubscriptionRequest
	PromptSubscriptionResourceRequest                        = v1.PromptSubscriptionResourceRequest
	PromptSubscriptionResourceResponse                       = v1.PromptSubscriptionResourceResponse
	PromptSubscriptionResponse                               = v1.PromptSubscriptionResponse
	ProvisioningDeployRequest                                = v1.ProvisioningDeployRequest
	ProvisioningDeployResponse                               = v1.ProvisioningDeployResponse
	ProvisioningDeployResult                                 = v1.ProvisioningDeployResult
	ProvisioningDeployment                                   = v1.ProvisioningDeployment
	ProvisioningDeploymentPreview                            = v1.ProvisioningDeploymentPreview
	ProvisioningDeploymentPreviewChange                      = v1.ProvisioningDeploymentPreviewChange
	ProvisioningDestroyOptions                               = v1.ProvisioningDestroyOptions
	ProvisioningDestroyRequest                               = v1.ProvisioningDestroyRequest
	ProvisioningDestroyResponse                              = v1.ProvisioningDestroyResponse
	ProvisioningDestroyResult                                = v1.ProvisioningDestroyResult
	ProvisioningEnsureEnvRequest                             = v1.ProvisioningEnsureEnvRequest
	ProvisioningEnsureEnvResponse                            = v1.ProvisioningEnsureEnvResponse
	ProvisioningInitializeRequest                            = v1.ProvisioningInitializeRequest
	ProvisioningInitializeResponse                           = v1.ProvisioningInitializeResponse
	ProvisioningInputParameter                               = v1.ProvisioningInputParameter
	ProvisioningMessage                                      = v1.ProvisioningMessage
	ProvisioningMessage_DeployRequest                        = v1.ProvisioningMessage_DeployRequest
	ProvisioningMessage_DeployResponse                       = v1.ProvisioningMessage_DeployResponse
	ProvisioningMessage_DestroyRequest                       = v1.ProvisioningMessage_DestroyRequest
	ProvisioningMessage_DestroyResponse                      = v1.ProvisioningMessage_DestroyResponse
	ProvisioningMessage_EnsureEnvRequest                     = v1.ProvisioningMessage_EnsureEnvRequest
	ProvisioningMessage_EnsureEnvResponse                    = v1.ProvisioningMessage_EnsureEnvResponse
	ProvisioningMessage_InitializeRequest                    = v1.ProvisioningMessage_InitializeRequest
	ProvisioningMessage_InitializeResponse                   = v1.ProvisioningMessage_InitializeResponse
	ProvisioningMessage_ParametersRequest                    = v1.ProvisioningMessage_ParametersRequest
	ProvisioningMessage_ParametersResponse                   = v1.ProvisioningMessage_ParametersResponse
	ProvisioningMessage_PlannedOutputsRequest                = v1.ProvisioningMessage_PlannedOutputsRequest
	ProvisioningMessage_PlannedOutputsResponse               = v1.ProvisioningMessage_PlannedOutputsResponse
	ProvisioningMessage_PreviewRequest                       = v1.ProvisioningMessage_PreviewRequest
	ProvisioningMessage_PreviewResponse                      = v1.ProvisioningMessage_PreviewResponse
	ProvisioningMessage_ProgressMessage                      = v1.ProvisioningMessage_ProgressMessage
	ProvisioningMessage_RegisterProvisioningProviderRequest  = v1.ProvisioningMessage_RegisterProvisioningProviderRequest
	ProvisioningMessage_RegisterProvisioningProviderResponse = v1.ProvisioningMessage_RegisterProvisioningProviderResponse
	ProvisioningMessage_StateRequest                         = v1.ProvisioningMessage_StateRequest
	ProvisioningMessage_StateResponse                        = v1.ProvisioningMessage_StateResponse
	ProvisioningOptions                                      = v1.ProvisioningOptions
	ProvisioningOutputParameter                              = v1.ProvisioningOutputParameter
	ProvisioningParameter                                    = v1.ProvisioningParameter
	ProvisioningParametersRequest                            = v1.ProvisioningParametersRequest
	ProvisioningParametersResponse                           = v1.ProvisioningParametersResponse
	ProvisioningPlannedOutput                                = v1.ProvisioningPlannedOutput
	ProvisioningPlannedOutputsRequest                        = v1.ProvisioningPlannedOutputsRequest
	ProvisioningPlannedOutputsResponse                       = v1.ProvisioningPlannedOutputsResponse
	ProvisioningPreviewRequest                               = v1.ProvisioningPreviewRequest
	ProvisioningPreviewResponse                              = v1.ProvisioningPreviewResponse
	ProvisioningPreviewResult                                = v1.ProvisioningPreviewResult
	ProvisioningProgressMessage                              = v1.ProvisioningProgressMessage
	ProvisioningResource                                     = v1.ProvisioningResource
	ProvisioningServiceClient                                = v1.ProvisioningServiceClient
	ProvisioningServiceServer                                = v1.ProvisioningServiceServer
	ProvisioningService_StreamClient                         = v1.ProvisioningService_StreamClient
	ProvisioningService_StreamServer                         = v1.ProvisioningService_StreamServer
	ProvisioningSkippedReason                                = v1.ProvisioningSkippedReason
	ProvisioningState                                        = v1.ProvisioningState
	ProvisioningStateOptions                                 = v1.ProvisioningStateOptions
	ProvisioningStateRequest                                 = v1.ProvisioningStateRequest
	ProvisioningStateResponse                                = v1.ProvisioningStateResponse
	ProvisioningStateResult                                  = v1.ProvisioningStateResult
	PublishOptions                                           = v1.PublishOptions
	QuotaCheckOptions                                        = v1.QuotaCheckOptions
	QuotaRequirement                                         = v1.QuotaRequirement
	ReadyRequest                                             = v1.ReadyRequest
	ReadyResponse                                            = v1.ReadyResponse
	RegisterFrameworkServiceRequest                          = v1.RegisterFrameworkServiceRequest
	RegisterFrameworkServiceResponse                         = v1.RegisterFrameworkServiceResponse
	RegisterProvisioningProviderRequest                      = v1.RegisterProvisioningProviderRequest
	RegisterProvisioningProviderResponse                     = v1.RegisterProvisioningProviderResponse
	RegisterServiceTargetRequest                             = v1.RegisterServiceTargetRequest
	RegisterServiceTargetResponse                            = v1.RegisterServiceTargetResponse
	RegisterValidationCheckRequest                           = v1.RegisterValidationCheckRequest
	RegisterValidationCheckResponse                          = v1.RegisterValidationCheckResponse
	ReportErrorRequest                                       = v1.ReportErrorRequest
	ReportErrorResponse                                      = v1.ReportErrorResponse
	ReportUsageRequest                                       = v1.ReportUsageRequest
	ReportUsageResponse                                      = v1.ReportUsageResponse
	RequiredVersions                                         = v1.RequiredVersions
	ResolveModelDeploymentsRequest                           = v1.ResolveModelDeploymentsRequest
	ResolveModelDeploymentsResponse                          = v1.ResolveModelDeploymentsResponse
	Resource                                                 = v1.Resource
	ResourceExtended                                         = v1.ResourceExtended
	ResourceGroup                                            = v1.ResourceGroup
	RunWorkflowRequest                                       = v1.RunWorkflowRequest
	SelectChoice                                             = v1.SelectChoice
	SelectEnvironmentRequest                                 = v1.SelectEnvironmentRequest
	SelectOptions                                            = v1.SelectOptions
	SelectRequest                                            = v1.SelectRequest
	SelectResponse                                           = v1.SelectResponse
	SendCopilotMessageRequest                                = v1.SendCopilotMessageRequest
	SendCopilotMessageResponse                               = v1.SendCopilotMessageResponse
	ServiceBuildResult                                       = v1.ServiceBuildResult
	ServiceConfig                                            = v1.ServiceConfig
	ServiceContext                                           = v1.ServiceContext
	ServiceDeployResult                                      = v1.ServiceDeployResult
	ServiceErrorDetail                                       = v1.ServiceErrorDetail
	ServiceHandlerStatus                                     = v1.ServiceHandlerStatus
	ServicePackageResult                                     = v1.ServicePackageResult
	ServicePublishResult                                     = v1.ServicePublishResult
	ServiceRestoreResult                                     = v1.ServiceRestoreResult
	ServiceTargetDeployRequest                               = v1.ServiceTargetDeployRequest
	ServiceTargetDeployResponse                              = v1.ServiceTargetDeployResponse
	ServiceTargetEndpointsRequest                            = v1.ServiceTargetEndpointsRequest
	ServiceTargetEndpointsResponse                           = v1.ServiceTargetEndpointsResponse
	ServiceTargetInitializeRequest                           = v1.ServiceTargetInitializeRequest
	ServiceTargetInitializeResponse                          = v1.ServiceTargetInitializeResponse
	ServiceTargetInputParameter                              = v1.ServiceTargetInputParameter
	ServiceTargetMessage                                     = v1.ServiceTargetMessage
	ServiceTargetMessage_DeployRequest                       = v1.ServiceTargetMessage_DeployRequest
	ServiceTargetMessage_DeployResponse                      = v1.ServiceTargetMessage_DeployResponse
	ServiceTargetMessage_EndpointsRequest                    = v1.ServiceTargetMessage_EndpointsRequest
	ServiceTargetMessage_EndpointsResponse                   = v1.ServiceTargetMessage_EndpointsResponse
	ServiceTargetMessage_GetTargetResourceRequest            = v1.ServiceTargetMessage_GetTargetResourceRequest
	ServiceTargetMessage_GetTargetResourceResponse           = v1.ServiceTargetMessage_GetTargetResourceResponse
	ServiceTargetMessage_InitializeRequest                   = v1.ServiceTargetMessage_InitializeRequest
	ServiceTargetMessage_InitializeResponse                  = v1.ServiceTargetMessage_InitializeResponse
	ServiceTargetMessage_PackageRequest                      = v1.ServiceTargetMessage_PackageRequest
	ServiceTargetMessage_PackageResponse                     = v1.ServiceTargetMessage_PackageResponse
	ServiceTargetMessage_ProgressMessage                     = v1.ServiceTargetMessage_ProgressMessage
	ServiceTargetMessage_PublishRequest                      = v1.ServiceTargetMessage_PublishRequest
	ServiceTargetMessage_PublishResponse                     = v1.ServiceTargetMessage_PublishResponse
	ServiceTargetMessage_RegisterServiceTargetRequest        = v1.ServiceTargetMessage_RegisterServiceTargetRequest
	ServiceTargetMessage_RegisterServiceTargetResponse       = v1.ServiceTargetMessage_RegisterServiceTargetResponse
	ServiceTargetOptions                                     = v1.ServiceTargetOptions
	ServiceTargetOutputParameter                             = v1.ServiceTargetOutputParameter
	ServiceTargetPackageRequest                              = v1.ServiceTargetPackageRequest
	ServiceTargetPackageResponse                             = v1.ServiceTargetPackageResponse
	ServiceTargetProgressMessage                             = v1.ServiceTargetProgressMessage
	ServiceTargetPublishRequest                              = v1.ServiceTargetPublishRequest
	ServiceTargetPublishResponse                             = v1.ServiceTargetPublishResponse
	ServiceTargetResource                                    = v1.ServiceTargetResource
	ServiceTargetServiceClient                               = v1.ServiceTargetServiceClient
	ServiceTargetServiceServer                               = v1.ServiceTargetServiceServer
	ServiceTargetService_StreamClient                        = v1.ServiceTargetService_StreamClient
	ServiceTargetService_StreamServer                        = v1.ServiceTargetService_StreamServer
	SetConfigRequest                                         = v1.SetConfigRequest
	SetEnvRequest                                            = v1.SetEnvRequest
	SetProjectConfigSectionRequest                           = v1.SetProjectConfigSectionRequest
	SetProjectConfigValueRequest                             = v1.SetProjectConfigValueRequest
	SetServiceConfigSectionRequest                           = v1.SetServiceConfigSectionRequest
	SetServiceConfigValueRequest                             = v1.SetServiceConfigValueRequest
	SetUserConfigRequest                                     = v1.SetUserConfigRequest
	StopCopilotSessionRequest                                = v1.StopCopilotSessionRequest
	SubscribeProjectEvent                                    = v1.SubscribeProjectEvent
	SubscribeServiceEvent                                    = v1.SubscribeServiceEvent
	Subscription                                             = v1.Subscription
	TargetResource                                           = v1.TargetResource
	TelemetryServiceClient                                   = v1.TelemetryServiceClient
	TelemetryServiceServer                                   = v1.TelemetryServiceServer
	UnimplementedAccountServiceServer                        = v1.UnimplementedAccountServiceServer
	UnimplementedAiModelServiceServer                        = v1.UnimplementedAiModelServiceServer
	UnimplementedComposeServiceServer                        = v1.UnimplementedComposeServiceServer
	UnimplementedContainerServiceServer                      = v1.UnimplementedContainerServiceServer
	UnimplementedCopilotServiceServer                        = v1.UnimplementedCopilotServiceServer
	UnimplementedDeploymentServiceServer                     = v1.UnimplementedDeploymentServiceServer
	UnimplementedEnvironmentServiceServer                    = v1.UnimplementedEnvironmentServiceServer
	UnimplementedEventServiceServer                          = v1.UnimplementedEventServiceServer
	UnimplementedExtensionServiceServer                      = v1.UnimplementedExtensionServiceServer
	UnimplementedFrameworkServiceServer                      = v1.UnimplementedFrameworkServiceServer
	UnimplementedProjectServiceServer                        = v1.UnimplementedProjectServiceServer
	UnimplementedPromptServiceServer                         = v1.UnimplementedPromptServiceServer
	UnimplementedProvisioningServiceServer                   = v1.UnimplementedProvisioningServiceServer
	UnimplementedServiceTargetServiceServer                  = v1.UnimplementedServiceTargetServiceServer
	UnimplementedTelemetryServiceServer                      = v1.UnimplementedTelemetryServiceServer
	UnimplementedUserConfigServiceServer                     = v1.UnimplementedUserConfigServiceServer
	UnimplementedValidationServiceServer                     = v1.UnimplementedValidationServiceServer
	UnimplementedWorkflowServiceServer                       = v1.UnimplementedWorkflowServiceServer
	UnsafeAccountServiceServer                               = v1.UnsafeAccountServiceServer
	UnsafeAiModelServiceServer                               = v1.UnsafeAiModelServiceServer
	UnsafeComposeServiceServer                               = v1.UnsafeComposeServiceServer
	UnsafeContainerServiceServer                             = v1.UnsafeContainerServiceServer
	UnsafeCopilotServiceServer                               = v1.UnsafeCopilotServiceServer
	UnsafeDeploymentServiceServer                            = v1.UnsafeDeploymentServiceServer
	UnsafeEnvironmentServiceServer                           = v1.UnsafeEnvironmentServiceServer
	UnsafeEventServiceServer                                 = v1.UnsafeEventServiceServer
	UnsafeExtensionServiceServer                             = v1.UnsafeExtensionServiceServer
	UnsafeFrameworkServiceServer                             = v1.UnsafeFrameworkServiceServer
	UnsafeProjectServiceServer                               = v1.UnsafeProjectServiceServer
	UnsafePromptServiceServer                                = v1.UnsafePromptServiceServer
	UnsafeProvisioningServiceServer                          = v1.UnsafeProvisioningServiceServer
	UnsafeServiceTargetServiceServer                         = v1.UnsafeServiceTargetServiceServer
	UnsafeTelemetryServiceServer                             = v1.UnsafeTelemetryServiceServer
	UnsafeUserConfigServiceServer                            = v1.UnsafeUserConfigServiceServer
	UnsafeValidationServiceServer                            = v1.UnsafeValidationServiceServer
	UnsafeWorkflowServiceServer                              = v1.UnsafeWorkflowServiceServer
	UnsetConfigRequest                                       = v1.UnsetConfigRequest
	UnsetProjectConfigRequest                                = v1.UnsetProjectConfigRequest
	UnsetServiceConfigRequest                                = v1.UnsetServiceConfigRequest
	UnsetUserConfigRequest                                   = v1.UnsetUserConfigRequest
	UserConfigServiceClient                                  = v1.UserConfigServiceClient
	UserConfigServiceServer                                  = v1.UserConfigServiceServer
	ValidationCheckRequest                                   = v1.ValidationCheckRequest
	ValidationCheckResponse                                  = v1.ValidationCheckResponse
	ValidationCheckResult                                    = v1.ValidationCheckResult
	ValidationCheckSeverity                                  = v1.ValidationCheckSeverity
	ValidationMessage                                        = v1.ValidationMessage
	ValidationMessage_PrepareValidationContextChunk          = v1.ValidationMessage_PrepareValidationContextChunk
	ValidationMessage_PrepareValidationContextResponse       = v1.ValidationMessage_PrepareValidationContextResponse
	ValidationMessage_RegisterValidationCheckRequest         = v1.ValidationMessage_RegisterValidationCheckRequest
	ValidationMessage_RegisterValidationCheckResponse        = v1.ValidationMessage_RegisterValidationCheckResponse
	ValidationMessage_ValidationCheckRequest                 = v1.ValidationMessage_ValidationCheckRequest
	ValidationMessage_ValidationCheckResponse                = v1.ValidationMessage_ValidationCheckResponse
	ValidationReportLink                                     = v1.ValidationReportLink
	ValidationServiceClient                                  = v1.ValidationServiceClient
	ValidationServiceServer                                  = v1.ValidationServiceServer
	ValidationService_StreamClient                           = v1.ValidationService_StreamClient
	ValidationService_StreamServer                           = v1.ValidationService_StreamServer
	Workflow                                                 = v1.Workflow
	WorkflowCommand                                          = v1.WorkflowCommand
	WorkflowServiceClient                                    = v1.WorkflowServiceClient
	WorkflowServiceServer                                    = v1.WorkflowServiceServer
	WorkflowStep                                             = v1.WorkflowStep
)

var (
	AccountService_ServiceDesc       = v1.AccountService_ServiceDesc
	AiModelService_ServiceDesc       = v1.AiModelService_ServiceDesc
	ArtifactKind_name                = v1.ArtifactKind_name
	ArtifactKind_value               = v1.ArtifactKind_value
	ComposeService_ServiceDesc       = v1.ComposeService_ServiceDesc
	ContainerService_ServiceDesc     = v1.ContainerService_ServiceDesc
	CopilotFileChangeType_name       = v1.CopilotFileChangeType_name
	CopilotFileChangeType_value      = v1.CopilotFileChangeType_value
	CopilotService_ServiceDesc       = v1.CopilotService_ServiceDesc
	DeploymentService_ServiceDesc    = v1.DeploymentService_ServiceDesc
	EnvironmentService_ServiceDesc   = v1.EnvironmentService_ServiceDesc
	ErrorOrigin_name                 = v1.ErrorOrigin_name
	ErrorOrigin_value                = v1.ErrorOrigin_value
	EventService_ServiceDesc         = v1.EventService_ServiceDesc
	ExtensionService_ServiceDesc     = v1.ExtensionService_ServiceDesc
	File_account_proto               = v1.File_azd_extensions_v1_account_proto
	File_ai_model_proto              = v1.File_azd_extensions_v1_ai_model_proto
	File_compose_proto               = v1.File_azd_extensions_v1_compose_proto
	File_container_proto             = v1.File_azd_extensions_v1_container_proto
	File_copilot_proto               = v1.File_azd_extensions_v1_copilot_proto
	File_deployment_proto            = v1.File_azd_extensions_v1_deployment_proto
	File_environment_proto           = v1.File_azd_extensions_v1_environment_proto
	File_errors_proto                = v1.File_azd_extensions_v1_errors_proto
	File_event_proto                 = v1.File_azd_extensions_v1_event_proto
	File_extension_proto             = v1.File_azd_extensions_v1_extension_proto
	File_framework_service_proto     = v1.File_azd_extensions_v1_framework_service_proto
	File_models_proto                = v1.File_azd_extensions_v1_models_proto
	File_project_proto               = v1.File_azd_extensions_v1_project_proto
	File_prompt_proto                = v1.File_azd_extensions_v1_prompt_proto
	File_provisioning_proto          = v1.File_azd_extensions_v1_provisioning_proto
	File_service_target_proto        = v1.File_azd_extensions_v1_service_target_proto
	File_telemetry_proto             = v1.File_azd_extensions_v1_telemetry_proto
	File_user_config_proto           = v1.File_azd_extensions_v1_user_config_proto
	File_validation_proto            = v1.File_azd_extensions_v1_validation_proto
	File_workflow_proto              = v1.File_azd_extensions_v1_workflow_proto
	FrameworkService_ServiceDesc     = v1.FrameworkService_ServiceDesc
	LocationKind_name                = v1.LocationKind_name
	LocationKind_value               = v1.LocationKind_value
	ProjectService_ServiceDesc       = v1.ProjectService_ServiceDesc
	PromptService_ServiceDesc        = v1.PromptService_ServiceDesc
	ProvisioningService_ServiceDesc  = v1.ProvisioningService_ServiceDesc
	ProvisioningSkippedReason_name   = v1.ProvisioningSkippedReason_name
	ProvisioningSkippedReason_value  = v1.ProvisioningSkippedReason_value
	ServiceTargetService_ServiceDesc = v1.ServiceTargetService_ServiceDesc
	TelemetryService_ServiceDesc     = v1.TelemetryService_ServiceDesc
	UserConfigService_ServiceDesc    = v1.UserConfigService_ServiceDesc
	ValidationCheckSeverity_name     = v1.ValidationCheckSeverity_name
	ValidationCheckSeverity_value    = v1.ValidationCheckSeverity_value
	ValidationService_ServiceDesc    = v1.ValidationService_ServiceDesc
	WorkflowService_ServiceDesc      = v1.WorkflowService_ServiceDesc
)

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return v1.NewAccountServiceClient(cc)
}

func NewAiModelServiceClient(cc grpc.ClientConnInterface) AiModelServiceClient {
	return v1.NewAiModelServiceClient(cc)
}

func NewComposeServiceClient(cc grpc.ClientConnInterface) ComposeServiceClient {
	return v1.NewComposeServiceClient(cc)
}

func NewContainerServiceClient(cc grpc.ClientConnInterface) ContainerServiceClient {
	return v1.NewContainerServiceClient(cc)
}

func NewCopilotServiceClient(cc grpc.ClientConnInterface) CopilotServiceClient {
	return v1.NewCopilotServiceClient(cc)
}

func NewDeploymentServiceClient(cc grpc.ClientConnInterface) DeploymentServiceClient {
	return v1.NewDeploymentServiceClient(cc)
}

func NewEnvironmentServiceClient(cc grpc.ClientConnInterface) EnvironmentServiceClient {
	return v1.NewEnvironmentServiceClient(cc)
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return v1.NewEventServiceClient(cc)
}

func NewExtensionServiceClient(cc grpc.ClientConnInterface) ExtensionServiceClient {
	return v1.NewExtensionServiceClient(cc)
}

func NewFrameworkServiceClient(cc grpc.ClientConnInterface) FrameworkServiceClient {
	return v1.NewFrameworkServiceClient(cc)
}

func NewProjectServiceClient(cc grpc.ClientConnInterface) ProjectServiceClient {
	return v1.NewProjectServiceClient(cc)
}

func NewPromptServiceClient(cc grpc.ClientConnInterface) PromptServiceClient {
	return v1.NewPromptServiceClient(cc)
}

func NewProvisioningServiceClient(cc grpc.ClientConnInterface) ProvisioningServiceClient {
	return v1.NewProvisioningServiceClient(cc)
}

func NewServiceTargetServiceClient(cc grpc.ClientConnInterface) ServiceTargetServiceClient {
	return v1.NewServiceTargetServiceClient(cc)
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return v1.NewTelemetryServiceClient(cc)
}

func NewUserConfigServiceClient(cc grpc.ClientConnInterface) UserConfigServiceClient {
	return v1.NewUserConfigServiceClient(cc)
}

func NewValidationServiceClient(cc grpc.ClientConnInterface) ValidationServiceClient {
	return v1.NewValidationServiceClient(cc)
}

func NewWorkflowServiceClient(cc grpc.ClientConnInterface) WorkflowServiceClient {
	return v1.NewWorkflowServiceClient(cc)
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	v1.RegisterAccountServiceServer(s, srv)
}

func RegisterAiModelServiceServer(s grpc.ServiceRegistrar, srv AiModelServiceServer) {
	v1.RegisterAiModelServiceServer(s, srv)
}

func RegisterComposeServiceServer(s grpc.ServiceRegistrar, srv ComposeServiceServer) {
	v1.RegisterComposeServiceServer(s, srv)
}

func RegisterContainerServiceServer(s grpc.ServiceRegistrar, srv ContainerServiceServer) {
	v1.RegisterContainerServiceServer(s, srv)
}

func RegisterCopilotServiceServer(s grpc.ServiceRegistrar, srv CopilotServiceServer) {
	v1.RegisterCopilotServiceServer(s, srv)
}

func RegisterDeploymentServiceServer(s grpc.ServiceRegistrar, srv DeploymentServiceServer) {
	v1.RegisterDeploymentServiceServer(s, srv)
}

func RegisterEnvironmentServiceServer(s grpc.ServiceRegistrar, srv EnvironmentServiceServer) {
	v1.RegisterEnvironmentServiceServer(s, srv)
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	v1.RegisterEventServiceServer(s, srv)
}

func RegisterExtensionServiceServer(s grpc.ServiceRegistrar, srv ExtensionServiceServer) {
	v1.RegisterExtensionServiceServer(s, srv)
}

func RegisterFrameworkServiceServer(s grpc.ServiceRegistrar, srv FrameworkServiceServer) {
	v1.RegisterFrameworkServiceServer(s, srv)
}

func RegisterProjectServiceServer(s grpc.ServiceRegistrar, srv ProjectServiceServer) {
	v1.RegisterProjectServiceServer(s, srv)
}

func RegisterPromptServiceServer(s grpc.ServiceRegistrar, srv PromptServiceServer) {
	v1.RegisterPromptServiceServer(s, srv)
}

func RegisterProvisioningServiceServer(s grpc.ServiceRegistrar, srv ProvisioningServiceServer) {
	v1.RegisterProvisioningServiceServer(s, srv)
}

func RegisterServiceTargetServiceServer(s grpc.ServiceRegistrar, srv ServiceTargetServiceServer) {
	v1.RegisterServiceTargetServiceServer(s, srv)
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	v1.RegisterTelemetryServiceServer(s, srv)
}

func RegisterUserConfigServiceServer(s grpc.ServiceRegistrar, srv UserConfigServiceServer) {
	v1.RegisterUserConfigServiceServer(s, srv)
}

func RegisterValidationServiceServer(s grpc.ServiceRegistrar, srv ValidationServiceServer) {
	v1.RegisterValidationServiceServer(s, srv)
}

func RegisterWorkflowServiceServer(s grpc.ServiceRegistrar, srv WorkflowServiceServer) {
	v1.RegisterWorkflowServiceServer(s, srv)
}
