// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: deployment.proto

package azdext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDeploymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    *Deployment            `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentResponse) Reset() {
	*x = GetDeploymentResponse{}
	mi := &file_deployment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentResponse) ProtoMessage() {}

func (x *GetDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentResponse.ProtoReflect.Descriptor instead.
func (*GetDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_deployment_proto_rawDescGZIP(), []int{0}
}

func (x *GetDeploymentResponse) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type GetDeploymentContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AzureContext  *AzureContext          `protobuf:"bytes,1,opt,name=AzureContext,proto3" json:"AzureContext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentContextResponse) Reset() {
	*x = GetDeploymentContextResponse{}
	mi := &file_deployment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentContextResponse) ProtoMessage() {}

func (x *GetDeploymentContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentContextResponse.ProtoReflect.Descriptor instead.
func (*GetDeploymentContextResponse) Descriptor() ([]byte, []int) {
	return file_deployment_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeploymentContextResponse) GetAzureContext() *AzureContext {
	if x != nil {
		return x.AzureContext
	}
	return nil
}

type Deployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,3,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Outputs       map[string]string      `protobuf:"bytes,7,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Resources     []string               `protobuf:"bytes,8,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_deployment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_deployment_proto_rawDescGZIP(), []int{2}
}

func (x *Deployment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Deployment) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Deployment) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *Deployment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deployment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Deployment) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Deployment) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Deployment) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

var File_deployment_proto protoreflect.FileDescriptor

const file_deployment_proto_rawDesc = "" +
	"\n" +
	"\x10deployment.proto\x12\x06azdext\x1a\fmodels.proto\"K\n" +
	"\x15GetDeploymentResponse\x122\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\x12.azdext.DeploymentR\n" +
	"deployment\"X\n" +
	"\x1cGetDeploymentContextResponse\x128\n" +
	"\fAzureContext\x18\x01 \x01(\v2\x14.azdext.AzureContextR\fAzureContext\"\x84\x03\n" +
	"\n" +
	"Deployment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\"\n" +
	"\fdeploymentId\x18\x03 \x01(\tR\fdeploymentId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x120\n" +
	"\x04tags\x18\x06 \x03(\v2\x1c.azdext.Deployment.TagsEntryR\x04tags\x129\n" +
	"\aoutputs\x18\a \x03(\v2\x1f.azdext.Deployment.OutputsEntryR\aoutputs\x12\x1c\n" +
	"\tresources\x18\b \x03(\tR\tresources\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xad\x01\n" +
	"\x11DeploymentService\x12D\n" +
	"\rGetDeployment\x12\x14.azdext.EmptyRequest\x1a\x1d.azdext.GetDeploymentResponse\x12R\n" +
	"\x14GetDeploymentContext\x12\x14.azdext.EmptyRequest\x1a$.azdext.GetDeploymentContextResponseB6Z4github.com/azure/azure-dev/cli/azd/pkg/azdext;azdextb\x06proto3"

var (
	file_deployment_proto_rawDescOnce sync.Once
	file_deployment_proto_rawDescData []byte
)

func file_deployment_proto_rawDescGZIP() []byte {
	file_deployment_proto_rawDescOnce.Do(func() {
		file_deployment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deployment_proto_rawDesc), len(file_deployment_proto_rawDesc)))
	})
	return file_deployment_proto_rawDescData
}

var file_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_deployment_proto_goTypes = []any{
	(*GetDeploymentResponse)(nil),        // 0: azdext.GetDeploymentResponse
	(*GetDeploymentContextResponse)(nil), // 1: azdext.GetDeploymentContextResponse
	(*Deployment)(nil),                   // 2: azdext.Deployment
	nil,                                  // 3: azdext.Deployment.TagsEntry
	nil,                                  // 4: azdext.Deployment.OutputsEntry
	(*AzureContext)(nil),                 // 5: azdext.AzureContext
	(*EmptyRequest)(nil),                 // 6: azdext.EmptyRequest
}
var file_deployment_proto_depIdxs = []int32{
	2, // 0: azdext.GetDeploymentResponse.deployment:type_name -> azdext.Deployment
	5, // 1: azdext.GetDeploymentContextResponse.AzureContext:type_name -> azdext.AzureContext
	3, // 2: azdext.Deployment.tags:type_name -> azdext.Deployment.TagsEntry
	4, // 3: azdext.Deployment.outputs:type_name -> azdext.Deployment.OutputsEntry
	6, // 4: azdext.DeploymentService.GetDeployment:input_type -> azdext.EmptyRequest
	6, // 5: azdext.DeploymentService.GetDeploymentContext:input_type -> azdext.EmptyRequest
	0, // 6: azdext.DeploymentService.GetDeployment:output_type -> azdext.GetDeploymentResponse
	1, // 7: azdext.DeploymentService.GetDeploymentContext:output_type -> azdext.GetDeploymentContextResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_deployment_proto_init() }
func file_deployment_proto_init() {
	if File_deployment_proto != nil {
		return
	}
	file_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deployment_proto_rawDesc), len(file_deployment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deployment_proto_goTypes,
		DependencyIndexes: file_deployment_proto_depIdxs,
		MessageInfos:      file_deployment_proto_msgTypes,
	}.Build()
	File_deployment_proto = out.File
	file_deployment_proto_goTypes = nil
	file_deployment_proto_depIdxs = nil
}
