// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: environment.proto

package azdext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to retrieve an environment by name.
type GetEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name of the environment.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentRequest) Reset() {
	*x = GetEnvironmentRequest{}
	mi := &file_environment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentRequest) ProtoMessage() {}

func (x *GetEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*GetEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{0}
}

func (x *GetEnvironmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SelectEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name of the environment.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectEnvironmentRequest) Reset() {
	*x = SelectEnvironmentRequest{}
	mi := &file_environment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectEnvironmentRequest) ProtoMessage() {}

func (x *SelectEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*SelectEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{1}
}

func (x *SelectEnvironmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to retrieve a specific key-value pair.
type GetEnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvName       string                 `protobuf:"bytes,1,opt,name=env_name,json=envName,proto3" json:"env_name,omitempty"` // Name of the environment.
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                        // Key to retrieve.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvRequest) Reset() {
	*x = GetEnvRequest{}
	mi := &file_environment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvRequest) ProtoMessage() {}

func (x *GetEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvRequest.ProtoReflect.Descriptor instead.
func (*GetEnvRequest) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{2}
}

func (x *GetEnvRequest) GetEnvName() string {
	if x != nil {
		return x.EnvName
	}
	return ""
}

func (x *GetEnvRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Request to set a key-value pair.
type SetEnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvName       string                 `protobuf:"bytes,1,opt,name=env_name,json=envName,proto3" json:"env_name,omitempty"` // Name of the environment.
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                        // Key to set.
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                    // Value to set for the key.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEnvRequest) Reset() {
	*x = SetEnvRequest{}
	mi := &file_environment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEnvRequest) ProtoMessage() {}

func (x *SetEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEnvRequest.ProtoReflect.Descriptor instead.
func (*SetEnvRequest) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{3}
}

func (x *SetEnvRequest) GetEnvName() string {
	if x != nil {
		return x.EnvName
	}
	return ""
}

func (x *SetEnvRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetEnvRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Response containing details of an environment.
type EnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   *Environment           `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"` // Environment details.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentResponse) Reset() {
	*x = EnvironmentResponse{}
	mi := &file_environment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentResponse) ProtoMessage() {}

func (x *EnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentResponse.ProtoReflect.Descriptor instead.
func (*EnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{4}
}

func (x *EnvironmentResponse) GetEnvironment() *Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

type EnvironmentListResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Environments  []*EnvironmentDescription `protobuf:"bytes,1,rep,name=environments,proto3" json:"environments,omitempty"` // List of environments.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentListResponse) Reset() {
	*x = EnvironmentListResponse{}
	mi := &file_environment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentListResponse) ProtoMessage() {}

func (x *EnvironmentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentListResponse.ProtoReflect.Descriptor instead.
func (*EnvironmentListResponse) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{5}
}

func (x *EnvironmentListResponse) GetEnvironments() []*EnvironmentDescription {
	if x != nil {
		return x.Environments
	}
	return nil
}

// Response containing a list of key-value pairs.
type KeyValueListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyValues     []*KeyValue            `protobuf:"bytes,1,rep,name=key_values,json=keyValues,proto3" json:"key_values,omitempty"` // List of key-value pairs.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueListResponse) Reset() {
	*x = KeyValueListResponse{}
	mi := &file_environment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueListResponse) ProtoMessage() {}

func (x *KeyValueListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueListResponse.ProtoReflect.Descriptor instead.
func (*KeyValueListResponse) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{6}
}

func (x *KeyValueListResponse) GetKeyValues() []*KeyValue {
	if x != nil {
		return x.KeyValues
	}
	return nil
}

// Response containing a single key-value pair.
type KeyValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // Key name.
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // Value associated with the key.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueResponse) Reset() {
	*x = KeyValueResponse{}
	mi := &file_environment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueResponse) ProtoMessage() {}

func (x *KeyValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueResponse.ProtoReflect.Descriptor instead.
func (*KeyValueResponse) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{7}
}

func (x *KeyValueResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValueResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Environment object definition.
type Environment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name of the environment.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_environment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{8}
}

func (x *Environment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EnvironmentDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`        // Name of the environment.
	Local         bool                   `protobuf:"varint,2,opt,name=local,proto3" json:"local,omitempty"`     // Whether the environment is local.
	Remote        bool                   `protobuf:"varint,3,opt,name=remote,proto3" json:"remote,omitempty"`   // Whether the environment is remote.
	Default       bool                   `protobuf:"varint,4,opt,name=default,proto3" json:"default,omitempty"` // Whether the environment is the default.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentDescription) Reset() {
	*x = EnvironmentDescription{}
	mi := &file_environment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentDescription) ProtoMessage() {}

func (x *EnvironmentDescription) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentDescription.ProtoReflect.Descriptor instead.
func (*EnvironmentDescription) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{9}
}

func (x *EnvironmentDescription) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvironmentDescription) GetLocal() bool {
	if x != nil {
		return x.Local
	}
	return false
}

func (x *EnvironmentDescription) GetRemote() bool {
	if x != nil {
		return x.Remote
	}
	return false
}

func (x *EnvironmentDescription) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

// Key-value pair definition.
type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // Key name.
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // Value associated with the key.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_environment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{10}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Request message for Get
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_environment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{11}
}

func (x *GetConfigRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Response message for Get
type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_environment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{12}
}

func (x *GetConfigResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetConfigResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Request message for GetString
type GetConfigStringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigStringRequest) Reset() {
	*x = GetConfigStringRequest{}
	mi := &file_environment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigStringRequest) ProtoMessage() {}

func (x *GetConfigStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigStringRequest.ProtoReflect.Descriptor instead.
func (*GetConfigStringRequest) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{13}
}

func (x *GetConfigStringRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Response message for GetString
type GetConfigStringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigStringResponse) Reset() {
	*x = GetConfigStringResponse{}
	mi := &file_environment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigStringResponse) ProtoMessage() {}

func (x *GetConfigStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigStringResponse.ProtoReflect.Descriptor instead.
func (*GetConfigStringResponse) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{14}
}

func (x *GetConfigStringResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetConfigStringResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Request message for GetSection
type GetConfigSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigSectionRequest) Reset() {
	*x = GetConfigSectionRequest{}
	mi := &file_environment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigSectionRequest) ProtoMessage() {}

func (x *GetConfigSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigSectionRequest.ProtoReflect.Descriptor instead.
func (*GetConfigSectionRequest) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{15}
}

func (x *GetConfigSectionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Response message for GetSection
type GetConfigSectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       []byte                 `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigSectionResponse) Reset() {
	*x = GetConfigSectionResponse{}
	mi := &file_environment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigSectionResponse) ProtoMessage() {}

func (x *GetConfigSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigSectionResponse.ProtoReflect.Descriptor instead.
func (*GetConfigSectionResponse) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{16}
}

func (x *GetConfigSectionResponse) GetSection() []byte {
	if x != nil {
		return x.Section
	}
	return nil
}

func (x *GetConfigSectionResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Request message for Set
type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_environment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{17}
}

func (x *SetConfigRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SetConfigRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Request message for Unset
type UnsetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsetConfigRequest) Reset() {
	*x = UnsetConfigRequest{}
	mi := &file_environment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsetConfigRequest) ProtoMessage() {}

func (x *UnsetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsetConfigRequest.ProtoReflect.Descriptor instead.
func (*UnsetConfigRequest) Descriptor() ([]byte, []int) {
	return file_environment_proto_rawDescGZIP(), []int{18}
}

func (x *UnsetConfigRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_environment_proto protoreflect.FileDescriptor

const file_environment_proto_rawDesc = "" +
	"\n" +
	"\x11environment.proto\x12\x06azdext\x1a\fmodels.proto\"+\n" +
	"\x15GetEnvironmentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\".\n" +
	"\x18SelectEnvironmentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"<\n" +
	"\rGetEnvRequest\x12\x19\n" +
	"\benv_name\x18\x01 \x01(\tR\aenvName\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"R\n" +
	"\rSetEnvRequest\x12\x19\n" +
	"\benv_name\x18\x01 \x01(\tR\aenvName\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"L\n" +
	"\x13EnvironmentResponse\x125\n" +
	"\venvironment\x18\x01 \x01(\v2\x13.azdext.EnvironmentR\venvironment\"]\n" +
	"\x17EnvironmentListResponse\x12B\n" +
	"\fenvironments\x18\x01 \x03(\v2\x1e.azdext.EnvironmentDescriptionR\fenvironments\"G\n" +
	"\x14KeyValueListResponse\x12/\n" +
	"\n" +
	"key_values\x18\x01 \x03(\v2\x10.azdext.KeyValueR\tkeyValues\":\n" +
	"\x10KeyValueResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"!\n" +
	"\vEnvironment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"t\n" +
	"\x16EnvironmentDescription\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05local\x18\x02 \x01(\bR\x05local\x12\x16\n" +
	"\x06remote\x18\x03 \x01(\bR\x06remote\x12\x18\n" +
	"\adefault\x18\x04 \x01(\bR\adefault\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"&\n" +
	"\x10GetConfigRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"?\n" +
	"\x11GetConfigResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\",\n" +
	"\x16GetConfigStringRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"E\n" +
	"\x17GetConfigStringResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"-\n" +
	"\x17GetConfigSectionRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"J\n" +
	"\x18GetConfigSectionResponse\x12\x18\n" +
	"\asection\x18\x01 \x01(\fR\asection\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"<\n" +
	"\x10SetConfigRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"(\n" +
	"\x12UnsetConfigRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path2\xc8\x06\n" +
	"\x12EnvironmentService\x12?\n" +
	"\n" +
	"GetCurrent\x12\x14.azdext.EmptyRequest\x1a\x1b.azdext.EnvironmentResponse\x12=\n" +
	"\x04List\x12\x14.azdext.EmptyRequest\x1a\x1f.azdext.EnvironmentListResponse\x12A\n" +
	"\x03Get\x12\x1d.azdext.GetEnvironmentRequest\x1a\x1b.azdext.EnvironmentResponse\x12A\n" +
	"\x06Select\x12 .azdext.SelectEnvironmentRequest\x1a\x15.azdext.EmptyResponse\x12H\n" +
	"\tGetValues\x12\x1d.azdext.GetEnvironmentRequest\x1a\x1c.azdext.KeyValueListResponse\x12;\n" +
	"\bGetValue\x12\x15.azdext.GetEnvRequest\x1a\x18.azdext.KeyValueResponse\x128\n" +
	"\bSetValue\x12\x15.azdext.SetEnvRequest\x1a\x15.azdext.EmptyResponse\x12@\n" +
	"\tGetConfig\x12\x18.azdext.GetConfigRequest\x1a\x19.azdext.GetConfigResponse\x12R\n" +
	"\x0fGetConfigString\x12\x1e.azdext.GetConfigStringRequest\x1a\x1f.azdext.GetConfigStringResponse\x12U\n" +
	"\x10GetConfigSection\x12\x1f.azdext.GetConfigSectionRequest\x1a .azdext.GetConfigSectionResponse\x12<\n" +
	"\tSetConfig\x12\x18.azdext.SetConfigRequest\x1a\x15.azdext.EmptyResponse\x12@\n" +
	"\vUnsetConfig\x12\x1a.azdext.UnsetConfigRequest\x1a\x15.azdext.EmptyResponseB6Z4github.com/azure/azure-dev/cli/azd/pkg/azdext;azdextb\x06proto3"

var (
	file_environment_proto_rawDescOnce sync.Once
	file_environment_proto_rawDescData []byte
)

func file_environment_proto_rawDescGZIP() []byte {
	file_environment_proto_rawDescOnce.Do(func() {
		file_environment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_environment_proto_rawDesc), len(file_environment_proto_rawDesc)))
	})
	return file_environment_proto_rawDescData
}

var file_environment_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_environment_proto_goTypes = []any{
	(*GetEnvironmentRequest)(nil),    // 0: azdext.GetEnvironmentRequest
	(*SelectEnvironmentRequest)(nil), // 1: azdext.SelectEnvironmentRequest
	(*GetEnvRequest)(nil),            // 2: azdext.GetEnvRequest
	(*SetEnvRequest)(nil),            // 3: azdext.SetEnvRequest
	(*EnvironmentResponse)(nil),      // 4: azdext.EnvironmentResponse
	(*EnvironmentListResponse)(nil),  // 5: azdext.EnvironmentListResponse
	(*KeyValueListResponse)(nil),     // 6: azdext.KeyValueListResponse
	(*KeyValueResponse)(nil),         // 7: azdext.KeyValueResponse
	(*Environment)(nil),              // 8: azdext.Environment
	(*EnvironmentDescription)(nil),   // 9: azdext.EnvironmentDescription
	(*KeyValue)(nil),                 // 10: azdext.KeyValue
	(*GetConfigRequest)(nil),         // 11: azdext.GetConfigRequest
	(*GetConfigResponse)(nil),        // 12: azdext.GetConfigResponse
	(*GetConfigStringRequest)(nil),   // 13: azdext.GetConfigStringRequest
	(*GetConfigStringResponse)(nil),  // 14: azdext.GetConfigStringResponse
	(*GetConfigSectionRequest)(nil),  // 15: azdext.GetConfigSectionRequest
	(*GetConfigSectionResponse)(nil), // 16: azdext.GetConfigSectionResponse
	(*SetConfigRequest)(nil),         // 17: azdext.SetConfigRequest
	(*UnsetConfigRequest)(nil),       // 18: azdext.UnsetConfigRequest
	(*EmptyRequest)(nil),             // 19: azdext.EmptyRequest
	(*EmptyResponse)(nil),            // 20: azdext.EmptyResponse
}
var file_environment_proto_depIdxs = []int32{
	8,  // 0: azdext.EnvironmentResponse.environment:type_name -> azdext.Environment
	9,  // 1: azdext.EnvironmentListResponse.environments:type_name -> azdext.EnvironmentDescription
	10, // 2: azdext.KeyValueListResponse.key_values:type_name -> azdext.KeyValue
	19, // 3: azdext.EnvironmentService.GetCurrent:input_type -> azdext.EmptyRequest
	19, // 4: azdext.EnvironmentService.List:input_type -> azdext.EmptyRequest
	0,  // 5: azdext.EnvironmentService.Get:input_type -> azdext.GetEnvironmentRequest
	1,  // 6: azdext.EnvironmentService.Select:input_type -> azdext.SelectEnvironmentRequest
	0,  // 7: azdext.EnvironmentService.GetValues:input_type -> azdext.GetEnvironmentRequest
	2,  // 8: azdext.EnvironmentService.GetValue:input_type -> azdext.GetEnvRequest
	3,  // 9: azdext.EnvironmentService.SetValue:input_type -> azdext.SetEnvRequest
	11, // 10: azdext.EnvironmentService.GetConfig:input_type -> azdext.GetConfigRequest
	13, // 11: azdext.EnvironmentService.GetConfigString:input_type -> azdext.GetConfigStringRequest
	15, // 12: azdext.EnvironmentService.GetConfigSection:input_type -> azdext.GetConfigSectionRequest
	17, // 13: azdext.EnvironmentService.SetConfig:input_type -> azdext.SetConfigRequest
	18, // 14: azdext.EnvironmentService.UnsetConfig:input_type -> azdext.UnsetConfigRequest
	4,  // 15: azdext.EnvironmentService.GetCurrent:output_type -> azdext.EnvironmentResponse
	5,  // 16: azdext.EnvironmentService.List:output_type -> azdext.EnvironmentListResponse
	4,  // 17: azdext.EnvironmentService.Get:output_type -> azdext.EnvironmentResponse
	20, // 18: azdext.EnvironmentService.Select:output_type -> azdext.EmptyResponse
	6,  // 19: azdext.EnvironmentService.GetValues:output_type -> azdext.KeyValueListResponse
	7,  // 20: azdext.EnvironmentService.GetValue:output_type -> azdext.KeyValueResponse
	20, // 21: azdext.EnvironmentService.SetValue:output_type -> azdext.EmptyResponse
	12, // 22: azdext.EnvironmentService.GetConfig:output_type -> azdext.GetConfigResponse
	14, // 23: azdext.EnvironmentService.GetConfigString:output_type -> azdext.GetConfigStringResponse
	16, // 24: azdext.EnvironmentService.GetConfigSection:output_type -> azdext.GetConfigSectionResponse
	20, // 25: azdext.EnvironmentService.SetConfig:output_type -> azdext.EmptyResponse
	20, // 26: azdext.EnvironmentService.UnsetConfig:output_type -> azdext.EmptyResponse
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_environment_proto_init() }
func file_environment_proto_init() {
	if File_environment_proto != nil {
		return
	}
	file_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_environment_proto_rawDesc), len(file_environment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_environment_proto_goTypes,
		DependencyIndexes: file_environment_proto_depIdxs,
		MessageInfos:      file_environment_proto_msgTypes,
	}.Build()
	File_environment_proto = out.File
	file_environment_proto_goTypes = nil
	file_environment_proto_depIdxs = nil
}
