// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: provisioning.proto

package azdext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProvisioningSkippedReason int32

const (
	ProvisioningSkippedReason_PROVISIONING_SKIPPED_REASON_UNSPECIFIED      ProvisioningSkippedReason = 0
	ProvisioningSkippedReason_PROVISIONING_SKIPPED_REASON_DEPLOYMENT_STATE ProvisioningSkippedReason = 1
)

// Enum value maps for ProvisioningSkippedReason.
var (
	ProvisioningSkippedReason_name = map[int32]string{
		0: "PROVISIONING_SKIPPED_REASON_UNSPECIFIED",
		1: "PROVISIONING_SKIPPED_REASON_DEPLOYMENT_STATE",
	}
	ProvisioningSkippedReason_value = map[string]int32{
		"PROVISIONING_SKIPPED_REASON_UNSPECIFIED":      0,
		"PROVISIONING_SKIPPED_REASON_DEPLOYMENT_STATE": 1,
	}
)

func (x ProvisioningSkippedReason) Enum() *ProvisioningSkippedReason {
	p := new(ProvisioningSkippedReason)
	*p = x
	return p
}

func (x ProvisioningSkippedReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProvisioningSkippedReason) Descriptor() protoreflect.EnumDescriptor {
	return file_provisioning_proto_enumTypes[0].Descriptor()
}

func (ProvisioningSkippedReason) Type() protoreflect.EnumType {
	return &file_provisioning_proto_enumTypes[0]
}

func (x ProvisioningSkippedReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProvisioningSkippedReason.Descriptor instead.
func (ProvisioningSkippedReason) EnumDescriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{0}
}

// Envelope for all possible provisioning messages (requests and responses)
type ProvisioningMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Error     *ExtensionError        `protobuf:"bytes,99,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*ProvisioningMessage_RegisterProvisioningProviderRequest
	//	*ProvisioningMessage_RegisterProvisioningProviderResponse
	//	*ProvisioningMessage_InitializeRequest
	//	*ProvisioningMessage_InitializeResponse
	//	*ProvisioningMessage_StateRequest
	//	*ProvisioningMessage_StateResponse
	//	*ProvisioningMessage_DeployRequest
	//	*ProvisioningMessage_DeployResponse
	//	*ProvisioningMessage_PreviewRequest
	//	*ProvisioningMessage_PreviewResponse
	//	*ProvisioningMessage_DestroyRequest
	//	*ProvisioningMessage_DestroyResponse
	//	*ProvisioningMessage_EnsureEnvRequest
	//	*ProvisioningMessage_EnsureEnvResponse
	//	*ProvisioningMessage_ParametersRequest
	//	*ProvisioningMessage_ParametersResponse
	//	*ProvisioningMessage_ProgressMessage
	MessageType   isProvisioningMessage_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningMessage) Reset() {
	*x = ProvisioningMessage{}
	mi := &file_provisioning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningMessage) ProtoMessage() {}

func (x *ProvisioningMessage) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningMessage.ProtoReflect.Descriptor instead.
func (*ProvisioningMessage) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{0}
}

func (x *ProvisioningMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProvisioningMessage) GetError() *ExtensionError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ProvisioningMessage) GetMessageType() isProvisioningMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *ProvisioningMessage) GetRegisterProvisioningProviderRequest() *RegisterProvisioningProviderRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_RegisterProvisioningProviderRequest); ok {
			return x.RegisterProvisioningProviderRequest
		}
	}
	return nil
}

func (x *ProvisioningMessage) GetRegisterProvisioningProviderResponse() *RegisterProvisioningProviderResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_RegisterProvisioningProviderResponse); ok {
			return x.RegisterProvisioningProviderResponse
		}
	}
	return nil
}

func (x *ProvisioningMessage) GetInitializeRequest() *ProvisioningInitializeRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_InitializeRequest); ok {
			return x.InitializeRequest
		}
	}
	return nil
}

func (x *ProvisioningMessage) GetInitializeResponse() *ProvisioningInitializeResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_InitializeResponse); ok {
			return x.InitializeResponse
		}
	}
	return nil
}

func (x *ProvisioningMessage) GetStateRequest() *ProvisioningStateRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_StateRequest); ok {
			return x.StateRequest
		}
	}
	return nil
}

func (x *ProvisioningMessage) GetStateResponse() *ProvisioningStateResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_StateResponse); ok {
			return x.StateResponse
		}
	}
	return nil
}

func (x *ProvisioningMessage) GetDeployRequest() *ProvisioningDeployRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_DeployRequest); ok {
			return x.DeployRequest
		}
	}
	return nil
}

func (x *ProvisioningMessage) GetDeployResponse() *ProvisioningDeployResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_DeployResponse); ok {
			return x.DeployResponse
		}
	}
	return nil
}

func (x *ProvisioningMessage) GetPreviewRequest() *ProvisioningPreviewRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_PreviewRequest); ok {
			return x.PreviewRequest
		}
	}
	return nil
}

func (x *ProvisioningMessage) GetPreviewResponse() *ProvisioningPreviewResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_PreviewResponse); ok {
			return x.PreviewResponse
		}
	}
	return nil
}

func (x *ProvisioningMessage) GetDestroyRequest() *ProvisioningDestroyRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_DestroyRequest); ok {
			return x.DestroyRequest
		}
	}
	return nil
}

func (x *ProvisioningMessage) GetDestroyResponse() *ProvisioningDestroyResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_DestroyResponse); ok {
			return x.DestroyResponse
		}
	}
	return nil
}

func (x *ProvisioningMessage) GetEnsureEnvRequest() *ProvisioningEnsureEnvRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_EnsureEnvRequest); ok {
			return x.EnsureEnvRequest
		}
	}
	return nil
}

func (x *ProvisioningMessage) GetEnsureEnvResponse() *ProvisioningEnsureEnvResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_EnsureEnvResponse); ok {
			return x.EnsureEnvResponse
		}
	}
	return nil
}

func (x *ProvisioningMessage) GetParametersRequest() *ProvisioningParametersRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_ParametersRequest); ok {
			return x.ParametersRequest
		}
	}
	return nil
}

func (x *ProvisioningMessage) GetParametersResponse() *ProvisioningParametersResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_ParametersResponse); ok {
			return x.ParametersResponse
		}
	}
	return nil
}

func (x *ProvisioningMessage) GetProgressMessage() *ProvisioningProgressMessage {
	if x != nil {
		if x, ok := x.MessageType.(*ProvisioningMessage_ProgressMessage); ok {
			return x.ProgressMessage
		}
	}
	return nil
}

type isProvisioningMessage_MessageType interface {
	isProvisioningMessage_MessageType()
}

type ProvisioningMessage_RegisterProvisioningProviderRequest struct {
	RegisterProvisioningProviderRequest *RegisterProvisioningProviderRequest `protobuf:"bytes,2,opt,name=register_provisioning_provider_request,json=registerProvisioningProviderRequest,proto3,oneof"`
}

type ProvisioningMessage_RegisterProvisioningProviderResponse struct {
	RegisterProvisioningProviderResponse *RegisterProvisioningProviderResponse `protobuf:"bytes,3,opt,name=register_provisioning_provider_response,json=registerProvisioningProviderResponse,proto3,oneof"`
}

type ProvisioningMessage_InitializeRequest struct {
	InitializeRequest *ProvisioningInitializeRequest `protobuf:"bytes,4,opt,name=initialize_request,json=initializeRequest,proto3,oneof"`
}

type ProvisioningMessage_InitializeResponse struct {
	InitializeResponse *ProvisioningInitializeResponse `protobuf:"bytes,5,opt,name=initialize_response,json=initializeResponse,proto3,oneof"`
}

type ProvisioningMessage_StateRequest struct {
	StateRequest *ProvisioningStateRequest `protobuf:"bytes,6,opt,name=state_request,json=stateRequest,proto3,oneof"`
}

type ProvisioningMessage_StateResponse struct {
	StateResponse *ProvisioningStateResponse `protobuf:"bytes,7,opt,name=state_response,json=stateResponse,proto3,oneof"`
}

type ProvisioningMessage_DeployRequest struct {
	DeployRequest *ProvisioningDeployRequest `protobuf:"bytes,8,opt,name=deploy_request,json=deployRequest,proto3,oneof"`
}

type ProvisioningMessage_DeployResponse struct {
	DeployResponse *ProvisioningDeployResponse `protobuf:"bytes,9,opt,name=deploy_response,json=deployResponse,proto3,oneof"`
}

type ProvisioningMessage_PreviewRequest struct {
	PreviewRequest *ProvisioningPreviewRequest `protobuf:"bytes,10,opt,name=preview_request,json=previewRequest,proto3,oneof"`
}

type ProvisioningMessage_PreviewResponse struct {
	PreviewResponse *ProvisioningPreviewResponse `protobuf:"bytes,11,opt,name=preview_response,json=previewResponse,proto3,oneof"`
}

type ProvisioningMessage_DestroyRequest struct {
	DestroyRequest *ProvisioningDestroyRequest `protobuf:"bytes,12,opt,name=destroy_request,json=destroyRequest,proto3,oneof"`
}

type ProvisioningMessage_DestroyResponse struct {
	DestroyResponse *ProvisioningDestroyResponse `protobuf:"bytes,13,opt,name=destroy_response,json=destroyResponse,proto3,oneof"`
}

type ProvisioningMessage_EnsureEnvRequest struct {
	EnsureEnvRequest *ProvisioningEnsureEnvRequest `protobuf:"bytes,14,opt,name=ensure_env_request,json=ensureEnvRequest,proto3,oneof"`
}

type ProvisioningMessage_EnsureEnvResponse struct {
	EnsureEnvResponse *ProvisioningEnsureEnvResponse `protobuf:"bytes,15,opt,name=ensure_env_response,json=ensureEnvResponse,proto3,oneof"`
}

type ProvisioningMessage_ParametersRequest struct {
	ParametersRequest *ProvisioningParametersRequest `protobuf:"bytes,16,opt,name=parameters_request,json=parametersRequest,proto3,oneof"`
}

type ProvisioningMessage_ParametersResponse struct {
	ParametersResponse *ProvisioningParametersResponse `protobuf:"bytes,17,opt,name=parameters_response,json=parametersResponse,proto3,oneof"`
}

type ProvisioningMessage_ProgressMessage struct {
	ProgressMessage *ProvisioningProgressMessage `protobuf:"bytes,18,opt,name=progress_message,json=progressMessage,proto3,oneof"`
}

func (*ProvisioningMessage_RegisterProvisioningProviderRequest) isProvisioningMessage_MessageType() {}

func (*ProvisioningMessage_RegisterProvisioningProviderResponse) isProvisioningMessage_MessageType() {
}

func (*ProvisioningMessage_InitializeRequest) isProvisioningMessage_MessageType() {}

func (*ProvisioningMessage_InitializeResponse) isProvisioningMessage_MessageType() {}

func (*ProvisioningMessage_StateRequest) isProvisioningMessage_MessageType() {}

func (*ProvisioningMessage_StateResponse) isProvisioningMessage_MessageType() {}

func (*ProvisioningMessage_DeployRequest) isProvisioningMessage_MessageType() {}

func (*ProvisioningMessage_DeployResponse) isProvisioningMessage_MessageType() {}

func (*ProvisioningMessage_PreviewRequest) isProvisioningMessage_MessageType() {}

func (*ProvisioningMessage_PreviewResponse) isProvisioningMessage_MessageType() {}

func (*ProvisioningMessage_DestroyRequest) isProvisioningMessage_MessageType() {}

func (*ProvisioningMessage_DestroyResponse) isProvisioningMessage_MessageType() {}

func (*ProvisioningMessage_EnsureEnvRequest) isProvisioningMessage_MessageType() {}

func (*ProvisioningMessage_EnsureEnvResponse) isProvisioningMessage_MessageType() {}

func (*ProvisioningMessage_ParametersRequest) isProvisioningMessage_MessageType() {}

func (*ProvisioningMessage_ParametersResponse) isProvisioningMessage_MessageType() {}

func (*ProvisioningMessage_ProgressMessage) isProvisioningMessage_MessageType() {}

type RegisterProvisioningProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProvisioningProviderRequest) Reset() {
	*x = RegisterProvisioningProviderRequest{}
	mi := &file_provisioning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProvisioningProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProvisioningProviderRequest) ProtoMessage() {}

func (x *RegisterProvisioningProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProvisioningProviderRequest.ProtoReflect.Descriptor instead.
func (*RegisterProvisioningProviderRequest) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterProvisioningProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterProvisioningProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProvisioningProviderResponse) Reset() {
	*x = RegisterProvisioningProviderResponse{}
	mi := &file_provisioning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProvisioningProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProvisioningProviderResponse) ProtoMessage() {}

func (x *RegisterProvisioningProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProvisioningProviderResponse.ProtoReflect.Descriptor instead.
func (*RegisterProvisioningProviderResponse) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{2}
}

type ProvisioningInitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	Options       *ProvisioningOptions   `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningInitializeRequest) Reset() {
	*x = ProvisioningInitializeRequest{}
	mi := &file_provisioning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningInitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningInitializeRequest) ProtoMessage() {}

func (x *ProvisioningInitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningInitializeRequest.ProtoReflect.Descriptor instead.
func (*ProvisioningInitializeRequest) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{3}
}

func (x *ProvisioningInitializeRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *ProvisioningInitializeRequest) GetOptions() *ProvisioningOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ProvisioningInitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningInitializeResponse) Reset() {
	*x = ProvisioningInitializeResponse{}
	mi := &file_provisioning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningInitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningInitializeResponse) ProtoMessage() {}

func (x *ProvisioningInitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningInitializeResponse.ProtoReflect.Descriptor instead.
func (*ProvisioningInitializeResponse) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{4}
}

type ProvisioningStateRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Options       *ProvisioningStateOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningStateRequest) Reset() {
	*x = ProvisioningStateRequest{}
	mi := &file_provisioning_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningStateRequest) ProtoMessage() {}

func (x *ProvisioningStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningStateRequest.ProtoReflect.Descriptor instead.
func (*ProvisioningStateRequest) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{5}
}

func (x *ProvisioningStateRequest) GetOptions() *ProvisioningStateOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ProvisioningStateResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	StateResult   *ProvisioningStateResult `protobuf:"bytes,1,opt,name=state_result,json=stateResult,proto3" json:"state_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningStateResponse) Reset() {
	*x = ProvisioningStateResponse{}
	mi := &file_provisioning_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningStateResponse) ProtoMessage() {}

func (x *ProvisioningStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningStateResponse.ProtoReflect.Descriptor instead.
func (*ProvisioningStateResponse) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{6}
}

func (x *ProvisioningStateResponse) GetStateResult() *ProvisioningStateResult {
	if x != nil {
		return x.StateResult
	}
	return nil
}

type ProvisioningDeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningDeployRequest) Reset() {
	*x = ProvisioningDeployRequest{}
	mi := &file_provisioning_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningDeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningDeployRequest) ProtoMessage() {}

func (x *ProvisioningDeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningDeployRequest.ProtoReflect.Descriptor instead.
func (*ProvisioningDeployRequest) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{7}
}

type ProvisioningDeployResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Result        *ProvisioningDeployResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningDeployResponse) Reset() {
	*x = ProvisioningDeployResponse{}
	mi := &file_provisioning_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningDeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningDeployResponse) ProtoMessage() {}

func (x *ProvisioningDeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningDeployResponse.ProtoReflect.Descriptor instead.
func (*ProvisioningDeployResponse) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{8}
}

func (x *ProvisioningDeployResponse) GetResult() *ProvisioningDeployResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ProvisioningPreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningPreviewRequest) Reset() {
	*x = ProvisioningPreviewRequest{}
	mi := &file_provisioning_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningPreviewRequest) ProtoMessage() {}

func (x *ProvisioningPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningPreviewRequest.ProtoReflect.Descriptor instead.
func (*ProvisioningPreviewRequest) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{9}
}

type ProvisioningPreviewResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Result        *ProvisioningPreviewResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningPreviewResponse) Reset() {
	*x = ProvisioningPreviewResponse{}
	mi := &file_provisioning_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningPreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningPreviewResponse) ProtoMessage() {}

func (x *ProvisioningPreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningPreviewResponse.ProtoReflect.Descriptor instead.
func (*ProvisioningPreviewResponse) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{10}
}

func (x *ProvisioningPreviewResponse) GetResult() *ProvisioningPreviewResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ProvisioningDestroyRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Options       *ProvisioningDestroyOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningDestroyRequest) Reset() {
	*x = ProvisioningDestroyRequest{}
	mi := &file_provisioning_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningDestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningDestroyRequest) ProtoMessage() {}

func (x *ProvisioningDestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningDestroyRequest.ProtoReflect.Descriptor instead.
func (*ProvisioningDestroyRequest) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{11}
}

func (x *ProvisioningDestroyRequest) GetOptions() *ProvisioningDestroyOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ProvisioningDestroyResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Result        *ProvisioningDestroyResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningDestroyResponse) Reset() {
	*x = ProvisioningDestroyResponse{}
	mi := &file_provisioning_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningDestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningDestroyResponse) ProtoMessage() {}

func (x *ProvisioningDestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningDestroyResponse.ProtoReflect.Descriptor instead.
func (*ProvisioningDestroyResponse) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{12}
}

func (x *ProvisioningDestroyResponse) GetResult() *ProvisioningDestroyResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ProvisioningEnsureEnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningEnsureEnvRequest) Reset() {
	*x = ProvisioningEnsureEnvRequest{}
	mi := &file_provisioning_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningEnsureEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningEnsureEnvRequest) ProtoMessage() {}

func (x *ProvisioningEnsureEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningEnsureEnvRequest.ProtoReflect.Descriptor instead.
func (*ProvisioningEnsureEnvRequest) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{13}
}

type ProvisioningEnsureEnvResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningEnsureEnvResponse) Reset() {
	*x = ProvisioningEnsureEnvResponse{}
	mi := &file_provisioning_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningEnsureEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningEnsureEnvResponse) ProtoMessage() {}

func (x *ProvisioningEnsureEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningEnsureEnvResponse.ProtoReflect.Descriptor instead.
func (*ProvisioningEnsureEnvResponse) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{14}
}

type ProvisioningParametersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningParametersRequest) Reset() {
	*x = ProvisioningParametersRequest{}
	mi := &file_provisioning_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningParametersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningParametersRequest) ProtoMessage() {}

func (x *ProvisioningParametersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningParametersRequest.ProtoReflect.Descriptor instead.
func (*ProvisioningParametersRequest) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{15}
}

type ProvisioningParametersResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Parameters    []*ProvisioningParameter `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningParametersResponse) Reset() {
	*x = ProvisioningParametersResponse{}
	mi := &file_provisioning_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningParametersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningParametersResponse) ProtoMessage() {}

func (x *ProvisioningParametersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningParametersResponse.ProtoReflect.Descriptor instead.
func (*ProvisioningParametersResponse) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{16}
}

func (x *ProvisioningParametersResponse) GetParameters() []*ProvisioningParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ProvisioningOptions struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Provider              string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Path                  string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Module                string                 `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	DeploymentStacks      map[string]string      `protobuf:"bytes,4,rep,name=deployment_stacks,json=deploymentStacks,proto3" json:"deployment_stacks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IgnoreDeploymentState bool                   `protobuf:"varint,5,opt,name=ignore_deployment_state,json=ignoreDeploymentState,proto3" json:"ignore_deployment_state,omitempty"`
	Config                *structpb.Struct       `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ProvisioningOptions) Reset() {
	*x = ProvisioningOptions{}
	mi := &file_provisioning_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningOptions) ProtoMessage() {}

func (x *ProvisioningOptions) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningOptions.ProtoReflect.Descriptor instead.
func (*ProvisioningOptions) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{17}
}

func (x *ProvisioningOptions) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ProvisioningOptions) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProvisioningOptions) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ProvisioningOptions) GetDeploymentStacks() map[string]string {
	if x != nil {
		return x.DeploymentStacks
	}
	return nil
}

func (x *ProvisioningOptions) GetIgnoreDeploymentState() bool {
	if x != nil {
		return x.IgnoreDeploymentState
	}
	return false
}

func (x *ProvisioningOptions) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type ProvisioningStateOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningStateOptions) Reset() {
	*x = ProvisioningStateOptions{}
	mi := &file_provisioning_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningStateOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningStateOptions) ProtoMessage() {}

func (x *ProvisioningStateOptions) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningStateOptions.ProtoReflect.Descriptor instead.
func (*ProvisioningStateOptions) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{18}
}

type ProvisioningStateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *ProvisioningState     `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningStateResult) Reset() {
	*x = ProvisioningStateResult{}
	mi := &file_provisioning_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningStateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningStateResult) ProtoMessage() {}

func (x *ProvisioningStateResult) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningStateResult.ProtoReflect.Descriptor instead.
func (*ProvisioningStateResult) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{19}
}

func (x *ProvisioningStateResult) GetState() *ProvisioningState {
	if x != nil {
		return x.State
	}
	return nil
}

type ProvisioningState struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Outputs       map[string]*ProvisioningOutputParameter `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Resources     []*ProvisioningResource                 `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningState) Reset() {
	*x = ProvisioningState{}
	mi := &file_provisioning_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningState) ProtoMessage() {}

func (x *ProvisioningState) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningState.ProtoReflect.Descriptor instead.
func (*ProvisioningState) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{20}
}

func (x *ProvisioningState) GetOutputs() map[string]*ProvisioningOutputParameter {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ProvisioningState) GetResources() []*ProvisioningResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ProvisioningDeployment struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Parameters    map[string]*ProvisioningInputParameter  `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Outputs       map[string]*ProvisioningOutputParameter `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningDeployment) Reset() {
	*x = ProvisioningDeployment{}
	mi := &file_provisioning_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningDeployment) ProtoMessage() {}

func (x *ProvisioningDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningDeployment.ProtoReflect.Descriptor instead.
func (*ProvisioningDeployment) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{21}
}

func (x *ProvisioningDeployment) GetParameters() map[string]*ProvisioningInputParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ProvisioningDeployment) GetOutputs() map[string]*ProvisioningOutputParameter {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type ProvisioningDeployResult struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Deployment    *ProvisioningDeployment   `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	SkippedReason ProvisioningSkippedReason `protobuf:"varint,2,opt,name=skipped_reason,json=skippedReason,proto3,enum=azdext.ProvisioningSkippedReason" json:"skipped_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningDeployResult) Reset() {
	*x = ProvisioningDeployResult{}
	mi := &file_provisioning_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningDeployResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningDeployResult) ProtoMessage() {}

func (x *ProvisioningDeployResult) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningDeployResult.ProtoReflect.Descriptor instead.
func (*ProvisioningDeployResult) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{22}
}

func (x *ProvisioningDeployResult) GetDeployment() *ProvisioningDeployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *ProvisioningDeployResult) GetSkippedReason() ProvisioningSkippedReason {
	if x != nil {
		return x.SkippedReason
	}
	return ProvisioningSkippedReason_PROVISIONING_SKIPPED_REASON_UNSPECIFIED
}

type ProvisioningDeploymentPreview struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Summary       string                                  `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Parameters    map[string]*ProvisioningInputParameter  `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Outputs       map[string]*ProvisioningOutputParameter `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningDeploymentPreview) Reset() {
	*x = ProvisioningDeploymentPreview{}
	mi := &file_provisioning_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningDeploymentPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningDeploymentPreview) ProtoMessage() {}

func (x *ProvisioningDeploymentPreview) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningDeploymentPreview.ProtoReflect.Descriptor instead.
func (*ProvisioningDeploymentPreview) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{23}
}

func (x *ProvisioningDeploymentPreview) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ProvisioningDeploymentPreview) GetParameters() map[string]*ProvisioningInputParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ProvisioningDeploymentPreview) GetOutputs() map[string]*ProvisioningOutputParameter {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type ProvisioningPreviewResult struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Preview       *ProvisioningDeploymentPreview `protobuf:"bytes,1,opt,name=preview,proto3" json:"preview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningPreviewResult) Reset() {
	*x = ProvisioningPreviewResult{}
	mi := &file_provisioning_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningPreviewResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningPreviewResult) ProtoMessage() {}

func (x *ProvisioningPreviewResult) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningPreviewResult.ProtoReflect.Descriptor instead.
func (*ProvisioningPreviewResult) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{24}
}

func (x *ProvisioningPreviewResult) GetPreview() *ProvisioningDeploymentPreview {
	if x != nil {
		return x.Preview
	}
	return nil
}

type ProvisioningDestroyOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	Purge         bool                   `protobuf:"varint,2,opt,name=purge,proto3" json:"purge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningDestroyOptions) Reset() {
	*x = ProvisioningDestroyOptions{}
	mi := &file_provisioning_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningDestroyOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningDestroyOptions) ProtoMessage() {}

func (x *ProvisioningDestroyOptions) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningDestroyOptions.ProtoReflect.Descriptor instead.
func (*ProvisioningDestroyOptions) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{25}
}

func (x *ProvisioningDestroyOptions) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *ProvisioningDestroyOptions) GetPurge() bool {
	if x != nil {
		return x.Purge
	}
	return false
}

type ProvisioningDestroyResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InvalidatedEnvKeys []string               `protobuf:"bytes,1,rep,name=invalidated_env_keys,json=invalidatedEnvKeys,proto3" json:"invalidated_env_keys,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProvisioningDestroyResult) Reset() {
	*x = ProvisioningDestroyResult{}
	mi := &file_provisioning_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningDestroyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningDestroyResult) ProtoMessage() {}

func (x *ProvisioningDestroyResult) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningDestroyResult.ProtoReflect.Descriptor instead.
func (*ProvisioningDestroyResult) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{26}
}

func (x *ProvisioningDestroyResult) GetInvalidatedEnvKeys() []string {
	if x != nil {
		return x.InvalidatedEnvKeys
	}
	return nil
}

type ProvisioningInputParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,2,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningInputParameter) Reset() {
	*x = ProvisioningInputParameter{}
	mi := &file_provisioning_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningInputParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningInputParameter) ProtoMessage() {}

func (x *ProvisioningInputParameter) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningInputParameter.ProtoReflect.Descriptor instead.
func (*ProvisioningInputParameter) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{27}
}

func (x *ProvisioningInputParameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProvisioningInputParameter) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ProvisioningInputParameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ProvisioningOutputParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningOutputParameter) Reset() {
	*x = ProvisioningOutputParameter{}
	mi := &file_provisioning_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningOutputParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningOutputParameter) ProtoMessage() {}

func (x *ProvisioningOutputParameter) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningOutputParameter.ProtoReflect.Descriptor instead.
func (*ProvisioningOutputParameter) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{28}
}

func (x *ProvisioningOutputParameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProvisioningOutputParameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ProvisioningResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningResource) Reset() {
	*x = ProvisioningResource{}
	mi := &file_provisioning_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningResource) ProtoMessage() {}

func (x *ProvisioningResource) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningResource.ProtoReflect.Descriptor instead.
func (*ProvisioningResource) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{29}
}

func (x *ProvisioningResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProvisioningParameter struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Secret             bool                   `protobuf:"varint,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Value              string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	EnvVarMapping      []string               `protobuf:"bytes,4,rep,name=env_var_mapping,json=envVarMapping,proto3" json:"env_var_mapping,omitempty"`
	LocalPrompt        bool                   `protobuf:"varint,5,opt,name=local_prompt,json=localPrompt,proto3" json:"local_prompt,omitempty"`
	UsingEnvVarMapping bool                   `protobuf:"varint,6,opt,name=using_env_var_mapping,json=usingEnvVarMapping,proto3" json:"using_env_var_mapping,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProvisioningParameter) Reset() {
	*x = ProvisioningParameter{}
	mi := &file_provisioning_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningParameter) ProtoMessage() {}

func (x *ProvisioningParameter) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningParameter.ProtoReflect.Descriptor instead.
func (*ProvisioningParameter) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{30}
}

func (x *ProvisioningParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProvisioningParameter) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

func (x *ProvisioningParameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ProvisioningParameter) GetEnvVarMapping() []string {
	if x != nil {
		return x.EnvVarMapping
	}
	return nil
}

func (x *ProvisioningParameter) GetLocalPrompt() bool {
	if x != nil {
		return x.LocalPrompt
	}
	return false
}

func (x *ProvisioningParameter) GetUsingEnvVarMapping() bool {
	if x != nil {
		return x.UsingEnvVarMapping
	}
	return false
}

type ProvisioningProgressMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningProgressMessage) Reset() {
	*x = ProvisioningProgressMessage{}
	mi := &file_provisioning_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningProgressMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningProgressMessage) ProtoMessage() {}

func (x *ProvisioningProgressMessage) ProtoReflect() protoreflect.Message {
	mi := &file_provisioning_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningProgressMessage.ProtoReflect.Descriptor instead.
func (*ProvisioningProgressMessage) Descriptor() ([]byte, []int) {
	return file_provisioning_proto_rawDescGZIP(), []int{31}
}

func (x *ProvisioningProgressMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProvisioningProgressMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProvisioningProgressMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_provisioning_proto protoreflect.FileDescriptor

const file_provisioning_proto_rawDesc = "" +
	"\n" +
	"\x12provisioning.proto\x12\x06azdext\x1a$include/google/protobuf/struct.proto\x1a\ferrors.proto\"\xd8\f\n" +
	"\x13ProvisioningMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12,\n" +
	"\x05error\x18c \x01(\v2\x16.azdext.ExtensionErrorR\x05error\x12\x82\x01\n" +
	"&register_provisioning_provider_request\x18\x02 \x01(\v2+.azdext.RegisterProvisioningProviderRequestH\x00R#registerProvisioningProviderRequest\x12\x85\x01\n" +
	"'register_provisioning_provider_response\x18\x03 \x01(\v2,.azdext.RegisterProvisioningProviderResponseH\x00R$registerProvisioningProviderResponse\x12V\n" +
	"\x12initialize_request\x18\x04 \x01(\v2%.azdext.ProvisioningInitializeRequestH\x00R\x11initializeRequest\x12Y\n" +
	"\x13initialize_response\x18\x05 \x01(\v2&.azdext.ProvisioningInitializeResponseH\x00R\x12initializeResponse\x12G\n" +
	"\rstate_request\x18\x06 \x01(\v2 .azdext.ProvisioningStateRequestH\x00R\fstateRequest\x12J\n" +
	"\x0estate_response\x18\a \x01(\v2!.azdext.ProvisioningStateResponseH\x00R\rstateResponse\x12J\n" +
	"\x0edeploy_request\x18\b \x01(\v2!.azdext.ProvisioningDeployRequestH\x00R\rdeployRequest\x12M\n" +
	"\x0fdeploy_response\x18\t \x01(\v2\".azdext.ProvisioningDeployResponseH\x00R\x0edeployResponse\x12M\n" +
	"\x0fpreview_request\x18\n" +
	" \x01(\v2\".azdext.ProvisioningPreviewRequestH\x00R\x0epreviewRequest\x12P\n" +
	"\x10preview_response\x18\v \x01(\v2#.azdext.ProvisioningPreviewResponseH\x00R\x0fpreviewResponse\x12M\n" +
	"\x0fdestroy_request\x18\f \x01(\v2\".azdext.ProvisioningDestroyRequestH\x00R\x0edestroyRequest\x12P\n" +
	"\x10destroy_response\x18\r \x01(\v2#.azdext.ProvisioningDestroyResponseH\x00R\x0fdestroyResponse\x12T\n" +
	"\x12ensure_env_request\x18\x0e \x01(\v2$.azdext.ProvisioningEnsureEnvRequestH\x00R\x10ensureEnvRequest\x12W\n" +
	"\x13ensure_env_response\x18\x0f \x01(\v2%.azdext.ProvisioningEnsureEnvResponseH\x00R\x11ensureEnvResponse\x12V\n" +
	"\x12parameters_request\x18\x10 \x01(\v2%.azdext.ProvisioningParametersRequestH\x00R\x11parametersRequest\x12Y\n" +
	"\x13parameters_response\x18\x11 \x01(\v2&.azdext.ProvisioningParametersResponseH\x00R\x12parametersResponse\x12P\n" +
	"\x10progress_message\x18\x12 \x01(\v2#.azdext.ProvisioningProgressMessageH\x00R\x0fprogressMessageB\x0e\n" +
	"\fmessage_type\"9\n" +
	"#RegisterProvisioningProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"$RegisterProvisioningProviderResponse\"y\n" +
	"\x1dProvisioningInitializeRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x125\n" +
	"\aoptions\x18\x02 \x01(\v2\x1b.azdext.ProvisioningOptionsR\aoptions\" \n" +
	"\x1eProvisioningInitializeResponse\"V\n" +
	"\x18ProvisioningStateRequest\x12:\n" +
	"\aoptions\x18\x01 \x01(\v2 .azdext.ProvisioningStateOptionsR\aoptions\"_\n" +
	"\x19ProvisioningStateResponse\x12B\n" +
	"\fstate_result\x18\x01 \x01(\v2\x1f.azdext.ProvisioningStateResultR\vstateResult\"\x1b\n" +
	"\x19ProvisioningDeployRequest\"V\n" +
	"\x1aProvisioningDeployResponse\x128\n" +
	"\x06result\x18\x01 \x01(\v2 .azdext.ProvisioningDeployResultR\x06result\"\x1c\n" +
	"\x1aProvisioningPreviewRequest\"X\n" +
	"\x1bProvisioningPreviewResponse\x129\n" +
	"\x06result\x18\x01 \x01(\v2!.azdext.ProvisioningPreviewResultR\x06result\"Z\n" +
	"\x1aProvisioningDestroyRequest\x12<\n" +
	"\aoptions\x18\x01 \x01(\v2\".azdext.ProvisioningDestroyOptionsR\aoptions\"X\n" +
	"\x1bProvisioningDestroyResponse\x129\n" +
	"\x06result\x18\x01 \x01(\v2!.azdext.ProvisioningDestroyResultR\x06result\"\x1e\n" +
	"\x1cProvisioningEnsureEnvRequest\"\x1f\n" +
	"\x1dProvisioningEnsureEnvResponse\"\x1f\n" +
	"\x1dProvisioningParametersRequest\"_\n" +
	"\x1eProvisioningParametersResponse\x12=\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2\x1d.azdext.ProvisioningParameterR\n" +
	"parameters\"\xeb\x02\n" +
	"\x13ProvisioningOptions\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06module\x18\x03 \x01(\tR\x06module\x12^\n" +
	"\x11deployment_stacks\x18\x04 \x03(\v21.azdext.ProvisioningOptions.DeploymentStacksEntryR\x10deploymentStacks\x126\n" +
	"\x17ignore_deployment_state\x18\x05 \x01(\bR\x15ignoreDeploymentState\x12/\n" +
	"\x06config\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06config\x1aC\n" +
	"\x15DeploymentStacksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1a\n" +
	"\x18ProvisioningStateOptions\"J\n" +
	"\x17ProvisioningStateResult\x12/\n" +
	"\x05state\x18\x01 \x01(\v2\x19.azdext.ProvisioningStateR\x05state\"\xf2\x01\n" +
	"\x11ProvisioningState\x12@\n" +
	"\aoutputs\x18\x01 \x03(\v2&.azdext.ProvisioningState.OutputsEntryR\aoutputs\x12:\n" +
	"\tresources\x18\x02 \x03(\v2\x1c.azdext.ProvisioningResourceR\tresources\x1a_\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.azdext.ProvisioningOutputParameterR\x05value:\x028\x01\"\xf3\x02\n" +
	"\x16ProvisioningDeployment\x12N\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2..azdext.ProvisioningDeployment.ParametersEntryR\n" +
	"parameters\x12E\n" +
	"\aoutputs\x18\x02 \x03(\v2+.azdext.ProvisioningDeployment.OutputsEntryR\aoutputs\x1aa\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".azdext.ProvisioningInputParameterR\x05value:\x028\x01\x1a_\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.azdext.ProvisioningOutputParameterR\x05value:\x028\x01\"\xa4\x01\n" +
	"\x18ProvisioningDeployResult\x12>\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\x1e.azdext.ProvisioningDeploymentR\n" +
	"deployment\x12H\n" +
	"\x0eskipped_reason\x18\x02 \x01(\x0e2!.azdext.ProvisioningSkippedReasonR\rskippedReason\"\xa2\x03\n" +
	"\x1dProvisioningDeploymentPreview\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12U\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v25.azdext.ProvisioningDeploymentPreview.ParametersEntryR\n" +
	"parameters\x12L\n" +
	"\aoutputs\x18\x03 \x03(\v22.azdext.ProvisioningDeploymentPreview.OutputsEntryR\aoutputs\x1aa\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".azdext.ProvisioningInputParameterR\x05value:\x028\x01\x1a_\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.azdext.ProvisioningOutputParameterR\x05value:\x028\x01\"\\\n" +
	"\x19ProvisioningPreviewResult\x12?\n" +
	"\apreview\x18\x01 \x01(\v2%.azdext.ProvisioningDeploymentPreviewR\apreview\"H\n" +
	"\x1aProvisioningDestroyOptions\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\x12\x14\n" +
	"\x05purge\x18\x02 \x01(\bR\x05purge\"M\n" +
	"\x19ProvisioningDestroyResult\x120\n" +
	"\x14invalidated_env_keys\x18\x01 \x03(\tR\x12invalidatedEnvKeys\"k\n" +
	"\x1aProvisioningInputParameter\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12#\n" +
	"\rdefault_value\x18\x02 \x01(\tR\fdefaultValue\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"G\n" +
	"\x1bProvisioningOutputParameter\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"&\n" +
	"\x14ProvisioningResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd7\x01\n" +
	"\x15ProvisioningParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\bR\x06secret\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12&\n" +
	"\x0fenv_var_mapping\x18\x04 \x03(\tR\renvVarMapping\x12!\n" +
	"\flocal_prompt\x18\x05 \x01(\bR\vlocalPrompt\x121\n" +
	"\x15using_env_var_mapping\x18\x06 \x01(\bR\x12usingEnvVarMapping\"t\n" +
	"\x1bProvisioningProgressMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp*z\n" +
	"\x19ProvisioningSkippedReason\x12+\n" +
	"'PROVISIONING_SKIPPED_REASON_UNSPECIFIED\x10\x00\x120\n" +
	",PROVISIONING_SKIPPED_REASON_DEPLOYMENT_STATE\x10\x012]\n" +
	"\x13ProvisioningService\x12F\n" +
	"\x06Stream\x12\x1b.azdext.ProvisioningMessage\x1a\x1b.azdext.ProvisioningMessage(\x010\x01B/Z-github.com/azure/azure-dev/cli/azd/pkg/azdextb\x06proto3"

var (
	file_provisioning_proto_rawDescOnce sync.Once
	file_provisioning_proto_rawDescData []byte
)

func file_provisioning_proto_rawDescGZIP() []byte {
	file_provisioning_proto_rawDescOnce.Do(func() {
		file_provisioning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provisioning_proto_rawDesc), len(file_provisioning_proto_rawDesc)))
	})
	return file_provisioning_proto_rawDescData
}

var file_provisioning_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_provisioning_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_provisioning_proto_goTypes = []any{
	(ProvisioningSkippedReason)(0),               // 0: azdext.ProvisioningSkippedReason
	(*ProvisioningMessage)(nil),                  // 1: azdext.ProvisioningMessage
	(*RegisterProvisioningProviderRequest)(nil),  // 2: azdext.RegisterProvisioningProviderRequest
	(*RegisterProvisioningProviderResponse)(nil), // 3: azdext.RegisterProvisioningProviderResponse
	(*ProvisioningInitializeRequest)(nil),        // 4: azdext.ProvisioningInitializeRequest
	(*ProvisioningInitializeResponse)(nil),       // 5: azdext.ProvisioningInitializeResponse
	(*ProvisioningStateRequest)(nil),             // 6: azdext.ProvisioningStateRequest
	(*ProvisioningStateResponse)(nil),            // 7: azdext.ProvisioningStateResponse
	(*ProvisioningDeployRequest)(nil),            // 8: azdext.ProvisioningDeployRequest
	(*ProvisioningDeployResponse)(nil),           // 9: azdext.ProvisioningDeployResponse
	(*ProvisioningPreviewRequest)(nil),           // 10: azdext.ProvisioningPreviewRequest
	(*ProvisioningPreviewResponse)(nil),          // 11: azdext.ProvisioningPreviewResponse
	(*ProvisioningDestroyRequest)(nil),           // 12: azdext.ProvisioningDestroyRequest
	(*ProvisioningDestroyResponse)(nil),          // 13: azdext.ProvisioningDestroyResponse
	(*ProvisioningEnsureEnvRequest)(nil),         // 14: azdext.ProvisioningEnsureEnvRequest
	(*ProvisioningEnsureEnvResponse)(nil),        // 15: azdext.ProvisioningEnsureEnvResponse
	(*ProvisioningParametersRequest)(nil),        // 16: azdext.ProvisioningParametersRequest
	(*ProvisioningParametersResponse)(nil),       // 17: azdext.ProvisioningParametersResponse
	(*ProvisioningOptions)(nil),                  // 18: azdext.ProvisioningOptions
	(*ProvisioningStateOptions)(nil),             // 19: azdext.ProvisioningStateOptions
	(*ProvisioningStateResult)(nil),              // 20: azdext.ProvisioningStateResult
	(*ProvisioningState)(nil),                    // 21: azdext.ProvisioningState
	(*ProvisioningDeployment)(nil),               // 22: azdext.ProvisioningDeployment
	(*ProvisioningDeployResult)(nil),             // 23: azdext.ProvisioningDeployResult
	(*ProvisioningDeploymentPreview)(nil),        // 24: azdext.ProvisioningDeploymentPreview
	(*ProvisioningPreviewResult)(nil),            // 25: azdext.ProvisioningPreviewResult
	(*ProvisioningDestroyOptions)(nil),           // 26: azdext.ProvisioningDestroyOptions
	(*ProvisioningDestroyResult)(nil),            // 27: azdext.ProvisioningDestroyResult
	(*ProvisioningInputParameter)(nil),           // 28: azdext.ProvisioningInputParameter
	(*ProvisioningOutputParameter)(nil),          // 29: azdext.ProvisioningOutputParameter
	(*ProvisioningResource)(nil),                 // 30: azdext.ProvisioningResource
	(*ProvisioningParameter)(nil),                // 31: azdext.ProvisioningParameter
	(*ProvisioningProgressMessage)(nil),          // 32: azdext.ProvisioningProgressMessage
	nil,                                          // 33: azdext.ProvisioningOptions.DeploymentStacksEntry
	nil,                                          // 34: azdext.ProvisioningState.OutputsEntry
	nil,                                          // 35: azdext.ProvisioningDeployment.ParametersEntry
	nil,                                          // 36: azdext.ProvisioningDeployment.OutputsEntry
	nil,                                          // 37: azdext.ProvisioningDeploymentPreview.ParametersEntry
	nil,                                          // 38: azdext.ProvisioningDeploymentPreview.OutputsEntry
	(*ExtensionError)(nil),                       // 39: azdext.ExtensionError
	(*structpb.Struct)(nil),                      // 40: google.protobuf.Struct
}
var file_provisioning_proto_depIdxs = []int32{
	39, // 0: azdext.ProvisioningMessage.error:type_name -> azdext.ExtensionError
	2,  // 1: azdext.ProvisioningMessage.register_provisioning_provider_request:type_name -> azdext.RegisterProvisioningProviderRequest
	3,  // 2: azdext.ProvisioningMessage.register_provisioning_provider_response:type_name -> azdext.RegisterProvisioningProviderResponse
	4,  // 3: azdext.ProvisioningMessage.initialize_request:type_name -> azdext.ProvisioningInitializeRequest
	5,  // 4: azdext.ProvisioningMessage.initialize_response:type_name -> azdext.ProvisioningInitializeResponse
	6,  // 5: azdext.ProvisioningMessage.state_request:type_name -> azdext.ProvisioningStateRequest
	7,  // 6: azdext.ProvisioningMessage.state_response:type_name -> azdext.ProvisioningStateResponse
	8,  // 7: azdext.ProvisioningMessage.deploy_request:type_name -> azdext.ProvisioningDeployRequest
	9,  // 8: azdext.ProvisioningMessage.deploy_response:type_name -> azdext.ProvisioningDeployResponse
	10, // 9: azdext.ProvisioningMessage.preview_request:type_name -> azdext.ProvisioningPreviewRequest
	11, // 10: azdext.ProvisioningMessage.preview_response:type_name -> azdext.ProvisioningPreviewResponse
	12, // 11: azdext.ProvisioningMessage.destroy_request:type_name -> azdext.ProvisioningDestroyRequest
	13, // 12: azdext.ProvisioningMessage.destroy_response:type_name -> azdext.ProvisioningDestroyResponse
	14, // 13: azdext.ProvisioningMessage.ensure_env_request:type_name -> azdext.ProvisioningEnsureEnvRequest
	15, // 14: azdext.ProvisioningMessage.ensure_env_response:type_name -> azdext.ProvisioningEnsureEnvResponse
	16, // 15: azdext.ProvisioningMessage.parameters_request:type_name -> azdext.ProvisioningParametersRequest
	17, // 16: azdext.ProvisioningMessage.parameters_response:type_name -> azdext.ProvisioningParametersResponse
	32, // 17: azdext.ProvisioningMessage.progress_message:type_name -> azdext.ProvisioningProgressMessage
	18, // 18: azdext.ProvisioningInitializeRequest.options:type_name -> azdext.ProvisioningOptions
	19, // 19: azdext.ProvisioningStateRequest.options:type_name -> azdext.ProvisioningStateOptions
	20, // 20: azdext.ProvisioningStateResponse.state_result:type_name -> azdext.ProvisioningStateResult
	23, // 21: azdext.ProvisioningDeployResponse.result:type_name -> azdext.ProvisioningDeployResult
	25, // 22: azdext.ProvisioningPreviewResponse.result:type_name -> azdext.ProvisioningPreviewResult
	26, // 23: azdext.ProvisioningDestroyRequest.options:type_name -> azdext.ProvisioningDestroyOptions
	27, // 24: azdext.ProvisioningDestroyResponse.result:type_name -> azdext.ProvisioningDestroyResult
	31, // 25: azdext.ProvisioningParametersResponse.parameters:type_name -> azdext.ProvisioningParameter
	33, // 26: azdext.ProvisioningOptions.deployment_stacks:type_name -> azdext.ProvisioningOptions.DeploymentStacksEntry
	40, // 27: azdext.ProvisioningOptions.config:type_name -> google.protobuf.Struct
	21, // 28: azdext.ProvisioningStateResult.state:type_name -> azdext.ProvisioningState
	34, // 29: azdext.ProvisioningState.outputs:type_name -> azdext.ProvisioningState.OutputsEntry
	30, // 30: azdext.ProvisioningState.resources:type_name -> azdext.ProvisioningResource
	35, // 31: azdext.ProvisioningDeployment.parameters:type_name -> azdext.ProvisioningDeployment.ParametersEntry
	36, // 32: azdext.ProvisioningDeployment.outputs:type_name -> azdext.ProvisioningDeployment.OutputsEntry
	22, // 33: azdext.ProvisioningDeployResult.deployment:type_name -> azdext.ProvisioningDeployment
	0,  // 34: azdext.ProvisioningDeployResult.skipped_reason:type_name -> azdext.ProvisioningSkippedReason
	37, // 35: azdext.ProvisioningDeploymentPreview.parameters:type_name -> azdext.ProvisioningDeploymentPreview.ParametersEntry
	38, // 36: azdext.ProvisioningDeploymentPreview.outputs:type_name -> azdext.ProvisioningDeploymentPreview.OutputsEntry
	24, // 37: azdext.ProvisioningPreviewResult.preview:type_name -> azdext.ProvisioningDeploymentPreview
	29, // 38: azdext.ProvisioningState.OutputsEntry.value:type_name -> azdext.ProvisioningOutputParameter
	28, // 39: azdext.ProvisioningDeployment.ParametersEntry.value:type_name -> azdext.ProvisioningInputParameter
	29, // 40: azdext.ProvisioningDeployment.OutputsEntry.value:type_name -> azdext.ProvisioningOutputParameter
	28, // 41: azdext.ProvisioningDeploymentPreview.ParametersEntry.value:type_name -> azdext.ProvisioningInputParameter
	29, // 42: azdext.ProvisioningDeploymentPreview.OutputsEntry.value:type_name -> azdext.ProvisioningOutputParameter
	1,  // 43: azdext.ProvisioningService.Stream:input_type -> azdext.ProvisioningMessage
	1,  // 44: azdext.ProvisioningService.Stream:output_type -> azdext.ProvisioningMessage
	44, // [44:45] is the sub-list for method output_type
	43, // [43:44] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_provisioning_proto_init() }
func file_provisioning_proto_init() {
	if File_provisioning_proto != nil {
		return
	}
	file_errors_proto_init()
	file_provisioning_proto_msgTypes[0].OneofWrappers = []any{
		(*ProvisioningMessage_RegisterProvisioningProviderRequest)(nil),
		(*ProvisioningMessage_RegisterProvisioningProviderResponse)(nil),
		(*ProvisioningMessage_InitializeRequest)(nil),
		(*ProvisioningMessage_InitializeResponse)(nil),
		(*ProvisioningMessage_StateRequest)(nil),
		(*ProvisioningMessage_StateResponse)(nil),
		(*ProvisioningMessage_DeployRequest)(nil),
		(*ProvisioningMessage_DeployResponse)(nil),
		(*ProvisioningMessage_PreviewRequest)(nil),
		(*ProvisioningMessage_PreviewResponse)(nil),
		(*ProvisioningMessage_DestroyRequest)(nil),
		(*ProvisioningMessage_DestroyResponse)(nil),
		(*ProvisioningMessage_EnsureEnvRequest)(nil),
		(*ProvisioningMessage_EnsureEnvResponse)(nil),
		(*ProvisioningMessage_ParametersRequest)(nil),
		(*ProvisioningMessage_ParametersResponse)(nil),
		(*ProvisioningMessage_ProgressMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provisioning_proto_rawDesc), len(file_provisioning_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provisioning_proto_goTypes,
		DependencyIndexes: file_provisioning_proto_depIdxs,
		EnumInfos:         file_provisioning_proto_enumTypes,
		MessageInfos:      file_provisioning_proto_msgTypes,
	}.Build()
	File_provisioning_proto = out.File
	file_provisioning_proto_goTypes = nil
	file_provisioning_proto_depIdxs = nil
}
