// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package project

import (
	"context"
	"fmt"
	"strings"

	"github.com/azure/azure-dev/cli/azd/pkg/azdext"
)

// DemoProvisionValidationCheck is a sample provider-agnostic validation check.
// Unlike DemoValidationCheck (which relies on the Bicep snapshot), this check
// registers under the "provision" check type and therefore runs before
// provisioning for every provider — including this demo extension's own
// provisioning provider. It demonstrates reading the lean provision context
// (environment, subscription, location, resource group, target scope).
type DemoProvisionValidationCheck struct{}

// NewDemoProvisionValidationCheck creates a new DemoProvisionValidationCheck.
func NewDemoProvisionValidationCheck() *DemoProvisionValidationCheck {
	return &DemoProvisionValidationCheck{}
}

// Validate implements azdext.ValidationCheckProvider.
func (c *DemoProvisionValidationCheck) Validate(
	_ context.Context,
	valCtx *azdext.ValidationContext,
	_ *azdext.ValidationCheckRequest,
) (*azdext.ValidationCheckResponse, error) {
	msg := "This provider-agnostic warning was generated by the demo extension."

	var details []string
	if envName, ok := valCtx.EnvName(); ok && envName != "" {
		details = append(details, fmt.Sprintf("env=%s", envName))
	}
	if location, ok := valCtx.EnvLocation(); ok && location != "" {
		details = append(details, fmt.Sprintf("location=%s", location))
	}
	if scope, ok := valCtx.TargetScope(); ok && scope != "" {
		details = append(details, fmt.Sprintf("scope=%s", scope))
	}
	if len(details) > 0 {
		msg = fmt.Sprintf("%s Provision context: %s.", msg, strings.Join(details, ", "))
	}

	return &azdext.ValidationCheckResponse{
		Results: []*azdext.ValidationCheckResult{
			{
				Severity:     azdext.ValidationCheckSeverity_VALIDATION_CHECK_SEVERITY_WARNING,
				DiagnosticId: "demo_provision_warning",
				Message:      msg,
			},
		},
	}, nil
}
