// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package project

import (
	"testing"

	"github.com/azure/azure-dev/cli/azd/pkg/azdext"
	"github.com/stretchr/testify/require"
)

func TestDemoProvisionValidationCheck_ReturnsWarning(t *testing.T) {
	check := NewDemoProvisionValidationCheck()

	t.Run("empty context", func(t *testing.T) {
		valCtx := &azdext.ValidationContext{
			ContextID: "test-ctx",
			CheckType: azdext.ValidationCheckTypeProvision,
			Data:      map[string][]byte{},
		}
		req := &azdext.ValidationCheckRequest{
			CheckType: azdext.ValidationCheckTypeProvision,
			RuleId:    "demo_provision_warning",
			ContextId: "test-ctx",
		}

		resp, err := check.Validate(t.Context(), valCtx, req)
		require.NoError(t, err)
		require.Len(t, resp.Results, 1)
		require.Equal(t,
			azdext.ValidationCheckSeverity_VALIDATION_CHECK_SEVERITY_WARNING,
			resp.Results[0].Severity,
		)
		require.Equal(t, "demo_provision_warning", resp.Results[0].DiagnosticId)
		require.Equal(t,
			"This provider-agnostic warning was generated by the demo extension.",
			resp.Results[0].Message,
		)
	})

	t.Run("with provision context", func(t *testing.T) {
		valCtx := &azdext.ValidationContext{
			ContextID: "test-ctx-2",
			CheckType: azdext.ValidationCheckTypeProvision,
			Data: map[string][]byte{
				azdext.ValidationContextEnvName:     []byte("my-env"),
				azdext.ValidationContextEnvLocation: []byte("eastus2"),
				azdext.ValidationContextTargetScope: []byte("resourceGroup"),
			},
		}
		req := &azdext.ValidationCheckRequest{
			CheckType: azdext.ValidationCheckTypeProvision,
			RuleId:    "demo_provision_warning",
			ContextId: "test-ctx-2",
		}

		resp, err := check.Validate(t.Context(), valCtx, req)
		require.NoError(t, err)
		require.Len(t, resp.Results, 1)
		require.Contains(t, resp.Results[0].Message, "env=my-env")
		require.Contains(t, resp.Results[0].Message, "location=eastus2")
		require.Contains(t, resp.Results[0].Message, "scope=resourceGroup")
	})
}
