// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package project

import (
	"context"
	"fmt"

	"github.com/azure/azure-dev/cli/azd/pkg/azdext"
)

// DemoValidationCheck is a sample validation check that always returns
// a warning to demonstrate the validation-provider capability.
type DemoValidationCheck struct{}

// NewDemoValidationCheck creates a new DemoValidationCheck.
func NewDemoValidationCheck() *DemoValidationCheck {
	return &DemoValidationCheck{}
}

// Validate implements azdext.ValidationCheckProvider.
func (c *DemoValidationCheck) Validate(
	_ context.Context,
	valCtx *azdext.ValidationContext,
	_ *azdext.ValidationCheckRequest,
) (*azdext.ValidationCheckResponse, error) {
	msg := "This warning was intentional and generated by the demo extension."

	if resources, err := valCtx.ParsePredictedResources(); err == nil && len(resources) > 0 {
		msg = fmt.Sprintf(
			"%s Bicep snapshot contains %d predicted resources.",
			msg, len(resources),
		)
	}

	return &azdext.ValidationCheckResponse{
		Results: []*azdext.ValidationCheckResult{
			{
				Severity:     azdext.ValidationCheckSeverity_VALIDATION_CHECK_SEVERITY_WARNING,
				DiagnosticId: "demo_warning",
				Message:      msg,
			},
		},
	}, nil
}
