// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package project

import (
	"testing"

	"github.com/azure/azure-dev/cli/azd/pkg/azdext"
	"github.com/stretchr/testify/require"
)

func TestDemoValidationCheck_AlwaysReturnsWarning(t *testing.T) {
	check := NewDemoValidationCheck()

	t.Run("no ARM template", func(t *testing.T) {
		valCtx := &azdext.ValidationContext{
			ContextID: "test-ctx",
			CheckType: azdext.ValidationCheckTypeLocalPreflight,
			Data:      map[string][]byte{},
		}
		req := &azdext.ValidationCheckRequest{
			CheckType: azdext.ValidationCheckTypeLocalPreflight,
			RuleId:    "demo_warning",
			ContextId: "test-ctx",
		}

		resp, err := check.Validate(t.Context(), valCtx, req)
		require.NoError(t, err)
		require.Len(t, resp.Results, 1)
		require.Equal(t,
			azdext.ValidationCheckSeverity_VALIDATION_CHECK_SEVERITY_WARNING,
			resp.Results[0].Severity,
		)
		require.Equal(t,
			"This warning was intentional and generated by the demo extension.",
			resp.Results[0].Message,
		)
	})

	t.Run("with predicted resources", func(t *testing.T) {
		resourcesJSON := []byte(`[{"type": "a"}, {"type": "b"}, {"type": "c"}]`)
		valCtx := &azdext.ValidationContext{
			ContextID: "test-ctx-2",
			CheckType: azdext.ValidationCheckTypeLocalPreflight,
			Data: map[string][]byte{
				azdext.ValidationContextPredictedResources: resourcesJSON,
			},
		}
		req := &azdext.ValidationCheckRequest{
			CheckType: azdext.ValidationCheckTypeLocalPreflight,
			RuleId:    "demo_warning",
			ContextId: "test-ctx-2",
		}

		resp, err := check.Validate(t.Context(), valCtx, req)
		require.NoError(t, err)
		require.Len(t, resp.Results, 1)
		require.Contains(t, resp.Results[0].Message, "3 predicted resources")
	})
}
