# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: todo-nodejs-mongo-aks
metadata:
  template: todo-nodejs-mongo-aks@0.0.1-beta
workflows:
  up: 
    steps:
      - azd: provision
      - azd: deploy --all
pipeline:
  variables:
    - AZURE_PRINCIPAL_TYPE
services:
  web:
    project: ../../web/react-fluent
    dist: dist
    language: js
    host: aks
    hooks:
      prebuild:
        windows:
          shell: pwsh
          run: 'echo "VITE_API_BASE_URL=""$env:SERVICE_API_ENDPOINT_URL""" > .env.local ; echo "VITE_APPLICATIONINSIGHTS_CONNECTION_STRING=""$env:APPLICATIONINSIGHTS_CONNECTION_STRING""" >> .env.local'
        posix:
          shell: sh
          run: 'echo VITE_API_BASE_URL=\"$SERVICE_API_ENDPOINT_URL\" > .env.local && echo VITE_APPLICATIONINSIGHTS_CONNECTION_STRING=\"$APPLICATIONINSIGHTS_CONNECTION_STRING\" >> .env.local'
      postbuild:
        windows:
          shell: pwsh
          run: "rm .env.local"
        posix:
          shell: sh
          run: "rm .env.local"
  api:
    project: ../../api/js
    language: js
    host: aks
    k8s:
      ingress:
        relativePath: api