// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package cmd

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"azureaiagent/internal/exterrors"
	"azureaiagent/internal/pkg/agents/agent_api"
	"azureaiagent/internal/pkg/paths"

	"github.com/azure/azure-dev/cli/azd/pkg/azdext"
	"github.com/spf13/cobra"
)

type packFlags struct {
	name        string
	scope       string
	displayName string
	appVersion  string
	outputDir   string
	noPrompt    bool
}

func newPackCommand(extCtx *azdext.ExtensionContext) *cobra.Command {
	flags := &packFlags{}
	extCtx = ensureExtensionContext(extCtx)

	cmd := &cobra.Command{
		Use:   "pack [name]",
		Short: "Build a ready-to-sideload Teams app package for an activity agent.",
		Long: `Build a Teams app package (appPackage.zip) for a deployed Activity (Teams) agent.

The Microsoft 365 service assembles the package (manifest, icons, and a bot entry
bound to the agent's instance identity) from the agent and the Azure Bot created
during 'azd deploy'. The package is written next to the agent source (or to
--output-dir) so you can sideload it in Teams.

This command requires the agent to have been deployed first ('azd deploy'). Unlike
the best-effort packaging done during deploy, any failure here (tenant policy,
permissions, service outage) is reported as a command failure.`,
		Example: `  # Pack the agent resolved from azure.yaml (personal scope)
  azd ai agent pack

  # Pack a specific agent for shareable-link distribution
  azd ai agent pack my-agent --scope shared

  # Pack with a custom display name and output directory
  azd ai agent pack --display-name "Contoso Helper" --output-dir ./dist`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 {
				flags.name = args[0]
			}
			flags.noPrompt = extCtx.NoPrompt

			ctx := azdext.WithAccessToken(cmd.Context())
			action := &PackAction{flags: flags}
			return action.Run(ctx)
		},
	}

	cmd.Flags().StringVar(&flags.scope, "scope", "personal",
		fmt.Sprintf("Publish scope for the package (%s)", joinScopeHelp()))
	cmd.Flags().StringVar(&flags.displayName, "display-name", "",
		"Display name for the Teams app (defaults to the agent name)")
	cmd.Flags().StringVar(&flags.appVersion, "app-version", "1.0.0",
		"Version stamped into the Teams app manifest")
	cmd.Flags().StringVar(&flags.outputDir, "output-dir", "",
		"Directory to write appPackage.zip to (defaults to the agent source directory)")

	return cmd
}

// PackAction implements the agent pack command.
type PackAction struct {
	flags *packFlags
}

func (a *PackAction) Run(ctx context.Context) error {
	scope, err := resolveTeamsPackScope(a.flags.scope)
	if err != nil {
		return err
	}

	azdClient, err := azdext.NewAzdClient()
	if err != nil {
		return fmt.Errorf("failed to create azd client: %w", err)
	}
	defer azdClient.Close()

	packCtx, err := resolveTeamsPackContext(ctx, azdClient, a.flags.name, a.flags.noPrompt)
	if err != nil {
		return err
	}

	displayName := a.flags.displayName
	if displayName == "" {
		displayName = packCtx.agentName
	}

	request := buildTeamsAppPackageRequest(packCtx.botArmID, teamsAppRequestOptions{
		scope:       scope,
		displayName: displayName,
		appVersion:  a.flags.appVersion,
	})

	outputPath, err := a.resolveOutputPath(packCtx)
	if err != nil {
		return err
	}

	fmt.Printf(
		"Packing Teams app %q for agent %q (scope: %s)...\n",
		displayName,
		packCtx.agentName,
		scope.flag,
	)

	zipBytes, err := packCtx.agentClient.DownloadTeamsAppPackage(
		ctx, packCtx.agentName, request, agent_api.Microsoft365APIVersion,
	)
	if err != nil {
		return exterrors.ServiceFromAzure(err, exterrors.OpPackTeamsApp)
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o700); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}
	if err := writeTeamsAppPackOutput(outputPath, zipBytes); err != nil {
		return err
	}

	fmt.Printf("Teams app package written to %s\n", outputPath)
	fmt.Println("Sideload it in Teams (no admin required for personal scope), or run " +
		"'azd ai agent publish' to publish it to the Microsoft 365 store.")
	return nil
}

func writeTeamsAppPackOutput(outputPath string, zipBytes []byte) error {
	markerPath := filepath.Join(filepath.Dir(outputPath), teamsAppPackageMarkerFile)
	written, err := commitTeamsAppPackage(outputPath, markerPath, zipBytes)
	if err != nil {
		return fmt.Errorf("failed to write Teams app package %q: %w", outputPath, err)
	}
	if written == "" {
		return exterrors.Validation(
			exterrors.CodeInvalidFilePath,
			fmt.Sprintf("Teams app package %q already exists and was not generated by azd", outputPath),
			"remove the existing file or choose a different --output-dir",
		)
	}
	return nil
}

// resolveOutputPath returns the absolute path appPackage.zip is written to. When
// --output-dir is set it is joined with the package file name; otherwise the
// package is written next to the agent source, matching the deploy hook's location.
func (a *PackAction) resolveOutputPath(packCtx *teamsPackContext) (string, error) {
	if a.flags.outputDir != "" {
		abs, err := filepath.Abs(filepath.Join(a.flags.outputDir, teamsAppPackageFile))
		if err != nil {
			return "", fmt.Errorf("invalid --output-dir %q: %w", a.flags.outputDir, err)
		}
		return abs, nil
	}
	if hasSharedTeamsArtifactDestination(packCtx.proj, packCtx.svc) {
		return "", exterrors.Validation(
			exterrors.CodeConflictingArguments,
			fmt.Sprintf(
				"agent service %q shares its source directory %q with another agent service",
				packCtx.svc.GetName(),
				packCtx.svc.GetRelativePath(),
			),
			"pass --output-dir <directory> to choose a distinct Teams app package location",
		)
	}
	outputPath, err := paths.JoinAllowRoot(
		packCtx.proj.GetPath(), packCtx.svc.GetRelativePath(), teamsAppPackageFile,
	)
	if err != nil {
		return "", fmt.Errorf("failed to resolve output path: %w", err)
	}
	return outputPath, nil
}

// joinScopeHelp renders the supported scope values with their one-line summaries
// for the --scope flag help text.
func joinScopeHelp() string {
	return joinScopesHelp(teamsPackScopes)
}

func joinScopesHelp(scopes []teamsPackScope) string {
	var out strings.Builder
	for i, scope := range scopes {
		if i > 0 {
			out.WriteString("; ")
		}
		out.WriteString(fmt.Sprintf("%s: %s", scope.flag, scope.summary))
	}
	return out.String()
}
