// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/azure/azure-dev/cli/azd/pkg/azdext"
)

func TestWriteTeamsAppPackOutput_PreservesUnownedPackage(t *testing.T) {
	dir := t.TempDir()
	outputPath := filepath.Join(dir, teamsAppPackageFile)
	if err := os.WriteFile(outputPath, []byte("USER-CUSTOMIZED"), 0o600); err != nil {
		t.Fatal(err)
	}

	err := writeTeamsAppPackOutput(outputPath, []byte("AZD-GENERATED"))
	if err == nil {
		t.Fatal("expected existing unowned package error")
	}
	if !strings.Contains(err.Error(), "already exists and was not generated by azd") {
		t.Fatalf("unexpected error: %v", err)
	}
	data, _ := os.ReadFile(outputPath)
	if string(data) != "USER-CUSTOMIZED" {
		t.Errorf("unowned package was overwritten; content = %q", string(data))
	}
}

func TestWriteTeamsAppPackOutput_OverwritesOwnedPackage(t *testing.T) {
	dir := t.TempDir()
	outputPath := filepath.Join(dir, teamsAppPackageFile)
	markerPath := filepath.Join(dir, teamsAppPackageMarkerFile)
	if err := os.WriteFile(outputPath, []byte("OLD"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(markerPath, []byte(teamsAppPackageMarkerContent([]byte("OLD"))), 0o600); err != nil {
		t.Fatal(err)
	}

	if err := writeTeamsAppPackOutput(outputPath, []byte("NEW")); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	data, _ := os.ReadFile(outputPath)
	if string(data) != "NEW" {
		t.Errorf("owned package should be overwritten; content = %q", string(data))
	}
	if !teamsAppPackageIsOwned(outputPath, markerPath) {
		t.Errorf("marker must be updated for the new package")
	}
}

func TestPackResolveOutputPath_RejectsSharedDefaultDestination(t *testing.T) {
	root := t.TempDir()
	svc := &azdext.ServiceConfig{Name: "agent-a", Host: AiAgentHost, RelativePath: "."}
	proj := &azdext.ProjectConfig{
		Path: root,
		Services: map[string]*azdext.ServiceConfig{
			"agent-a": svc,
			"agent-b": {Name: "agent-b", Host: AiAgentHost, RelativePath: "."},
		},
	}
	action := &PackAction{flags: &packFlags{}}

	_, err := action.resolveOutputPath(&teamsPackContext{proj: proj, svc: svc})

	if err == nil {
		t.Fatal("expected shared default destination error")
	}
	if !strings.Contains(err.Error(), "shares its source directory") {
		t.Fatalf("expected shared source directory error, got %v", err)
	}
}

func TestPackResolveOutputPath_AllowsExplicitOutputDirForSharedSourceDirectory(t *testing.T) {
	root := t.TempDir()
	outputDir := filepath.Join(root, "dist")
	svc := &azdext.ServiceConfig{Name: "agent-a", Host: AiAgentHost, RelativePath: "."}
	proj := &azdext.ProjectConfig{
		Path: root,
		Services: map[string]*azdext.ServiceConfig{
			"agent-a": svc,
			"agent-b": {Name: "agent-b", Host: AiAgentHost, RelativePath: "."},
		},
	}
	action := &PackAction{flags: &packFlags{outputDir: outputDir}}

	got, err := action.resolveOutputPath(&teamsPackContext{proj: proj, svc: svc})

	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := filepath.Join(outputDir, teamsAppPackageFile)
	if got != want {
		t.Errorf("output path = %q, want %q", got, want)
	}
}
