// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package cmd

import (
	"bytes"
	_ "embed"
	"errors"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"text/template"

	"azureaiagent/internal/pkg/paths"

	"github.com/azure/azure-dev/cli/azd/pkg/azdext"
	"github.com/google/uuid"
)

// Generated pack-and-sideload script file names. They are written next to the
// agent source alongside TEAMS_APP_SETUP.md and complete the last manual mile
// (build the Teams app zip + `atk install --scope Personal`) in one command.
const (
	teamsSideloadScriptPwsh = "pack-and-sideload-teams-app.ps1"
	teamsSideloadScriptBash = "pack-and-sideload-teams-app.sh"

	// teamsSideloadTargets is the number of pack+sideload scripts
	// writeTeamsSideloadScripts emits (one per supported shell). The guide and
	// next-steps output advertise all of them by name, so the fast path is only
	// offered when every target was written -- a partial write (e.g. one script
	// collided with a user-owned file) must not advertise a file azd did not
	// generate.
	teamsSideloadTargets = 2

	// teamsSideloadGeneratedMarker is the generic prefix that appears in the
	// header of every azd-generated pack+sideload script and setup guide. The
	// full marker also names the generating agent (see teamsGeneratedMarkerFor),
	// so writeTeamsSideloadScripts / writeTeamsSetupGuide only overwrite a file
	// they generated for the SAME agent: a user-owned file sharing the name, or a
	// file another activity service generated for a different agent (e.g. two
	// services that resolve to one source directory), is left untouched.
	teamsSideloadGeneratedMarker = "Generated by 'azd deploy' (activity protocol)"
)

// teamsGeneratedMarkerFor returns the agent-specific generated marker embedded in
// the scripts and guide azd writes for the given agent. The key MUST be a stable,
// scope-specific identity such as the bot name (service name + subscription/RG
// salt): it stays constant across redeploys and managed-identity recreation,
// unlike the version-scoped msaAppId/instance client id. Keying the marker on a
// stable value lets postdeploy recognize its own prior output (safe to refresh)
// and leave a different agent's output that shares the source directory untouched
// (must not be clobbered -- only the last writer's package would install).
func teamsGeneratedMarkerFor(stableKey string) string {
	return teamsSideloadGeneratedMarker + " for bot " + stableKey
}

// canWriteGeneratedFile reports whether path may be (over)written with a file
// azd generated for stableKey. It is true when the path is absent or is a regular
// file already generated for the SAME stable key (an idempotent refresh). It is
// false -- with a log-ready reason -- for a non-regular file (symlink, FIFO,
// device, directory), a user-owned file, or a file generated for a DIFFERENT
// agent, so none of those is silently clobbered.
func canWriteGeneratedFile(path, stableKey string) (bool, string) {
	info, err := os.Lstat(path)
	if err != nil {
		// Absent, or the stat itself failed: attempt the write; WriteFile logs
		// any failure.
		return true, ""
	}
	if !info.Mode().IsRegular() {
		return false, "is not a regular file; leaving it untouched (rename it to get the generated file)"
	}
	existing, readErr := os.ReadFile(path)
	if readErr != nil {
		return false, "could not be read to verify its origin; leaving it untouched"
	}
	if strings.Contains(string(existing), teamsGeneratedMarkerFor(stableKey)) {
		return true, ""
	}
	if strings.Contains(string(existing), teamsSideloadGeneratedMarker) {
		return false, "was generated for a different agent (another activity service shares this " +
			"source directory); leaving it untouched"
	}
	return false, "already exists and was not generated by azd; leaving it untouched " +
		"(rename it to get the generated file)"
}

// writeOwnedGeneratedFile writes content to path with mode, but only when azd may
// own the path. It atomically claims a brand-new path (O_CREATE|O_EXCL, so under
// a parallel service-deploy graph only one concurrent postdeploy wins the create
// and the losers fall through to the ownership check), and for an existing path
// it refreshes in place only when the file is a regular file this same stableKey
// generated -- replacing it atomically via a temp file + rename so a reader never
// sees a partial file and a pre-existing symlink is replaced rather than followed.
// isLegacy, when non-nil, lets the caller additionally adopt a pre-marker
// generated file it recognizes (e.g. a guide from a released version). It returns
// written=true only when the file now holds content; otherwise reason explains
// why it was left untouched ("" means the caller should stay silent).
func writeOwnedGeneratedFile(
	path, content string, mode os.FileMode, stableKey string, isLegacy func(string) bool,
) (bool, string) {
	// Fast path: atomically create a new file. O_EXCL guarantees exactly one
	// concurrent writer wins the create; everyone else gets ErrExist below.
	if f, err := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY, mode); err == nil {
		_, writeErr := f.WriteString(content)
		closeErr := f.Close()
		if joined := errors.Join(writeErr, closeErr); joined != nil {
			return false, fmt.Sprintf("could not be written: %v", joined)
		}
		// os.OpenFile applies mode subject to umask, so re-assert it (the bash
		// script must stay executable).
		if err := os.Chmod(path, mode); err != nil {
			return false, fmt.Sprintf("could not be made executable: %v", err)
		}
		return true, ""
	} else if !errors.Is(err, os.ErrExist) {
		return false, fmt.Sprintf("could not be created: %v", err)
	}

	// The path already exists: only replace it if we own it (same stable key) or
	// it is a recognized legacy generated file. Never touch a user file, a
	// different agent's file, or a non-regular file.
	if ok, reason := canWriteGeneratedFile(path, stableKey); !ok {
		if isLegacy == nil || !isLegacy(path) {
			return false, reason
		}
	}
	if err := replaceFileAtomic(path, content, mode); err != nil {
		return false, fmt.Sprintf("could not be replaced: %v", err)
	}
	return true, ""
}

// replaceFileAtomic writes content to a temp file in path's directory and renames
// it over path. The rename is atomic and replaces the destination on both Unix
// and Windows, so a reader never observes a partial file and a symlink at path is
// replaced rather than having its target truncated.
func replaceFileAtomic(path, content string, mode os.FileMode) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".azd-teams-*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	// Best-effort cleanup; a no-op once the rename below succeeds.
	defer func() { _ = os.Remove(tmpName) }()
	if _, err := tmp.WriteString(content); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmpName, mode); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

//go:embed assets/teams_pack_sideload.ps1
var teamsSideloadPwshMarkup string

//go:embed assets/teams_pack_sideload.sh
var teamsSideloadBashMarkup string

// Keeping the scripts as real .ps1/.sh files (assets/) lets editors lint them and
// catches syntax errors a Go string literal would hide.
var (
	teamsSideloadPwshTmpl = template.Must(
		template.New("teamsSideloadPwsh").Parse(teamsSideloadPwshMarkup),
	)
	teamsSideloadBashTmpl = template.Must(
		template.New("teamsSideloadBash").Parse(teamsSideloadBashMarkup),
	)
)

// teamsAppIDNamespace is a fixed namespace used to derive a Teams app id from a
// stable, scope-specific bot key. Using a deterministic UUIDv5 keeps the Teams
// app identity stable across re-runs and re-deploys, so `atk install` updates the
// same app instead of piling up duplicate entries in the user's app list.
var teamsAppIDNamespace = uuid.MustParse("6ba7b811-9dad-11d1-80b4-00c04fd430c8")

// deterministicTeamsAppID derives a stable Teams app id (distinct from the bot
// id) from a stable, scope-specific key. The key MUST NOT be the version-scoped
// msaAppId/instance client id: that changes when a new agent version deploys (or
// the managed identity is recreated), which would mint a new Teams app id and
// pile up duplicate Teams apps instead of updating the installed one. The bot
// name (service name + subscription/RG salt) is stable, so callers pass that;
// the current msaAppId is used only for the manifest's bots[].botId.
func deterministicTeamsAppID(stableKey string) string {
	return uuid.NewSHA1(teamsAppIDNamespace, []byte("foundry-teams-app:"+stableKey)).String()
}

// teamsColorIconB64 is a 192x192 solid-color PNG and teamsOutlineIconB64 is a
// 32x32 transparent outline PNG, embedded as base64 so the generated scripts can
// write valid Teams icons with no image tooling on any OS. Replace with your own
// branding by editing the generated script or the produced color.png/outline.png.
// cspell:disable
const (
	// teamsColorIconB64 and teamsOutlineIconB64 are split into short concatenated
	// literals only to satisfy the lll line-length linter (each source line stays
	// well under 125 chars); concatenation yields the exact original base64 for
	// each PNG.
	teamsColorIconB64 = "" +
		"iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAABiUlEQVR42u3TMQ0AAAjAMHxyIBdZYIKPHjWwZJHVA1" +
		"+FCBgADAAGAAOAAcAAYAAwABgADAAGAAOAAcAAYAAwABgADAAGAAOAAcAAYAAwABgADAAGAAOAAcAAYAAwABgADAAG" +
		"AAOAAcAAYAAwABgADAAGAAOAAcAAYAAwABgADAAGwAAiYAAwABgADAAGAAOAAcAAYAAwABgADAAGAAOAAcAAYAAwAB" +
		"gADAAGAAOAAcAAYAAwABgADAAGAAOAAcAAYAAwABgADAAGAAOAAcAAYAAwABgADAAGAAOAAcAAYAAwABgAA4ABwABg" +
		"ADAAGAAMAAYAA4ABwABgADAAGAAMAAYAA4ABwABgADAAGAAMAAYAA4ABwABgADAAGAAMAAYAA4ABwABgADAAGAAMAA" +
		"YAA4ABwABgADAAGAAMAAYAA4ABwAAYQAQMAAYAA4ABwABgADAAGAAMAAYAA4ABwABgADAAGAAMAAYAA4ABwABgADAA" +
		"GAAMAAYAA4ABwABgADAAGAAMAAYAA8ClBeSCFRle66JBAAAAAElFTkSuQmCC"
	teamsOutlineIconB64 = "" +
		"iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAaklEQVR42u1XQQ4AIAjq/5+2D7RlJoKbnBPJpdJag2" +
		"6wC2iJYULsE5DkWeefk1fEHgmyKhgKzHxDpbcP8yFayc2J6mU3L3KijYAR0E8ApQ3pg0hiFNOXkcQ6phsSCUsmYUol" +
		"bLnMx2SAwgZ903yusz4vOQAAAABJRU5ErkJggg=="
)

// cspell:enable

// teamsSideloadData is the template model shared by the pwsh and bash scripts.
type teamsSideloadData struct {
	AgentName     string
	BotName       string
	MsaAppID      string
	TeamsAppId    string
	ColorPngB64   string
	OutlinePngB64 string
}

// teamsSideloadScriptContent renders one pack-and-sideload script from the given
// template with the azd-controlled ids baked in.
func teamsSideloadScriptContent(
	tmpl *template.Template, agentName, botName, msaAppID string,
) string {
	var buf bytes.Buffer
	// Inputs are azd-controlled resource names/ids and the templates are
	// compile-time embedded, so execution cannot realistically fail.
	_ = tmpl.Execute(&buf, teamsSideloadData{
		AgentName:     agentName,
		BotName:       botName,
		MsaAppID:      msaAppID,
		TeamsAppId:    deterministicTeamsAppID(botName),
		ColorPngB64:   teamsColorIconB64,
		OutlinePngB64: teamsOutlineIconB64,
	})
	return buf.String()
}

// writeTeamsSideloadScripts writes runnable pwsh + bash pack-and-sideload scripts
// next to the agent source so the user can finish the last manual mile (package
// the Teams app + sideload it for themselves) in one command. It returns the
// paths written. Best-effort: any script that fails to write is skipped and
// logged, and this never blocks or fails the deploy. All ids are baked in from
// the deploy, so the generated scripts make no Azure calls.
func writeTeamsSideloadScripts(
	proj *azdext.ProjectConfig, svc *azdext.ServiceConfig, agentName, botName, msaAppID string,
) []string {
	scripts := []struct {
		file string
		tmpl *template.Template
		mode os.FileMode
	}{
		{teamsSideloadScriptPwsh, teamsSideloadPwshTmpl, 0o600},
		{teamsSideloadScriptBash, teamsSideloadBashTmpl, 0o700},
	}

	var written []string
	for _, s := range scripts {
		scriptPath, err := paths.JoinAllowRoot(proj.GetPath(), svc.GetRelativePath(), s.file)
		if err != nil {
			log.Printf("postdeploy: skipping Teams sideload script %q: %v", s.file, err)
			continue
		}
		content := teamsSideloadScriptContent(s.tmpl, agentName, botName, msaAppID)

		// Atomically claim/refresh the path keyed on the STABLE bot name (never
		// the version-scoped msaAppId): a user-owned file, a different agent's
		// script sharing this source directory, or a non-regular file is left
		// untouched, and concurrent service deploys cannot clobber each other.
		if ok, reason := writeOwnedGeneratedFile(scriptPath, content, s.mode, botName, nil); !ok {
			if reason != "" {
				log.Printf("postdeploy: Teams sideload script %q %s", scriptPath, reason)
			}
			continue
		}
		written = append(written, scriptPath)
	}
	return written
}

// preferredSideloadScript returns the generated script that matches the current
// OS (the .ps1 on Windows, the .sh elsewhere), or "" if no matching script was
// written. It deliberately does not fall back to the other platform's script:
// running a .ps1 on Linux/macOS or a .sh on Windows would emit the wrong shell
// syntax, so the caller shows the guide/manual fallback instead.
func preferredSideloadScript(scriptPaths []string) string {
	wantPwsh := runtime.GOOS == "windows"
	for _, p := range scriptPaths {
		isPwsh := strings.HasSuffix(p, ".ps1")
		if isPwsh == wantPwsh {
			return p
		}
	}
	return ""
}

// sideloadRunCommand returns a shell-safe invocation of the generated script for
// a user-facing hint. The path is single-quote quoted for the target shell so a
// path containing spaces or metacharacters ($, backticks, quotes) is neither
// expanded nor able to break out of the argument when pasted. The pwsh call
// operator (&) is required to run a quoted .ps1 path, while .sh is run via bash.
// See cli/azd/AGENTS.md ("Shell-safe output" / "Path Safety").
func sideloadRunCommand(scriptPath string) string {
	if strings.HasSuffix(scriptPath, ".ps1") {
		// PowerShell single-quoted literal: an embedded ' is escaped by doubling.
		return "& '" + strings.ReplaceAll(scriptPath, "'", "''") + "'"
	}
	// POSIX single-quoted literal: close the quote, add an escaped ', reopen.
	return "bash '" + strings.ReplaceAll(scriptPath, "'", `'\''`) + "'"
}
