// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package cmd

import (
	"context"
	"fmt"
	"sync"

	"github.com/azure/azure-dev/cli/azd/pkg/azdext"
	"github.com/fatih/color"
	"github.com/spf13/cobra"
)

func newUpCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "up",
		Short: "Runs azd up in concurrent mode",
		RunE: func(cmd *cobra.Command, args []string) error {
			// Create a new context that includes the AZD access token
			ctx := azdext.WithAccessToken(cmd.Context())

			// Create a new AZD client
			azdClient, err := azdext.NewAzdClient()
			if err != nil {
				return fmt.Errorf("failed to create azd client: %w", err)
			}

			defer azdClient.Close()

			// Get the original project configuration (services as defined in azure.yaml)
			projectClient := azdClient.Project()

			// Get the resolved services (includes services generated by importers like Aspire)
			resolvedResp, err := projectClient.GetResolvedServices(ctx, &azdext.EmptyRequest{})
			if err != nil {
				return fmt.Errorf("failed to get resolved services: %w", err)
			}

			services := resolvedResp.GetServices()
			fmt.Printf("\nResolved services after import processing (%d):\n", len(services))
			for name, svc := range services {
				fmt.Printf("  - %s (host: %s, language: %s)\n", name, svc.Host, svc.Language)
			}

			// Get the workflow client
			workflowClient := azdClient.Workflow()

			// Step 1: Run package
			color.New(color.FgCyan, color.Bold).Println("\n==> Running package...")
			_, err = workflowClient.Run(ctx, &azdext.RunWorkflowRequest{
				Workflow: &azdext.Workflow{
					Name: "package",
					Steps: []*azdext.WorkflowStep{
						{
							Command: &azdext.WorkflowCommand{
								Args: []string{"package"},
							},
						},
					},
				},
			})
			if err != nil {
				return fmt.Errorf("failed to run package: %w", err)
			}
			fmt.Println("Package completed")

			// Step 2: Run provision
			color.New(color.FgCyan, color.Bold).Println("\n==> Running provision...")
			_, err = workflowClient.Run(ctx, &azdext.RunWorkflowRequest{
				Workflow: &azdext.Workflow{
					Name: "provision",
					Steps: []*azdext.WorkflowStep{
						{
							Command: &azdext.WorkflowCommand{
								Args: []string{"provision"},
							},
						},
					},
				},
			})
			if err != nil {
				return fmt.Errorf("failed to run provision: %w", err)
			}
			fmt.Println("Provision completed")

			// Step 3: Run deploy concurrently for each service
			color.New(color.FgCyan, color.Bold).Printf("\n==> Deploying %d services concurrently...\n", len(services))

			var wg sync.WaitGroup
			errChan := make(chan error, len(services))

			for serviceName := range services {
				wg.Add(1)
				go func(svcName string) {
					defer wg.Done()

					// Create a new independent context for each deployment
					// This prevents context cancellation from affecting other concurrent deployments
					deployCtx := azdext.WithAccessToken(context.Background())

					color.New(color.FgYellow).Printf("  [%s] Starting deployment...\n", svcName)

					_, err := workflowClient.Run(deployCtx, &azdext.RunWorkflowRequest{
						Workflow: &azdext.Workflow{
							Name: fmt.Sprintf("deploy-%s", svcName),
							Steps: []*azdext.WorkflowStep{
								{
									Command: &azdext.WorkflowCommand{
										Args: []string{"deploy", svcName},
									},
								},
							},
						},
					})

					if err != nil {
						color.New(color.FgRed).Printf("  [%s] Deployment failed: %v\n", svcName, err)
						errChan <- fmt.Errorf("failed to deploy service %s: %w", svcName, err)
						return
					}

					color.New(color.FgGreen).Printf("  [%s] Deployment completed successfully!\n", svcName)
				}(serviceName)
			} // Wait for all deployments to complete
			wg.Wait()
			close(errChan)

			// Check for any errors
			var deployErrors []error
			for err := range errChan {
				deployErrors = append(deployErrors, err)
			}

			if len(deployErrors) > 0 {
				color.New(color.FgRed, color.Bold).Println("\n==> Deployment completed with errors:")
				for _, err := range deployErrors {
					fmt.Printf("  - %v\n", err)
				}
				return fmt.Errorf("%d service(s) failed to deploy", len(deployErrors))
			}

			color.New(color.FgGreen, color.Bold).Println("\n==> All services deployed successfully!")
			return nil
		},
	}
}
