// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package cmd

import (
	"fmt"

	"github.com/azure/azure-dev/cli/azd/pkg/azdext"
	"github.com/spf13/cobra"
)

func newUpCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "up",
		Short: "Runs azd up in concurrent mode",
		RunE: func(cmd *cobra.Command, args []string) error {
			// Create a new context that includes the AZD access token
			ctx := azdext.WithAccessToken(cmd.Context())

			// Create a new AZD client
			azdClient, err := azdext.NewAzdClient()
			if err != nil {
				return fmt.Errorf("failed to create azd client: %w", err)
			}

			defer azdClient.Close()

			// Get the original project configuration (services as defined in azure.yaml)
			projectResp, err := azdClient.Project().Get(ctx, &azdext.EmptyRequest{})
			if err != nil {
				return fmt.Errorf("failed to get project: %w", err)
			}

			fmt.Printf("Project: %s\n", projectResp.GetProject().Name)
			fmt.Printf("\nServices from azure.yaml (%d):\n", len(projectResp.GetProject().Services))
			for name := range projectResp.GetProject().Services {
				fmt.Printf("  - %s\n", name)
			}

			// Get the resolved services (includes services generated by importers like Aspire)
			resolvedResp, err := azdClient.Project().GetResolvedServices(ctx, &azdext.EmptyRequest{})
			if err != nil {
				return fmt.Errorf("failed to get resolved services: %w", err)
			}

			fmt.Printf("\nResolved services after import processing (%d):\n", len(resolvedResp.GetServices()))
			for name, svc := range resolvedResp.GetServices() {
				fmt.Printf("  - %s (host: %s, language: %s)\n", name, svc.Host, svc.Language)
			}

			return nil
		},
	}
}
