// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// generatefacade creates the azdext stable-contract forwarding surface.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

const stableDescriptorPrefix = "File_azd_extensions_v1_"

type alias struct {
	name   string
	target string
}

type function struct {
	name       string
	signature  *ast.FuncType
	parameters []string
}

func main() {
	source := flag.String("source", "", "directory containing the stable generated contracts")
	output := flag.String("output", "", "path for the generated facade file")
	flag.Parse()

	if *source == "" || *output == "" {
		fmt.Fprintln(os.Stderr, "-source and -output are required")
		os.Exit(2)
	}

	if err := generate(*source, *output); err != nil {
		fmt.Fprintf(os.Stderr, "generate facade: %v\n", err)
		os.Exit(1)
	}
}

func generate(source, output string) error {
	entries, err := os.ReadDir(source)
	if err != nil {
		return fmt.Errorf("read source directory: %w", err)
	}

	var (
		types     []alias
		constants []alias
		variables []alias
		functions []function
	)

	files := make([]string, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".pb.go") {
			files = append(files, filepath.Join(source, entry.Name()))
		}
	}
	slices.Sort(files)

	fileSet := token.NewFileSet()
	for _, file := range files {
		parsed, err := parser.ParseFile(fileSet, file, nil, 0)
		if err != nil {
			return fmt.Errorf("parse %s: %w", file, err)
		}

		for _, declaration := range parsed.Decls {
			switch declaration := declaration.(type) {
			case *ast.GenDecl:
				for _, specification := range declaration.Specs {
					switch specification := specification.(type) {
					case *ast.TypeSpec:
						if specification.Name.IsExported() {
							types = append(types, alias{
								name:   specification.Name.Name,
								target: specification.Name.Name,
							})
						}
					case *ast.ValueSpec:
						for _, name := range specification.Names {
							if !name.IsExported() {
								continue
							}

							facadeName := name.Name
							if after, ok := strings.CutPrefix(facadeName, stableDescriptorPrefix); ok {
								facadeName = "File_" + after
							}
							item := alias{name: facadeName, target: name.Name}
							if declaration.Tok == token.CONST {
								constants = append(constants, item)
							} else if declaration.Tok == token.VAR {
								variables = append(variables, item)
							}
						}
					}
				}
			case *ast.FuncDecl:
				if declaration.Recv == nil && declaration.Name.IsExported() {
					parameters, err := parameterNames(declaration.Type.Params)
					if err != nil {
						return fmt.Errorf("%s: %w", declaration.Name.Name, err)
					}
					functions = append(functions, function{
						name:       declaration.Name.Name,
						signature:  declaration.Type,
						parameters: parameters,
					})
				}
			}
		}
	}

	sortAliases(types)
	sortAliases(constants)
	sortAliases(variables)
	slices.SortFunc(functions, func(a, b function) int {
		return strings.Compare(a.name, b.name)
	})

	var generated bytes.Buffer
	generated.WriteString(`// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by grpc/generatefacade. DO NOT EDIT.

package azdext

import (
	v1 "github.com/azure/azure-dev/cli/azd/pkg/azdext/contracts/v1"
	"google.golang.org/grpc"
)

`)
	writeAliasGroup(&generated, "const", constants)
	writeAliasGroup(&generated, "type", types)
	writeVariableGroup(&generated, variables)

	for _, function := range functions {
		var signature bytes.Buffer
		if err := format.Node(&signature, fileSet, function.signature); err != nil {
			return fmt.Errorf("format signature for %s: %w", function.name, err)
		}

		fmt.Fprintf(&generated, "func %s%s {\n\t", function.name, strings.TrimPrefix(signature.String(), "func"))
		if function.signature.Results != nil && len(function.signature.Results.List) > 0 {
			generated.WriteString("return ")
		}
		fmt.Fprintf(&generated, "v1.%s(%s)\n}\n\n", function.name, strings.Join(function.parameters, ", "))
	}

	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		return fmt.Errorf("format generated facade: %w", err)
	}
	//nolint:gosec // Generated Go sources must retain normal repository-readable permissions.
	if err := os.WriteFile(output, formatted, 0o644); err != nil {
		return fmt.Errorf("write output: %w", err)
	}

	return nil
}

func parameterNames(fields *ast.FieldList) ([]string, error) {
	if fields == nil {
		return nil, nil
	}

	var names []string
	for _, field := range fields.List {
		if len(field.Names) == 0 {
			return nil, fmt.Errorf("unnamed generated parameter")
		}
		for _, name := range field.Names {
			parameter := name.Name
			if _, ok := field.Type.(*ast.Ellipsis); ok {
				parameter += "..."
			}
			names = append(names, parameter)
		}
	}
	return names, nil
}

func sortAliases(items []alias) {
	slices.SortFunc(items, func(a, b alias) int {
		return strings.Compare(a.name, b.name)
	})
}

func writeAliasGroup(output *bytes.Buffer, keyword string, items []alias) {
	if len(items) == 0 {
		return
	}

	fmt.Fprintf(output, "%s (\n", keyword)
	for _, item := range items {
		fmt.Fprintf(output, "\t%s = v1.%s\n", item.name, item.target)
	}
	output.WriteString(")\n\n")
}

func writeVariableGroup(output *bytes.Buffer, items []alias) {
	if len(items) == 0 {
		return
	}

	output.WriteString("var (\n")
	for _, item := range items {
		fmt.Fprintf(output, "\t%s = v1.%s\n", item.name, item.target)
	}
	output.WriteString(")\n\n")
}
