ARG prefix=''
ARG base='alpine:3.15'
FROM ${prefix}${base}

ARG shell="bash"
ARG baseUrl='must set baseUrl'
ARG version='must set version'

RUN apk add curl libc6-compat tar bash

COPY ./*.sh ./
COPY test/telemetry/alpine.sh.telemetry.csv /telemetry.csv

ENV SHELL="${shell}"
ENV BASE_URL="${baseUrl}"
ENV VERSION="${version}"

ENTRYPOINT ./test-sh-install.sh $SHELL $BASE_URL $VERSION && ./test-telemetry-functions.sh
