ARG base='alpine:3.15'
FROM ${base}

ARG shell='sh'
ARG baseUrl='must set baseUrl'
ARG version='must set version'

RUN apk add curl libc6-compat tar

COPY ./*.sh ./
RUN cat install-azd.sh \
    | ${shell} -s -- --verbose --base-url "$baseUrl" --version "$version"  \
    && azd --help \
    && cat uninstall-azd.sh | ${shell}
