ARG prefix=''
ARG base='ubuntu:20.04'
FROM ${prefix}${base}

ARG shell='bash'
ARG baseUrl='must set baseUrl'
ARG version='must set version'

# pwsh install instructions from
# https://docs.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.2

RUN apt-get update \
    && apt-get install -y wget apt-transport-https software-properties-common \
    && wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb" \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y powershell

# Invoke-RestMethod uses curl and is required by the installer
RUN apt-get install -y curl

COPY ./test-pwsh-xplat-install.ps1 /test-pwsh-xplat-install.ps1
COPY ./*stall-azd.ps1 /

# Validate telemetry behavior by simulating an error
COPY ./test-telemetry-functions.ps1 /
COPY test/telemetry/ubuntu.pwsh.telemetry.json /telemetry.json

ENV BASE_URL="${baseUrl}"
ENV VERSION="${version}"

ENTRYPOINT pwsh -NonInteractive -c "\$ProgressPreference = 'SilentlyContinue'; /test-pwsh-xplat-install.ps1 -BaseUrl \$env:BASE_URL -Version \$env:VERSION && /test-telemetry-functions.ps1"
