ARG base='ubuntu:20.04'
FROM ${base}

ARG shell='bash'
ARG baseUrl='must set baseUrl'
ARG version='must set version'

RUN apt update && apt install -y curl

COPY ./*.sh ./
RUN ./test-sh-install.sh "${shell}" "${baseUrl}" "${version}"
