ARG base='alpine:3.15'
FROM ${base}

ARG shell="bash"
ARG baseUrl='must set baseUrl'
ARG version='must set version'

RUN apk add curl libc6-compat tar bash

COPY ./*.sh ./
RUN ./test-sh-install.sh "${shell}" "${baseUrl}" "${version}"
