ARG prefix=''
ARG base='ubuntu:20.04'
FROM ${prefix}${base}

ARG shell='bash'
ARG baseUrl='must set baseUrl'
ARG version='must set version'

RUN apt update && apt install -y curl

COPY ./*.sh ./
COPY test/telemetry/ubuntu.sh.telemetry.csv /telemetry.csv

ENV SHELL="${shell}"
ENV BASE_URL="${baseUrl}"
ENV VERSION="${version}"

ENTRYPOINT ./test-sh-install.sh $SHELL $BASE_URL $VERSION \
    && ./test-telemetry-functions.sh \
    && ./test-sh-install-errors.sh $SHELL $BASEURL $VERSION
