name: Feature Request
description: Suggest an idea or enhancement for Azure Developer CLI
title: "[Feature Request]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible.
        
        Before submitting, please:
        - Search existing issues and discussions to see if this has already been suggested
        - Check the [documentation](https://learn.microsoft.com/azure/developer/azure-developer-cli/) to ensure this feature doesn't already exist
  
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: false
  
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: What would you like to see?
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Have you found any workarounds?
    validations:
      required: false
  
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe the use case or scenario where this feature would be helpful. Real-world examples are very valuable!
      placeholder: |
        In my project, I need to...
        This would help me because...
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request here.
    validations:
      required: false
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow this project's Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
