# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: Todo-java-postgresql-terraform
version: 1.0.0
summary: Azure Todo Java APP Environment
description: Deploys an Azure Web App
runner: ARM
templatePath: azuredeploy.json

parameters:
  - id: environmentName
    name: environmentName
    required: true
    type: string
    description: Name of the environment
  - id: sqlAdminPassword
    name: sqlAdminPassword
    description: 'sqlAdminPassword'
    type: string
    required: true
  - id: appUserPassword
    name: appUserPassword
    description: 'appUserPassword'
    type: string
    required: true