pr:
  branches:
    include: [main]

  paths:
    include:
      - eng/pipelines/build-notice.yml

trigger:
  branches:
    include: [main]

extends:
  template: /eng/pipelines/templates/stages/1es-redirect.yml
  parameters:
    stages:
      - template: /eng/pipelines/templates/stages/notice-build-and-test.yml
