# Continuous deployment trigger
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - go.mod
      - cli/azd/extensions/
      - eng/pipelines/release-azd-extension.yml
      - /eng/pipelines/templates/jobs/build-azd-extension.yml
      - /eng/pipelines/templates/jobs/cross-build-azd-extension.yml
      - /eng/pipelines/templates/variables/image.yml

pr:
  paths:
    include:
      - go.mod
      - cli/azd/extensions/
      - eng/pipelines/release-azd-extension.yml
      - eng/pipelines/templates/steps/publish-cli.yml
    exclude:
      - cli/azd/docs/**

parameters:
  - name: AzdExtensionId
    type: string
  - name: AzdExtensionDirectory
    type: string

variables:
  - name: sanitizedExtensionId
    value: ${{ replace(parameters.AzdExtensionId, '.', '-') }}

extends:
  template: /eng/pipelines/templates/stages/1es-redirect.yml
  parameters:
    stages:
      - template: /eng/pipelines/templates/stages/build-and-test-azd-extension.yml
        parameters:
          BuildMatrix:
            Windows:
              Pool: $(WINDOWSPOOL)
              OSVmImage: $(WINDOWSVMIMAGE)
              OS: windows
              ImageKey: image
              UploadArtifact: true
              Variables:
                BuildTarget: ${{ variables.sanitizedExtensionId }}-windows-amd64.exe
                BuildOutputName: ${{ variables.sanitizedExtensionId }}-windows-amd64.exe
                BuildTestMsi: true
                AZURE_DEV_CI_OS: win
                Codeql.Enabled: true
                Codeql.SkipTaskAutoInjection: false
                Codeql.BuildIdentifier: cli_windows
            Linux:
              Pool: $(LINUXPOOL)
              OSVmImage: $(LINUXVMIMAGE)
              OS: linux
              ImageKey: image
              UploadArtifact: true
              Variables:
                BuildTarget: ${{ variables.sanitizedExtensionId }}-linux-amd64
                BuildOutputName: ${{ variables.sanitizedExtensionId }}-linux-amd64
                SetExecutableBit: true
                SetShieldInfo: true
                BuildLinuxPackages: true
                AZURE_DEV_CI_OS: lin
                Codeql.Enabled: true
                Codeql.SkipTaskAutoInjection: false
                Codeql.BuildIdentifier: cli_linux
            Mac:
              Pool: Azure Pipelines
              OSVmImage: $(MACVMIMAGE)
              OS: macOS
              ImageKey: vmImage
              UploadArtifact: true
              Variables:
                BuildTarget: ${{ variables.sanitizedExtensionId }}-darwin-amd64
                BuildOutputName: ${{ variables.sanitizedExtensionId }}-darwin-amd64
                MacLocalSign: false
                SetExecutableBit: true
                AZURE_DEV_CI_OS: mac
                # CodeQL on macOS not supported by the Azure DevOps task as-of current.
                # Codeql.BuildIdentifier: cli_darwin

            ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
              # Only run this build during scheduled pipeline executions
              MacAppleSilicon:
                Pool: Azure Pipelines
                OSVmImage: $(MACVMIMAGEM1)
                OS: macOS
                ImageKey: vmImage
                UploadArtifact: false
                Variables:
                  BuildTarget: ${{ variables.sanitizedExtensionId }}-darwin-amd64
                  BuildOutputName: ${{ variables.sanitizedExtensionId }}-darwin-amd64
                  MacLocalSign: false
                  SetExecutableBit: true
                  AZURE_DEV_CI_OS: mac-arm64
          CrossBuildMatrix:
            # Compliant image name required
            LinuxARM64:
              Pool: $(LINUXPOOL)
              OSVmImage: $(LINUXVMIMAGE)
              OS: linux
              ImageKey: image
              ValidateCrossCompile: true
              ValidateVm:
                PoolName: $(ARMPOOL)
                ImageName: $(LINUXARMVMIMAGE)
                Os: linux
              ValidationTask: bash
              ValidationScript: pwd && ls && chmod +x ./azd-linux-arm64 && ./azd-linux-arm64 version
              Variables:
                BuildTarget: ${{ variables.sanitizedExtensionId }}-linux-arm64
                BuildOutputName: ${{ variables.sanitizedExtensionId }}-linux-arm64
                SetExecutableBit: true
                GOOS: linux
                GOARCH: arm64
                BuildLinuxPackages: true
            MacARM64:
              Pool: Azure Pipelines
              OSVmImage: $(MACVMIMAGE)
              OS: macOS
              ImageKey: vmImage
              Variables:
                BuildTarget: ${{ variables.sanitizedExtensionId }}-darwin-arm64
                BuildOutputName: ${{ variables.sanitizedExtensionId }}-darwin-arm64
                SetExecutableBit: true
                GOOS: darwin
                GOARCH: arm64
                # CGO_ENABLED is required on MacOS to cross-compile pkg/outil/osversion
                CGO_ENABLED: 1
            WindowsARM64:
              Pool: $(WINDOWSPOOL)
              OSVmImage: $(WINDOWSVMIMAGE)
              OS: windows
              ImageKey: image
              ValidateCrossCompile: true
              ValidateVm:
                PoolName: $(ARMPOOL)
                ImageName: $(WINDOWSARMVMIMAGE)
                Os: windows
              ValidationTask: script
              ValidationScript: |
                dir
                azd-windows-arm64.exe version
              Variables:
                BuildTarget: ${{ variables.sanitizedExtensionId }}-windows-arm64.exe
                BuildOutputName: ${{ variables.sanitizedExtensionId }}-windows-arm64.exe
                GOOS: windows
                GOARCH: arm64

      - template: /eng/pipelines/templates/stages/code-coverage-upload.yml
        parameters:
          DownloadArtifacts:
            - cover-win
            - cover-lin
            - cover-mac
            - ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
                - cover-mac-arm64

      # - ${{ if ne(variables['Build.Reason'], 'Schedule') }}:
      #     - template: /eng/pipelines/templates/stages/sign.yml

      #     - template: /eng/pipelines/templates/stages/publish.yml
