# Continuous deployment trigger
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - go.mod
      - cli/azd/extensions/azure.appservice
      - eng/pipelines/release-azd-extension.yml
      - /eng/pipelines/templates/jobs/build-azd-extension.yml
      - /eng/pipelines/templates/jobs/cross-build-azd-extension.yml
      - /eng/pipelines/templates/variables/image.yml

pr:
  paths:
    include:
      - cli/azd/extensions/azure.appservice
      - eng/pipelines/release-ext-azure-appservice.yml
      - eng/pipelines/release-azd-extension.yml
      - eng/pipelines/templates/steps/publish-cli.yml
    exclude:
      - cli/azd/docs/**

extends:
  template: /eng/pipelines/templates/stages/1es-redirect.yml
  parameters:
    stages:
      - template: /eng/pipelines/templates/stages/release-azd-extension.yml
        parameters: 
          AzdExtensionId: azure.appservice
          SanitizedExtensionId: azure-appservice
          AzdExtensionDirectory: cli/azd/extensions/azure.appservice
