parameters:
  - name: DoPublish
    displayName: Check to run a release build
    type: boolean
    default: false

trigger: none
pr: none

extends:
  template: /eng/pipelines/templates/stages/1es-redirect.yml
  parameters:
    stages:
      - ${{ if and(eq(variables['Build.Repository.Name'], 'Azure/azure-dev'), eq(variables['Build.Reason'], 'Manual'), eq(parameters.DoPublish, true)) }}:
        - template: /eng/pipelines/templates/stages/publish.yml
