variables:
  - template: /eng/pipelines/templates/variables/globals.yml
  - name: NodeVersion
    value: 16

jobs:
  - job: CreateMatrix
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: MMSUbuntu20.04

    steps:
      - checkout: self

      - bash: curl -fsSL https://aka.ms/install-azd.sh | bash
        displayName: Install azd

      - pwsh: |
          $templateNames = (azd template list --output json | ConvertFrom-Json).name
          $matrix = @{}
          foreach ($template in $templateNames) {
            $jobName = $template.Replace('/', '_')
            $matrix[$jobName] = @{ TemplateName = $template }
          }
          # Adding extra test for capitals letters support. Using first template
          $firstTemplate = $($templateNames)[0]
          $capitalsTest = $firstTemplate.Replace('/', '_') + "-Upper-case-test"
          $matrix[$capitalsTest] = @{ TemplateName = $firstTemplate; UseUpperCase = "true" }

          Write-Host "Matrix:"
          Write-Host ($matrix | Format-List | Out-String)

          $matrixJson = ConvertTo-Json $matrix -Depth 100 -Compress
          Write-Host "##vso[task.setvariable variable=Matrix;isOutput=true]$matrixJson"
        name: Generate
        displayName: Generate matrix

  - job: TestTemplates
    dependsOn: CreateMatrix

    strategy:
      matrix: $[ dependencies.CreateMatrix.outputs['Generate.Matrix'] ]
      maxParallel: 10

    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: MMSUbuntu20.04

    steps:
      - checkout: self

      - template: /eng/pipelines/templates/steps/install-bicep.yml

      - template: /eng/pipelines/templates/steps/az-login.yml

      - pwsh: |
          if (!$env:AZDVERSION) {
            Write-Host "AzdVersion variable not set. Using 'daily'"
            Write-Host "##vso[task.setvariable variable=AzdVersion]daily"
          } else {
            Write-Host "Using specified azd version: $(AzdVersion)"
          }
        displayName: Ensure AzdVersion is set

      - pwsh: |
          if (!$env:TEMPLATEBRANCHNAME) {
            Write-Host "TemplateBranchName variable not set. Using 'staging'"
            Write-Host "##vso[task.setvariable variable=TemplateBranchName]staging"
          } else {
            Write-Host "Using specified azd version: $(TemplateBranchName)"
          }
        displayName: Ensure TemplateBranchName is set

      - pwsh: |
          if (!$env:DEPLOYLOCATION) {
            Write-Host "DeployLocation variable not set. Using 'eastus2'"
            Write-Host "##vso[task.setvariable variable=DeployLocation]eastus2"
          } else {
            Write-Host "Using specified azd version: $(DeployLocation)"
          }
        displayName: Ensure DeployLocation is set

      - bash: curl -fsSL https://aka.ms/install-azd.sh | bash -s -- --version '$(AzdVersion)' --verbose
        displayName: Install azd

      - pwsh: |
          $templateName = '$(TemplateName)'.Substring(14)
          $useUpperCaseName = '$(UseUpperCase)'
          $envPrefixName = "azd-template-test"
          if($useUpperCaseName -eq "true") {
            # Use upper case name for env prefix name
            $envPrefixName = "AZD-TEMPLATE-TEST"
          } 
          $resourceGroupName = "rg-$envPrefixName-$templateName-$(Build.BuildId)"
          Write-Host "Resource group name: $resourceGroupName"
          Write-Host "##vso[task.setvariable variable=ResourceGroupName]$resourceGroupName"
          Write-Host "##vso[task.setvariable variable=EnvPrefixName]$envPrefixName"
        displayName: Set Resource Group Name

      - task: Bash@3
        displayName: Test templates
        inputs:
          targetType: filePath
          filePath: templates/tests/test-templates.sh
          arguments: >
            -e '$(EnvPrefixName)'
            -t '$(TemplateName)'
            -b '$(TemplateBranchName)'
            -s '$(Build.BuildId)'
            -l '$(DeployLocation)'
            -p 'list'
          workingDirectory: templates/tests

      - pwsh: |
          $resourceGroupId = az group show `
            --resource-group '$(ResourceGroupName)' `
            --query id

          if ($LASTEXITCODE) {
            Write-Host "Could not get information for resource group: $(ResourceGroupName)"
            exit 0
          }

          az tag create `
            --resource-id $resourceGroupId `
            --tags DeleteAfter="$(Get-Date -AsUTC).ToString('o')"
        condition: always()
        displayName: Tag resource group for deletion
