pr:
  paths:
    include: 
      - eng/templates/**/*template-test*.yml
      - eng/pipelines/template-tests.yml

parameters:
- name: AzdVersion
  displayName: |
    Version of azd to test against.
    For PR builds, specify 'pr/<PRNumber>'. The PR validation build must have succeeded prior.
    For official build, 'daily', 'latest', or a specific version number: '0.3.0-beta.6-daily.1947218'.
  type: string
  default: daily

- name: TemplateList
  displayName: |
    Comma-delimited list of templates to test against (by default, results of azd template list). Example: 'Azure-Samples/todo-csharp-sql, Azure-Samples/todo-nodejs-mongo'
  type: string
  default: '(azd template list)'

- name: TemplateListFilter
  displayName: | 
    Regex filter expression to filter templates. Examples: 'csharp', 'terraform', 'python-mongo'
  type: string
  default: '.*'

- name: TemplateBranchName
  displayName: The template repository branch to test against
  type: string
  default: staging

- name: TemplateRunEnvironmentVariables
  displayName: |
    Comma-delimited list of environment variables in the format of (KEY=VALUE) to set for the template test run.
    Example: USE_APIM=true,ENV_SUFFIX=MYSUFFIX
  type: string
  default: ''

- name: AzureLocation
  displayName: Azure location for templates to be deployed to
  type: string
  default: eastus2

- name: CleanupHoursDelay
  displayName: Delay of cleanup for Azure resources for debugging purposes
  type: number
  default: 0

variables:
  - template: /eng/pipelines/templates/variables/globals.yml
  - name: NodeVersion
    value: 16

jobs:
- template: /eng/pipelines/templates/jobs/run-template-tests.yml
  parameters:
    AzdVersion: ${{ parameters.AzdVersion }}
    # This allows usage of azp run inside azure-dev 
    # to run template-tests against a new version of azd
    UseAzdVersionFromPrNumber: true
    TemplateList: ${{ parameters.TemplateList }}
    TemplateListFilter: ${{ parameters.TemplateListFilter }}
    TemplateBranchName: ${{ parameters.TemplateBranchName }}
    TemplateRunEnvironmentVariables: ${{ parameters.TemplateRunEnvironmentVariables }}
    AzureLocation: ${{ parameters.AzureLocation }}
    CleanupHoursDelay: ${{ parameters.CleanupHoursDelay }}
