pr: none
trigger: none

jobs:
  - job: AcceptInvites
    pool:
        name: azsdk-pool-mms-ubuntu-2004-general
        vmImage: MMSUbuntu20.04

    steps:
      - checkout: self
      - task: PowerShell@2
        inputs:
          pwsh: true
          targetType: filePath
          filePath: eng/scripts/Approve-RepoInvites.ps1
          arguments: -Owner 'Azure-Samples'
        env:
          GH_TOKEN: $(azuresdk-github-pat)
