name: global-cspell

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'eng/**' # Not required

jobs:
  cspell-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: Run spell check for templates
        with:
          node-version: "16"
      - run: npm install -g cspell
      - run: cspell lint '**/*.go' --config ./cli/azd/.vscode/cspell.yaml --root ./cli/azd --no-progress
      - run: cspell lint '**/*.ts' --config ./ext/vscode/.vscode/cspell.yaml --root ./ext/vscode --no-progress
      - run: cspell lint '**/*' --config ./.vscode/cspell.yaml --relative --no-progress
