name: azureDevOps-ext-ci

for test
on:
  pull_request:
    paths:
      - "ext/azuredevops/**"
      - ".github/workflows/devops-ext-ci.yml"
    branches: [main]

# If two events are triggered within a short time in the same PR, cancel the run of the oldest event
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: |
          npm install -g npm
          npm install
        working-directory: ./ext/azuredevops/setupAzd

      - name: Test
        run: npm test
        working-directory: ./ext/azuredevops/setupAzd
