name: ext-azure-ai-finetune-ci

on:
  pull_request:
    paths:
      - "cli/azd/extensions/azure.ai.finetune/**"
      - ".github/workflows/ext-azure-ai-finetune-ci.yml"
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    uses: ./.github/workflows/lint-go.yml
    with:
      working-directory: cli/azd/extensions/azure.ai.finetune
      go-version: "^1.25"
      golangci-lint-version: "v2.6"