name: ext-registry-check

on:
  pull_request_target:
    paths:
      - "cli/azd/extensions/registry.json"
    branches: [main]
    types: [opened, edited, synchronize, labeled, unlabeled, reopened, ready_for_review]

# If two events are triggered within a short time in the same PR, cancel the run of the oldest event
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  pull-requests: read
  contents: read

jobs:
  # NOTE: this is running with pull_request_target, which means that any check or code
  # that runs in here should be strictly controlled to come from stable/verified places
  # (for instance, our script below uses the .github folder from 'main', and not from the
  #  users' branch, we don't npm install any packages, etc..)
  extension-registry-check:
    name: Extension registry "core team approval required" check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Check extension registry update
        uses: actions/github-script@v9
        with:
          script: |
            const script = require('./.github/scripts/src/ext-registry-check.js');
            await script({ github, context, core });
  