name: ext-azure-ai-dataset-ci

on:
  pull_request:
    paths:
      - "cli/azd/extensions/azure.ai.dataset/**"
      - ".github/workflows/lint-ext-azure-ai-dataset.yml"
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write # required by reusable workflow lint-go.yml

jobs:
  lint:
    uses: ./.github/workflows/lint-go.yml
    with:
      working-directory: cli/azd/extensions/azure.ai.dataset
