name: scripts-ci

on:
  pull_request:
    paths:
      - ".github/scripts/**"
      - ".github/workflows/scripts-ci.yml"

# If two events are triggered within a short time in the same PR, cancel the run of the oldest event
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  vitest:
    name: Run test suite for our GitHub action support scripts
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: .github/scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          # 24 is the version that the GitHub actions script I'm running should also be 
          # running under.
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
