name: templates-ci

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - "templates/**"
      - ".github/workflows/templates-ci.yml"


permissions:
  contents: read
  pull-requests: write

jobs:
  bicep-lint:
    uses: ./.github/workflows/lint-bicep.yml
