name: templates-ci

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - "templates/**"
      - ".github/workflows/templates-ci.yml"


permissions:
  contents: read
  pull-requests: write

jobs:
  bicep-lint:
    uses: ./.github/workflows/lint-bicep.yml
  
  cspell-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install -g cspell
      - name: Spell check for templates
        run: cspell lint '**/*' --config ./templates/cspell.yaml --root ./templates --no-progress
