name: templates-ci

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - "templates/**"
      - ".github/workflows/templates-ci.yml"


permissions:
  contents: read
  pull-requests: write

jobs:
  bicep-lint:
    uses: ./.github/workflows/lint-bicep.yml
  
  cspell-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: Run spell check for templates
        with:
          node-version: "16"
      - run: npm install -g cspell
      - run: cspell lint '**/*' --config ./.vscode/cspell.yaml --relative --no-progress
