// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinit
// +build !wireinit

package cmd

import (
	"github.com/azure/azure-dev/cli/azd/cmd/action"
	"github.com/azure/azure-dev/cli/azd/internal"
	"github.com/azure/azure-dev/cli/azd/pkg/exec"
	"github.com/azure/azure-dev/cli/azd/pkg/output"
	"github.com/azure/azure-dev/cli/azd/pkg/templates"
	"github.com/azure/azure-dev/cli/azd/pkg/tools/git"
	"github.com/spf13/cobra"
)

// initors from wire.go:

func initInitAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags initFlags, args []string) (action.Action, error) {
	azdContext, err := newAzdContext()
	if err != nil {
		return nil, err
	}
	commandRunner := exec.NewCommandRunner()
	writer := output.GetDefaultWriter()
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	console := newConsoleFromOptions(o, writer, formatter)
	azCli := newAzCliFromOptions(o, commandRunner)
	gitCli := git.NewGitCliFromRunner(commandRunner)
	cmdInitAction, err := newInitAction(azdContext, commandRunner, console, azCli, gitCli, flags)
	if err != nil {
		return nil, err
	}
	return cmdInitAction, nil
}

func initInfraCreateAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags infraCreateFlags, args []string) (action.Action, error) {
	azdContext, err := newAzdContext()
	if err != nil {
		return nil, err
	}
	commandRunner := exec.NewCommandRunner()
	azCli := newAzCliFromOptions(o, commandRunner)
	writer := output.GetDefaultWriter()
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	console := newConsoleFromOptions(o, writer, formatter)
	cmdInfraCreateAction := newInfraCreateAction(flags, azdContext, azCli, console, formatter, writer)
	return cmdInfraCreateAction, nil
}

func initDeployAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags deployFlags, args []string) (action.Action, error) {
	azdContext, err := newAzdContext()
	if err != nil {
		return nil, err
	}
	commandRunner := exec.NewCommandRunner()
	azCli := newAzCliFromOptions(o, commandRunner)
	writer := output.GetDefaultWriter()
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	console := newConsoleFromOptions(o, writer, formatter)
	cmdDeployAction, err := newDeployAction(flags, azdContext, azCli, console, formatter, writer)
	if err != nil {
		return nil, err
	}
	return cmdDeployAction, nil
}

func initUpAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags upFlags, args []string) (action.Action, error) {
	azdContext, err := newAzdContext()
	if err != nil {
		return nil, err
	}
	commandRunner := exec.NewCommandRunner()
	writer := output.GetDefaultWriter()
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	console := newConsoleFromOptions(o, writer, formatter)
	azCli := newAzCliFromOptions(o, commandRunner)
	gitCli := git.NewGitCliFromRunner(commandRunner)
	cmdInitFlags := flags.initFlags
	cmdInitAction, err := newInitAction(azdContext, commandRunner, console, azCli, gitCli, cmdInitFlags)
	if err != nil {
		return nil, err
	}
	cmdInfraCreateFlags := flags.infraCreateFlags
	cmdInfraCreateAction := newInfraCreateAction(cmdInfraCreateFlags, azdContext, azCli, console, formatter, writer)
	cmdDeployFlags := flags.deployFlags
	cmdDeployAction, err := newDeployAction(cmdDeployFlags, azdContext, azCli, console, formatter, writer)
	if err != nil {
		return nil, err
	}
	cmdUpAction := newUpAction(cmdInitAction, cmdInfraCreateAction, cmdDeployAction, console)
	return cmdUpAction, nil
}

func initInfraDeleteAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags infraDeleteFlags, args []string) (action.Action, error) {
	azdContext, err := newAzdContext()
	if err != nil {
		return nil, err
	}
	commandRunner := exec.NewCommandRunner()
	azCli := newAzCliFromOptions(o, commandRunner)
	writer := output.GetDefaultWriter()
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	console := newConsoleFromOptions(o, writer, formatter)
	cmdInfraDeleteAction := newInfraDeleteAction(flags, azdContext, azCli, console)
	return cmdInfraDeleteAction, nil
}

func initEnvSetAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags struct{}, args []string) (action.Action, error) {
	azdContext, err := newAzdContext()
	if err != nil {
		return nil, err
	}
	commandRunner := exec.NewCommandRunner()
	azCli := newAzCliFromOptions(o, commandRunner)
	writer := output.GetDefaultWriter()
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	console := newConsoleFromOptions(o, writer, formatter)
	cmdEnvSetAction := newEnvSetAction(azdContext, azCli, console, o, args)
	return cmdEnvSetAction, nil
}

func initEnvSelectAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags struct{}, args []string) (action.Action, error) {
	azdContext, err := newAzdContext()
	if err != nil {
		return nil, err
	}
	cmdEnvSelectAction := newEnvSelectAction(azdContext, args)
	return cmdEnvSelectAction, nil
}

func initEnvListAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags struct{}, args []string) (action.Action, error) {
	azdContext, err := newAzdContext()
	if err != nil {
		return nil, err
	}
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	writer := output.GetDefaultWriter()
	cmdEnvListAction := newEnvListAction(azdContext, formatter, writer)
	return cmdEnvListAction, nil
}

func initEnvNewAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags envNewFlags, args []string) (action.Action, error) {
	azdContext, err := newAzdContext()
	if err != nil {
		return nil, err
	}
	commandRunner := exec.NewCommandRunner()
	azCli := newAzCliFromOptions(o, commandRunner)
	writer := output.GetDefaultWriter()
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	console := newConsoleFromOptions(o, writer, formatter)
	cmdEnvNewAction := newEnvNewAction(azdContext, azCli, flags, console)
	return cmdEnvNewAction, nil
}

func initEnvRefreshAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags struct{}, args []string) (action.Action, error) {
	azdContext, err := newAzdContext()
	if err != nil {
		return nil, err
	}
	commandRunner := exec.NewCommandRunner()
	azCli := newAzCliFromOptions(o, commandRunner)
	writer := output.GetDefaultWriter()
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	console := newConsoleFromOptions(o, writer, formatter)
	cmdEnvRefreshAction := newEnvRefreshAction(azdContext, azCli, o, console, formatter, writer)
	return cmdEnvRefreshAction, nil
}

func initEnvGetValuesAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags struct{}, args []string) (action.Action, error) {
	azdContext, err := newAzdContext()
	if err != nil {
		return nil, err
	}
	writer := output.GetDefaultWriter()
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	console := newConsoleFromOptions(o, writer, formatter)
	commandRunner := exec.NewCommandRunner()
	azCli := newAzCliFromOptions(o, commandRunner)
	cmdEnvGetValuesAction := newEnvGetValuesAction(azdContext, console, formatter, writer, azCli, o)
	return cmdEnvGetValuesAction, nil
}

func initLoginAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags loginFlags, args []string) (action.Action, error) {
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	writer := output.GetDefaultWriter()
	commandRunner := exec.NewCommandRunner()
	azCli := newAzCliFromOptions(o, commandRunner)
	cmdLoginAction := newLoginAction(formatter, writer, azCli, flags)
	return cmdLoginAction, nil
}

func initMonitorAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags monitorFlags, args []string) (action.Action, error) {
	azdContext, err := newAzdContext()
	if err != nil {
		return nil, err
	}
	commandRunner := exec.NewCommandRunner()
	azCli := newAzCliFromOptions(o, commandRunner)
	writer := output.GetDefaultWriter()
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	console := newConsoleFromOptions(o, writer, formatter)
	cmdMonitorAction := newMonitorAction(azdContext, azCli, console, flags)
	return cmdMonitorAction, nil
}

func initPipelineConfigAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags pipelineConfigFlags, args []string) (action.Action, error) {
	azdContext, err := newAzdContext()
	if err != nil {
		return nil, err
	}
	writer := output.GetDefaultWriter()
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	console := newConsoleFromOptions(o, writer, formatter)
	cmdPipelineConfigAction := newPipelineConfigAction(azdContext, console, flags)
	return cmdPipelineConfigAction, nil
}

func initRestoreAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags restoreFlags, args []string) (action.Action, error) {
	writer := output.GetDefaultWriter()
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	console := newConsoleFromOptions(o, writer, formatter)
	azdContext, err := newAzdContext()
	if err != nil {
		return nil, err
	}
	cmdRestoreAction := newRestoreAction(flags, console, azdContext)
	return cmdRestoreAction, nil
}

func initShowAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags showFlags, args []string) (action.Action, error) {
	writer := output.GetDefaultWriter()
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	console := newConsoleFromOptions(o, writer, formatter)
	azdContext, err := newAzdContext()
	if err != nil {
		return nil, err
	}
	cmdShowAction := newShowAction(console, formatter, writer, azdContext, flags)
	return cmdShowAction, nil
}

func initTemplatesListAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags templatesListFlags, args []string) (action.Action, error) {
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	writer := output.GetDefaultWriter()
	templateManager := templates.NewTemplateManager()
	cmdTemplatesListAction := newTemplatesListAction(flags, formatter, writer, templateManager)
	return cmdTemplatesListAction, nil
}

func initTemplatesShowAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags struct{}, args []string) (action.Action, error) {
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	writer := output.GetDefaultWriter()
	templateManager := templates.NewTemplateManager()
	cmdTemplatesShowAction := newTemplatesShowAction(formatter, writer, templateManager, args)
	return cmdTemplatesShowAction, nil
}

func initVersionAction(cmd *cobra.Command, o *internal.GlobalCommandOptions, flags versionFlags, args []string) (action.Action, error) {
	formatter, err := output.GetCommandFormatter(cmd)
	if err != nil {
		return nil, err
	}
	writer := output.GetDefaultWriter()
	cmdVersionAction := newVersionAction(flags, formatter, writer)
	return cmdVersionAction, nil
}
