stages:
  - stage: Sign
    dependsOn: BuildAndTest
    variables: 
      - template: /eng/pipelines/templates/variables/globals.yml
      - template: /eng/pipelines/templates/variables/image.yml
    
    jobs:
      - job: Sign
        ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual') }}:
          displayName: Sign
        ${{ else }}:
          displayName: SKIP Signing
        
        pool:
          name: $(WINDOWSPOOL)
          image: $(WINDOWSVMIMAGE)
          os: windows

        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: vsix
              path: vsix

          - ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual') }}:
            - template: pipelines/steps/azd-azdo-extension-signing.yml@azure-sdk-build-tools
              parameters:
                Path: $(Build.SourcesDirectory)\vsix
                Pattern: '*.vsix'

          - ${{ else }}:
            - pwsh: Write-Host "Skipping signing. Build reason - $(Build.Reason)"
              displayName: Signing process skipped for non-release build

          - pwsh: |
              New-Item -ItemType Directory -Path signed
              Copy-Item vsix/ signed/ -Recurse
            displayName: Copy signing outputs
            condition: always()

        templateContext:
          outputs:
            - output: pipelineArtifact
              condition: succeeded()
              displayName: Publish Signed Artifacts
              artifact: signed
              path: signed/

            - output: pipelineArtifact
              condition: failed()
              displayName: Publish failed Signed Artifacts
              artifact: signed-FailedAttempt$(System.JobAttempt)
              path: signed/
