parameters:
  - name: StageName
    type: string
    default: Notice
  - name: StageDependsOn
    type: object
    default: []
  - name: StageCondition
    type: string
    default: ''

stages:
  - stage: ${{ parameters.StageName }}
    dependsOn: ${{ parameters.StageDependsOn }}
    ${{ if ne(parameters.StageCondition, '') }}:
      condition: ${{ parameters.StageCondition }}
    variables:
      - template: /eng/pipelines/templates/variables/globals.yml
      - name: EnableGoCliScan
        value: true

    jobs:
      - job: PoliCheck
        pool:
          name: azsdk-pool
          demands: ImageOverride -equals windows-2022
        timeoutInMinutes: 120
        steps:
          - template: /eng/common/pipelines/templates/steps/policheck.yml
            parameters:
              ExclusionDataBaseFileName: AzDevPoliCheckExclusion
              PublishAnalysisLogs: false

      - template: /eng/pipelines/templates/jobs/build-scan-cli.yml

      - template: /eng/pipelines/templates/jobs/build-scan-vscode.yml

      - job: GenerateNoticeTxt
        pool:
          name: azsdk-pool
          demands: ImageOverride -equals ubuntu-22.04

        templateContext:
          outputs:
            - output: pipelineArtifact
              targetPath: $(Build.SourcesDirectory)/NOTICE.txt
              artifactName: notice

        steps:
          - task: ComponentGovernanceComponentDetection@0

          - task: notice@0
            displayName: Generate NOTICE.txt file
            inputs:
              outputfile: $(Build.SourcesDirectory)/NOTICE.txt
              outputformat: text
