parameters:
  - name: BuildMatrix
    type: object
    default:
      Windows:
        Pool: $(WINDOWSPOOL)
        ImageKey: image
        OSVmImage: $(WINDOWSVMIMAGE)
        OS: windows
        Variables: {}

      Linux:
        Pool: $(LINUXPOOL)
        ImageKey: image
        OSVmImage: $(LINUXVMIMAGE)
        OS: linux
        Variables: 
          UploadArtifact: 'true'
          Codeql.Enabled: true
          Codeql.SkipTaskAutoInjection: false
          Codeql.BuildIdentifier: vscode_linux

      Mac:
        Pool: Azure Pipelines
        ImageKey: vmImage
        OSVmImage: $(MACVMIMAGE)
        OS: macOS
        Variables: {}

stages:
  - stage: BuildAndTest
    variables: 
      - template: /eng/pipelines/templates/variables/globals.yml
      - template: /eng/pipelines/templates/variables/image.yml

    jobs:
      - ${{ each build in parameters.BuildMatrix }}:
          - template: /eng/pipelines/templates/jobs/vscode-build.yml
            parameters:
              NameSuffix: ${{ build.key }}
              Pool: ${{ build.value.Pool }}
              ImageKey: ${{ build.value.ImageKey }}
              OSVmImage: ${{ build.value.OSVmImage }}
              OS: ${{ build.value.OS }}
              Variables: ${{ build.value.Variables }} 
