stages: 
  - stage: PublishManual
    dependsOn: Sign
    condition: >-
      and(
        succeeded(),
        ne(variables['Skip.Release'], 'true'),
        or(
          eq('Manual', variables['BuildReasonOverride']),
          and(
            eq('', variables['BuildReasonOverride']),
            eq(variables['Build.Reason'], 'Manual')
          )
        )
      )

    variables: 
      - template: /eng/pipelines/templates/variables/globals.yml
      - template: /eng/pipelines/templates/variables/image.yml

    jobs:
      - deployment: Publish_Release
        environment: package-publish
        pool:
          name: azsdk-pool-mms-ubuntu-2004-general
          image: azsdk-pool-mms-ubuntu-2004-1espt
          os: linux

        templateContext:
          inputs:
            - input: pipelineArtifact
              artifactName: release
              targetPath: release

            - input: pipelineArtifact
              artifactName: changelog
              targetPath: changelog
        
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /eng/pipelines/templates/steps/vscode-set-metadata-variables.yml

                - template: /eng/pipelines/templates/steps/publish-vscode.yml
                  parameters:
                    PublishLocations: azd/vscode/release/$(VSIX_VERSION);azd/vscode/release/latest
                    TagRepository: true
                    PublishToMarketplace: true

      - job: Publish_Shield
        dependsOn: Publish_Release

        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux

        steps:
          - template: /eng/pipelines/templates/steps/publish-shield.yml
            parameters:
              ArtifactName: shield-vscode
              ArtifactDownloadPath: shields/vscode
              ArtifactFilename: vscode.json
              StorageContainerName: ${{ parameters.StorageContainerName }}
              PublishDestination: azd/vscode/latest


      - job: Increment_Version
        condition: >-
          and(
            succeeded(),
            ne('true', variables['Skip.IncrementVersion'])
          )
        dependsOn: Publish_Release

        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux

        templateContext:
          inputs:
            - input: checkout
              repository: self

          steps:
            - task: PowerShell@2
              inputs:
                pwsh: true
                targetType: filePath
                filePath: eng/scripts/Update-VscodeExtensionVersion.ps1
              displayName: Increment VSCode Extension version

            - template: /eng/common/pipelines/templates/steps/create-pull-request.yml
              parameters:
                PRBranchName: vscode-version-increment-$(Build.BuildId)
                CommitMsg: Increment VSCode Extension version after release
                PRTitle: Increment VSCode Extension version after release
